- README.md
- lib/preview.bash
$ export BASH_PROFILE=whatever
$ source ~/.bash_profile
The available custom prompts will all be displayed in order, so that it is easy to decide which one you like best
> Add ability to preview themes

- install.sh
> Choose correct bash config file based on the OS

- themes/powerline-naked/powerline-naked.theme.bash
New theme available, Powerline-naked.
> Added Powerline-naked theme

- install.sh
Hi,
The installation will be hard for users to just press *n* and then press <*enter*>.
It will be better to just press <*enter*> for **NO**.
I add a red colour for warning message if user enter something other that *y*, *n*, <*space*> or <*enter*>.
I hope that there is a CONTRIBUTING.md too for *coding guidelines*.
> Minor edits to install.sh for easy install

- plugins/available/battery.plugin.bash
- themes/powerline-multiline/powerline-multiline.theme.bash
- Added a clock
- Added the battery status
- Visual improvements
Screenshot→ http://imgur.com/e7kFyBQ
> Improved Powerline-multiline theme

- completion/available/git.completion.bash
The title says it. Also formatted lines to keep them at max 80 chars.
> Add --force-with-lease to git push autocompletion

- themes/dulcie/dulcie.theme.bash
Hi! I made a very simple theme called "Dulcie" displaying the git info after a normal PS1 prompt. Enjoy!
> Add dulcie theme as a basic PS1 prompt with git info

- completion/available/bash-it.completion.bash
- lib/helpers.bash
It's showing the same output as `bash-it show completions`,
to keep things simple.
> Added support for `bash-it help completions` command.

- plugins/available/nginx.plugin.bash
- template/bash_profile.template.bash
These settings shouldn't be in the profile template, as they only make sense when used with nginx.
If you're using nginx, you can enable the nginx plugin.
> Moved nginx settings to plugin.

- README.md
- plugins/available/proxy.plugin.bash
Supports setting/unsetting proxy variables in the shell, and for tools like Git, npm, SVN, SSH.
Also added documentation in the main `README.md`.
The SVN support is pretty ugly, as it uses inline Python code to read/write the SVN config file (which follows the Windows .INI format).
> Added proxy plugin.

- completion/available/git.completion.bash
This PR updates the git bash completion to https://github.com/git/git/commit/6b1258b07b8ad5671f36bf7e998e905a0142c223.
Fixes #299.
> Updated git completion

- completion/available/vagrant.completion.bash
This PR updates the vagrant bash completion to the latest commit https://github.com/kura/vagrant-bash-completion/commit/e720d90ae9a6589eb13c578b40a503e902d4897c
> Updated vagrant bash completion

- install.sh
This PR is according to your comments on PR #454.
I closed my previous [PR](https://github.com/Bash-it/bash-it/pull/454) since i made some mess with my commits.
>  PR regarding bug #453

- install.sh
All of the install questions are now using the same syntax and semantics for read/echo/case.
> Updated install script

- aliases/available/fuck.aliases.bash
https://github.com/nvbn/thefuck
> Added aliases for nvbn/thefuck

- aliases/available/emacs.aliases.bash
Adding aliases for some important features of emacs-nox users
> Adding emacs daemon and emacsclient -t aliases for emacs-nox users

- themes/powerline-multiline/powerline-multiline.theme.bash
- themes/powerline/powerline.theme.bash
This ports sudo indicator feature to powerline theme, originally added
to powerline-multiline theme in PR #452.
> Port sudo indicator to powerline theme

- aliases/available/tmux.aliases.bash
My personal Tmux (terminal multiplexer) aliases for named sessions.
Hope it helps somebody.
> My personal tmux aliases

- lib/helpers.bash
- plugins/available/nginx.plugin.bash
- plugins/available/node.plugin.bash
please review this PR, it's trying to fix https://github.com/Bash-it/bash-it/issues/482; the duplicates in PATH variable. we started the conversation here already https://github.com/Bash-it/bash-it/issues/482.
I'm planing to add 1 more commit to fix the other places with duplicate PATH appends.
> Fix duplicate entries in path

- plugins/available/aws.plugin.bash
- Fixed export option to work in Mac (I think)
- Added remove option
- Other minor changes
> Updated AWS plugin

- plugins/available/aws.plugin.bash
Add completion to the awskeys function in the AWS plugin.
> Added completion to AWS plugin

- lib/helpers.bash
- plugins/available/latex.plugin.bash
- plugins/available/pipsi.plugin.bash
- plugins/available/pyenv.plugin.bash
- plugins/available/rbenv.plugin.bash
- plugins/available/ruby.plugin.bash
- plugins/available/todo.plugin.bash
- test/plugins/ruby.plugin.bats
sorry, that it took a bit of time to get back to fixing the rest of duplicate entries in the PATH
> [pathmunge] remove duplicate entry into PATH variable on reload command

- plugins/available/docker.plugin.bash
Changed port to 2376.
Added cert path and TLS verify.
> Updated boot2docker settings

- plugins/available/textmate.plugin.bash
Fix for http://stackoverflow.com/q/31516894/1228454
> Added check for presence of textmate executable

- README.md
> added simple uninstall instructions

- plugins/available/pyenv.plugin.bash
pyenv `PATH` should be `$HOME/.pyenv/bin`
> https://github.com/yyuu/pyenv#basic-github-checkout
> fix pyenv plugins PATH env

- themes/cupcake/cupcake.theme.bash
> New theme, named 'cupcake'

- aliases/available/general.aliases.bash
no more 'is a folder' cat errors! :-)
> Added 'catt' alias which displays content whatever regular file or folder

- completion/available/capistrano.completion.bash
Update capistrano completion
* Add the compatibility for capistrano gem version 3
* Use all tasks for completion
> Add the compatibility for capistrano gem version 3

- themes/axin/axin.theme.bash
Hey, I have created a new theme 'axin', it's based on the theme 'sexy'.:)
> a new theme:axin,based on 'sexy'

- themes/base.theme.bash
- themes/bobby/bobby.theme.bash
`bobby` is my favourite theme on `bash-it`, but it does not have `time` on prompt, which is important.
> adding datetime and battery percentage to theme 'bobby'

- aliases/available/apt.aliases.bash
- themes/binaryanomaly/binaryanomaly.theme.bash
A new theme I'd like to contribute.
> New binaryanomaly theme

- completion/available/hub.completion.bash
- plugins/available/gh.plugin.bash
- plugins/available/hub.plugin.bash
- Mark gh plugin as deprecated, hub is suggested as replacement
- Add hub plugin and completion
> Hub support

- README.md
- themes/base.theme.bash
Add the flag `SCM_GIT_IGNORE_UNTRACKED` to ignore *untracked* files in git prompt.
> Ignore untracked files

- completion/available/projects.completion.bash
- plugins/available/projects.plugin.bash
shameless port of zsh's projects plugin
> added projects plugin and completion

- README.md
- install.sh
- template/bash_profile.template.bash
> Allow for any install location

- plugins/available/visual-studio-code.plugin.bash
Only required on Mac OS X. More details here:
https://code.visualstudio.com/Docs/editor/setup
> Added Visual Studio Code plugin

- install.sh
> Fix for OS X installation

- completion/available/gradle.completion.bash
Code borrowed from gist:
https://gist.github.com/nolanlawson/8694399
> Add gradle completion

- themes/powerline-multiline/powerline-multiline.theme.bash
- New env var (THEME_PROMPT_USERINFO_MODE) to choose "user info" mode:
Possible values:
default: same behaviour as before
sudo: only show a "hint" when sudo credentials are cached
any other values disables this segment.
> Now, right prompt can be totally disabled in powerline multiline theme

- plugins/available/jenv.plugin.bash
Add plugin for [jenv](https://github.com/gcuisinier/jenv)
> Add jenv plugin

- aliases/available/apt.aliases.bash
> no sudo for apt-cache

- plugins/available/extract.plugin.bash
* add a short help message
* add multiple formats support
> add multi formats

- themes/pro/pro.theme.bash
> Added pro theme

- completion/available/terraform.completion.bash
Not providing help for the speicifc commands yet but at least complete
the available commands as a starting point
> Added simple support for terraform

- install.sh
> Added base plugin to default install

- plugins/available/nvm.plugin.bash
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/nvm.rb#L27
> Enable discovery and use of nvm installed via homebrew.

- completion/available/system.completion.bash
- themes/morris/morris.theme.bash
1. someone like me may want to use the completion functions that comes with the distribution.
2. add a simple theme.
> add system default completion

- CONTRIBUTING.md
- README.md
@edubxb @tswicegood Please feel free to review/add/change...
I've tried to summarize a couple of common rules and guidelines, nothing too fancy.
> Added first draft of contribution guidelines

- plugins/available/percol.plugin.bash
Use percol to search&select history,
> add plugin:percol

- install.sh
Removed tabs, using 2 spaces everywhere.
> Fixed indentation

- completion/available/docker.completion.bash
This completion was sourced from the official repo here: https://github.com/docker/docker/blob/master/contrib/completion/bash/docker
> Adding docker command line client completion

- themes/primer/primer.theme.bash
Just shows the time, directory, and scm info. Nice and short.
> Added Primer (minimal time) theme, based off of the candy theme.

- themes/powerline-multiline/README.md
Some minor changes in spelling, wording and formatting.
> Fixed spelling and wording

- themes/base.theme.bash
Fix an error introduced in PR https://github.com/Bash-it/bash-it/pull/649
> Fix an error when showing the status of a git repo

- aliases/available/emacs.aliases.bash
> Remove unnecessary double quotes in alias

- README.md
- completion/available/bash-it.completion.bash
- lib/helpers.bash
> Add update subcommand

- aliases/available/git.aliases.bash
- Reverted some changes added in https://github.com/Bash-it/bash-it/commit/bea8beca6f93eb983126b5e6af61be459e3c94b8
- Added new aliases
- Changed gg again (https://github.com/Bash-it/bash-it/commit/6d453fe1e4fae88bd7fccc269e87e824b3ab048f)
> Update some git aliases

- completion/available/ssh.completion.bash
- plugins/available/ssh.plugin.bash
> Added support for multiple aliases/hostnames in single line for ssh completion and plugin

- completion/available/git.completion.bash
Simply updating the file from the git source code mirror: https://github.com/git/git/blob/master/contrib/completion/git-completion.bash.
> Updating git.completion.bash to latest version.

- themes/cooperkid/cooperkid.theme.bash
I modified the Mr Briggs theme and made it more suitable for me and, I want to share it.
It is a 'simplistic' version of Mr Briggs. Removes the number of command executed, the commit hash between parenthesis, the prompt symbol, changes the prompt char, merges the host and path  into one variable and changes the some colors of the displayed variables.
It looks something like this:
> Adds cooperkid theme by AlfredoBejarano

- aliases/available/curl.aliases.bash
Here's a few convenience aliases I use for curl that save a lot of keystrokes.
> Added convenience aliases for curl

- plugins/available/killrails.plugin.bash
- test/lib/search.bats
Fixes some of the items introduced in #720 
* Indentation
* Unit tests
* Group meta information
> Killrails fix

- themes/mairan/mairan.theme.bash
Zork with a different color scheme.
> Add new theme 'mairan' (based on 'zork')

- completion/available/tmux.completion.bash
> [#734] tmux-completion when trying to use withiout running server

- template/bash_profile.template.bash
As https://github.com/xvzf/vcprompt is not valid
> Updated reference for vcprompt

- plugins/available/git.plugin.bash
Also fixed some typos in the function.
> Added missing meta tags for gittowork

- themes/tonotdo/tonotdo.theme.bash
> Bash-it theme inspired by oh-my-zsh tonotdo.

- aliases/available/git.aliases.bash
- Useful for seeing your changes before committing
Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>
> Add `gap` alias for `git add -p`

- completion/available/docker-compose.bash
- completion/available/docker-machine.bash
- completion/available/docker.completion.bash
CLI completions are from:
- docker : https://github.com/docker/docker/blob/master/contrib/completion/bash/docker
- docker-compose : https://github.com/docker/compose/blob/master/contrib/completion/bash/docker-compose
- docker-machine : https://github.com/docker/machine/blob/master/contrib/completion/bash/docker-machine.bash
Was thinking about whether I should split these into separate PRs as per contribution guideline but docker items seems related to one change? Can change is required
> Update docker & add docker-compose/docker-machine CLI completion

- aliases/available/vim.aliases.bash
New PR instead of borked https://github.com/Bash-it/bash-it/pull/750
> improved vim aliases

- lib/helpers.bash
Added the ability to list your custom aliases with 'bash-it help alias custom' and 'bash-it help alias'.
Particularly useful for forgetful people like me. 👍
> Custom alias help

- themes/wanelo/wanelo.theme.bash
Thought we'd contribute our workstation's theme we've been using for the last year.
If a zero status is returned, you get a ❤️  emoji, if non-zero you get 💔 .
attention: @hjhart
> Wanelo Pairing workstations theme

- README.md
- lib/helpers.bash
- template/bash_profile.template.bash
> 763: Automatically reload shell after enabling and disabling things.

- themes/powerline-multiline/powerline-multiline.theme.bash
- themes/powerline/powerline.theme.bash
> Revert "Changes to sudo check for powerline themes"

- completion/available/apm.completion.bash
Added completion for Atom Package Manager (`apm`)
> add completion for apm

- completion/available/todo.completion.bash
- Updated todo completion script to [latest version](https://github.com/ginatrapani/todo.txt-cli/blob/master/todo_completion) (the latest version includes some extra options)
> update completion for todo to latest version

- completion/available/nvm.completion.bash
added Bash completion for Node Version Manager (nvm)
> add completion for nvm

- themes/base.theme.bash
revert #797 as discussed on #804
> revert pull 797

- bash_it.sh
- completion/available/npm.completion.bash
> fix npm completion

- completion/available/jungle.completion.bash
https://github.com/achiku/jungle
> Add jungle completion

- themes/powerline-multiline/README.md
- themes/powerline-multiline/powerline-multiline.base.bash
- themes/powerline-multiline/powerline-multiline.theme.bash
- themes/powerline-naked/README.md
- themes/powerline-naked/powerline-naked.base.bash
- themes/powerline-naked/powerline-naked.theme.bash
- themes/powerline-plain/README.md
- themes/powerline-plain/powerline-plain.base.bash
- themes/powerline-plain/powerline-plain.theme.bash
- themes/powerline/README.md
- themes/powerline/powerline.base.bash
- themes/powerline/powerline.theme.bash
- Split functions and options in two files
- Unified functions and shared in all themes
- Add README.md for all themes
> Refactor of all powerline themes

- completion/available/vault.completion.bash
This is bash completion for Vault by HashiCorp.
This was sourced from https://github.com/iljaweis/vault-bash-completion/blob/master/vault-bash-completion.sh
If that's against the rules I understand I read them and didn't see anything that would cover something like this.
Thank you for your consideration.
> Adding vault completion

- README.md
I add install .sh `--silent` option description in README.
> [README] add --silent description in README

- completion/available/hub.completion.bash
update hub completion to the [latest version](https://github.com/github/hub/blob/57f1ff3981e2c1f9297f35a90e74dd12025a6fe9/etc/hub.bash_completion.sh).
> update hub completion

- plugins/available/go.plugin.bash
> add go plugin

- completion/available/go.completion.bash
> add go completion

- themes/brainy/README.md
- themes/brainy/brainy.theme.bash
- add Todo.txt status segment
- add ssh login indicator
- add battery charging indicator
- refactor
- minor updates
> update brainy theme

- README.md
- bash_it.sh
- lib/appearance.bash
This allows for having a separate and versioned custom folder of scripts.
> Allow for having custom scripts outside of bash-it.

- themes/purity/purity.theme.bash
If you're open to accepting PRs for new themes, I'd like to share my theme with the community.
- Minimal, clean, & elegant. Inspired by [ZSH Pure Theme](https://github.com/sindresorhus/pure)
- Bash prompt color changes based on result of last command:
- `red` arrow indicates failed commands (non-0 exit codes)
- `green` arrow indicates successful commands (0 exit code)
- Display SCM info: branch name, untracked, unstaged, staged files
> New Theme: Purity

- themes/kitsune/kitsune.theme.bash
Kitsune theme, used the morris theme as base and changed PS1.
> Added theme Kitsune

- plugins/available/docker.plugin.bash
Added function that shows the content of a Docker archive, created through `docker save`.
Based on this question: http://stackoverflow.com/q/38326532/1228454
> Added docker-archive-content function

- template/bash_profile.template.bash
Fixed a minor typo in `template/bash_profile.template.bash`
> Fixed a typo

- completion/available/vault.completion.bash
Adding more updates to vault completion same as https://github.com/Bash-it/bash-it/pull/860
> Adding new updates for vault completions

- lib/search.bash
> Fix search command for RedHat based distributions

- README.md
> add bash-it-docker to readme

- themes/base.theme.bash
> Fix for issue #883

- themes/90210/90210.theme.bash
Hi, since #892 I decided to create a theme based on the PS1 config that I use. Hope you guys like it! ;)
> new theme 90210 added

- aliases/available/git.aliases.bash
Simply add another alias for git to complete list of operations
> Add 'git rm' alias 'grm'

- aliases/available/git.aliases.bash
More git aliases I'm using.  I checked to see if they conflict with anything already present and I didn't see anything.  If an explanation is needed for each of them I can provide one.
> Adding more git aliases

- aliases/available/git.aliases.bash
Fixes https://github.com/Bash-it/bash-it/issues/921
> Simplify the `git diff` alias

- .gitattributes
> Added .gitattributes file to enforce LF line endings

- completion/available/rvm.completion.bash
Adding RVM Completion from source: https://rvm.io/workflow/completion
> Add RVM Completion

- README.md
> More documentation for Theme location

- themes/font/font.theme.bash
- Use new user_host_prompt to add more configurability to theme
- Disable default clock being shown
> Update font theme

- template/bash_profile.template.bash
- themes/base.theme.bash
Github-Issues: #955 
Signed-off-by: 林博仁 <Buo.Ren.Lin@gmail.com>
> Fix more space-in-path-proof issues

- plugins/available/dirs.plugin.bash
fixed spelling and grammar in dirs plugin
> fixed spelling and grammar

- themes/atomic/README.md
- themes/atomic/atomic.theme.bash
- Brainy theme reverted to original.
- add Atomic theme based on the original brainy.
- Special thanks to @MunifTanjim and @nwinkler for such excellent job.
> New theme Atomic added and reverted the theme Brainy by default

- plugins/available/autojump.plugin.bash
Add autojump package detection in Arch Linux
> Add Arch Linux support for autojump plugin

- plugins/available/battery.plugin.bash
- themes/atomic/atomic.theme.bash
Operating system detection was added to show the percentage of the battery in the promt.
- Detection of Linux, OSX and Windows systems was added.
- In windows systems detect if you use msys or cygwin.
- Displays the percentage of the battery in all operating systems.
> Improvements in Atomic theme

- themes/atomic/README.md
- themes/atomic/atomic.theme.bash
Updated the README of the theme.
Minor fixes on the theme battery indicator.
:raised_hands: :bowtie: :runner:
> Update ATOMIC Theme

- plugins/available/nvm.plugin.bash
> Remove prefixed space

- plugins/available/base.plugin.bash
I tried the command myip. I can't get ip. I fix the issue and strengthen the command. try more url to get myip before it is successful.
> fix and strengthen the command myip

- plugins/available/fzf.plugin.bash
Added some functions that allow to quickly edit files using `fzf`.
> Fzf plugin

- plugins/available/base.plugin.bash
fix #993 
if using mkcd many dirs, it will make all dirs and cd into the lastest one.
> fix mkcd issue #993

- plugins/available/base.plugin.bash
- themes/bakke/bakke.theme.bash
Only fix ips issue as your  propose.
> fix ips issue #998

- plugins/available/battery.plugin.bash
- themes/atomic/atomic.theme.bash
Improvements in the theme.
Added **pmset** command that improves the process of detecting the battery and its percentage in OSX.
> Changes in the battery plugin and in the Atomic Theme

- plugins/available/base.plugin.bash
changed URL to non-www as well
- this fixes issue #1011
> added `-L` to curl options to avoid empty responses

- completion/available/bash-it.completion.bash
- lib/helpers.bash
- test/completion/bash-it.completion.bats
Add a helper to show the current git SHA of the installed git repo.
Signed-off-by: Mike Fiedler <miketheman@gmail.com>
> Add version to commands

- CONTRIBUTING.md
- README.md
The days of breaking at 78 or 72 characters have mostly passed, but I don't like the opposite extreme either.
One-line-per-paragraph has some of the same disadvantages as short lines,
such as noisy diffs and arbitrary linebreaks (e.g. in the middle of example commands).
Would it be acceptable if I lazily introduced linebreaks as in the included diff? 
```diff
diff --git a/CONTRIBUTING.md b/CONTRIBUTING.md
index 5600fa3..7bca19d 100644
--- a/CONTRIBUTING.md
+++ b/CONTRIBUTING.md
@@ -1,38 +1,56 @@
-When contributing a new feature, a bug fix, a new theme, or any other change to Bash-it, please consider the following guidelines. Most of this is common sense, but please try to stick to the conventions listed here.
+When contributing a new feature, a bug fix, a new theme, or any other change to …
```
> Break lines on sentences or phrases

- completion/available/ssh.completion.bash
... neither should it's autocomplete,
please?  
:D
> ssh doesn't care about case

- completion/available/pipenv.completion.bash
https://github.com/kennethreitz/pipenv
> Add pipenv completion support

- completion/available/awless.completion.bash
https://github.com/wallix/awless
> Add awless completion support

- completion/available/gradle.completion.bash
https://github.com/gradle/gradle-completion
> Upgrade gradle completion to the official one

- completion/available/travis.completion.bash
https://github.com/travis-ci/travis.rb
and more @tswicegood 😉
> Add travis completion

- themes/brainy/brainy.theme.bash
I have followed the same technique as it is done in atomic theme
> Add discharging character in brainy theme

- themes/powerline/powerline.base.bash
change `${HOSTNAME}` to `${SHORT_HOSTNAME:=$HOSTNAME}`
> use $SHORT_HOSTNAME if set for powerline theme

- themes/base.theme.bash
> Revert "Update base.theme.bash with RUBY interpreter version check"

- plugins/available/gif.plugin.bash
Also support for filenames with spaces, and localized variables.
> GIF plugin: Added FPS auto-detection

- aliases/available/git.aliases.bash
Sorry for adding duplicating alias. I overlooked it.
> Remove duplicating alias

- plugins/available/direnv.plugin.bash
> Add direnv plugin

- README.md
From now on it would be better that 2 hashes are used for heading and 4 hashes for sub-headings. Good uniform formatting brings tears of joy out of people like me
Also I've added an index
> Fomatted the README File

- themes/powerline/powerline.base.bash
Fix some regressions introduced in PR https://github.com/Bash-it/bash-it/pull/891.
> Fix some regressions in Powerline theme

- themes/clean/clean.theme.bash
Remove zsh stuff and fix coloring
> clean theme: Fix scm coloring

- completion/available/terraform.completion.bash
This PR will fix https://github.com/Bash-it/bash-it/issues/1127.
> Update Terraform Completion

- completion/available/docker-compose.completion.bash
- completion/available/docker-machine.completion.bash
- completion/available/docker.completion.bash
Updated docker bash completions with the version that was pulled from a recent version of the Docker for Mac application.  Supports more recent form of some docker commands.
> Updating docker completions

- completion/available/invoke.completion.bash
Here is a copy of bash completion file from [invoke repo](https://github.com/pyinvoke/invoke/blob/master/completion/bash)
> Add invoke (pyinvoke.org) completions

- plugins/available/alias-completion.plugin.bash
This makes the script compatible with other 'versions' of `mktemp`.
> Change template for temp file creation

- install.sh
Feel free to ignore this PR if you'd be comfortable supporting `insane defaults` as well.
> INSANE EDIT: Pick a less crazy word than "sane"

- plugins/available/nodenv.plugin.bash
Title says it all. Let me know if you need more.
> Add nodenv plugin

- aliases/available/npm.aliases.bash
Credits to our mighty Evan You (creator of Vue.js) @yyx990803
https://gist.github.com/yyx990803/6045243
> Added alias that only list top level modules

- plugins/available/alias-completion.plugin.bash
Fix for https://github.com/Bash-it/bash-it/issues/1030
> Fixed opening vim

- themes/powerline/powerline.base.bash
> fix wd_prompt multiline croping

- plugins/available/fzf.plugin.bash
> Renamed "fd" function to "fcd" to avoid clash with "fd" tool

- themes/elixr/elixr.theme.bash
A minimal theme without username/hostname prompts as many times the user is well aware of the logged in host/user name. Added some neat, bold display chars along with SVM information.
Screenshot without SCM
Screenshot with SCM
> New "elixr" theme

- plugins/available/powerline.plugin.bash
Initializes powerline per the official powerline documentation:
https://powerline.readthedocs.io/en/master/usage/shell-prompts.html#bash-prompt
> Add powerline initialization plugin

- plugins/available/jump.plugin.bash
Considering FASD has been deprecated, jump does the same thing but is
actively maintained!
https://github.com/gsamokovarov/jump
> Add plugin for 'jump'

- lib/helpers.bash
> Fix update reload

- themes/zork/zork.theme.bash
I love zork, but I use conda and got sick of not being able to see what environment was activated!
> zork theme: add support for conda

- completion/available/system.completion.bash
Fixes https://github.com/Bash-it/bash-it/issues/932
> Fixing Error when starting Terminal after installing Bash-IT

- completion/available/bundler.completion.bash
examples:
`bundle exec rsp` + TAB => `bundle exec rspec`
`bundle exec rspec --no` + TAB => `bundle exec rspec --no-color`
I am a newbie to `complete`, so any comments are welcome.
> further bundle exec completion

- completion/available/lerna.completion.bash
Add completions for Lerna : https://www.npmjs.com/package/lerna
> Lerna completions

- completion/available/knife.completion.bash
Add completions for Opscode Chef's knife command
> Add completions for Opscode Chef's knife command

- completion/available/crystal.completion.bash
Supports https://crystal-lang.org
> Add Crystal auto-completion on Mac

- CONTRIBUTING.md
@nwinkler any thoughts about this? Just ran into a situation where an older PR had been force-pushed too and my local copy was totally outta sync. I'd like to encourage folks to not do that.
> Tweak the language around force pushes

- bash_it.sh
- lib/helpers.bash
- scripts/reloader.bash
This supersedes #1277 from @caguettaz. It incorporates all of his changes, plus a few other tweaks that came out of that discussion.
> Bugfix - issue with sourced files (noted by @caguettaz)

- themes/essential/essential.theme.bash
A simple, console-compatible Bash-it theme.
* Reactive coloring for:
* Privileged and standard users.
* Local and remote hosts.
* Exit status for prompt strings 1 and 2.
* Console-compatible!
* No unicode "tofu" in console sessions.
* Matching alignment for prompt strings 1 and 2.
> New theme: essential

- aliases/available/msys2.aliases.bash
Ignore "Windows hidden files" on MSYS2 bash.
> add aliases in MSYS2

- completion/available/docker-compose.completion.bash
- completion/available/docker-machine.completion.bash
- completion/available/docker.completion.bash
This PR is to update the lastest bash completion from docker repos.
> Update bash completion for docker, docker-machine, docker-compose.

- completion/available/helm.completion.bash
Signed-off-by: Brian Phillips <bpphillips@gmail.com>
> Add support for helm completion

- completion/available/git.completion.bash
This pull request is raw content from bash completion in [git repo](http://github.com/git/git/blob/master/contrib/completion/git-completion.bash) version v2.21.0
> Update bash completion for git v2.21.0

- plugins/available/pack.plugin.bash
With CNB `pack` beta being release it is a good time to add completion support to bash-it to help people that are starting to use `pack`.
> Add new plugin : `pack`

- aliases/available/git.aliases.bash
add gstp alias for 'git stash pop'
> Add alias for git stash pop

- plugins/available/osx.plugin.bash
This pull request adds two functions in `osx.plugin.bash`
1. List all JVMs
2. Pick default system-wide JVMs.
Closing older pull request #1362 , due to violating Contributing guidelines.
Refer to open issue #1359
> Add plugin list jvms and pick default system-wide

- aliases/available/node.aliases.bash
Added the most frequently used commands used be nodejs developers
> added nodejs aliases

- themes/base.theme.bash
Please let me know if there's any clean up you need me to do.  I wanted to see if it's something that you'd even consider before I spent more time on it.  Thank you for an awesome framework. :)
> allow customizing the character before ahead and behind characters

- themes/base.theme.bash
- themes/powerline/powerline.base.bash
SVN prompt also when in subdirectories that don't contain .svn
Show correct SVN status for powerline
> Improved subversion support for powerline

- test/themes/base.theme.git.bats
I'm not sure if there's a better way of fixing these tests, but if there are, then please let me know. 😀
> fix broken tests

- plugins/available/node.plugin.bash
> Ensure node paths are appended to existing $PATH

- lib/helpers.bash
- plugins/available/proxy.plugin.bash
> Make sed replacements work for both BSD and GNU sed

- themes/agnoster/agnoster.theme.bash
Initial commit of agnoster theme.
Credit: Isaac "Agnoster" Wolkerstorfer https://github.com/agnoster - original creator
Credit: Kenny Root https://gist.github.com/kruton/8345450 converted from 
zsh to bash
Credit: Toan Nguyen https://github.com/nntoan published in 
ohmybash/oh-my-bash (https://github.com/ohmybash/oh-my-bash)
Credit: https://github.com/speedenator patch for kruton's work and maintainance.
Credit: Hanish K H Updated & fixed on oct-05-2017
> themes/agnoster : Port from oh-my-bash

- README.md
- test/themes/base.theme.git.bats
- themes/base.theme.bash
If there's a better way of handling the test setup, then please let me know. 😀
> Toggle able commit count

- themes/newin/newin.theme.bash
Add a new theme named newin :)
> Add a new theme named newin :)

- aliases/available/git.aliases.bash
I often use this command when i use gerrit.
> add alias gcamd for `git commit --amend`

- plugins/available/man.plugin.bash
Now users can colorize man pages for better readability
> added man colors plugin

- completion/available/bundler.completion.bash
The latest update for Bundler completion from:
https://github.com/mernen/completion-ruby/blob/master/completion-bundle
> Update bundler completion from @mernen

- themes/zork/zork.theme.bash
It looks like ramses, mairan, and agnoster might have the same problems.
> Make zork theme not choke on strange characters

- themes/agnoster/agnoster.theme.bash
- themes/mairan/mairan.theme.bash
- themes/ramses/ramses.theme.bash
Double-check agnoster, I'm not 100% sure what I did is perfect.
> fix ramses, mairan, and agnoster shell quoting with virtual env

- themes/radek/README.md
- themes/radek/radek.theme.bash
Colorful theme for Python developers with no external
requirements.
> New theme for Python developers

- plugins/available/alias-completion.plugin.bash
This is a patch for fixing the issue originally reported in #1497, for which the patch was provided in PR #1503. That PR provided only a tentative fix for a single completion function known to have the issue.
This PR extends the solution by following the specification provided by the Bash completion function, i.e., the completion function always get the (full) command name ($1), the word being completed ($2), and the word preceding the word being completed ($3). The only tricky thing is that $3 needs to be obtained from the unaliased form of the command when $3 is an alias.
The suggestion and discussion are found in [this commit comment](https://github.com/Bash-it/bash-it/commit/9e92ef342f9673559e78220b14cd535aa631f4c7#commitcomment-37526899).
> Pass all the expected arguments to the completion function

- themes/barbuk/README.md
- themes/barbuk/barbuk.theme.bash
Simple theme with clean git prompt with github/gitlab/bitbucket icons. 
Good for light and dark theme user.
> Add theme barbuk

- themes/base.theme.bash
- themes/envy/envy.theme.bash
Envy theme is a good theme for me.
Now I wanna add python virtual env display for it.
> envy theme add python virtual_env display support.

- aliases/available/kubectl.aliases.bash
Provides a quick bash prompt in the k8s cluster using https://hub.docker.com/r/nicolaka/netshoot
> netshoot alias for k8s

- themes/barbuk/README.md
- themes/barbuk/barbuk.theme.bash
> Font usage for theme barbuk and git glyphs customization

- themes/atomic/atomic.theme.bash
Per discussion and changes made in #1535, applying simplified sudo check to `atomic` theme.
Tested locally.
-DF
---
CC: @lfelipe1501 , @buhl
> theme/atomic: Update sudo check method

- themes/brainy/brainy.theme.bash
Per discussion and changes made in #1535, applying simplified sudo check to `brainy` theme.
Tested locally.
-DF
---
CC: @MunifTanjim , @lfelipe1501 , @buhl
> theme/brainy: Update sudo check method

- completion/available/ng.completion.bash
See #1542, #1543
Thanks to @tbhaxor for the original fix.
> Added a check for the ng command in ng completion

- themes/barbuk/README.md
- themes/barbuk/barbuk.theme.bash
Following #1538 discussion, the custom theme variable naming has been updated.
> Theme barbuk: update custom variable naming

- plugins/available/sudo.plugin.bash
Hi Nils,
This plugin toggles sudo at the beginning of the current command or the previous when you hit the escape key twice.
> Added a sudo plugin

- .travis.yml
This is a preparation to further steps and can be merged separately.
> Refactor travis build matrix to `jobs`

- completion/available/oc.completion.bash
- completion/available/openshift.completion.bash
Updated openshift completion to use _command_exists removed duplicate oc completion
> Removed duplicate & updated openshift completion

- aliases/available/bash-it.aliases.bash
- aliases/available/general.aliases.bash
Also fixed a ShellCheck warning.
See #1560 for more details.
> Reworded the text for the general/bash-it alias loading

- test/fixtures/svn/broken/svn
- test/fixtures/svn/working/svn
- test/themes/base.theme.svn.bats
Unit tests for #1612, #1613.
Want to take a look, @arturmartins, @davesteinberg?
> Added test case for base theme SVN functionality

- test/fixtures/svn/working/svn
Based on @arturmartins comment in #1615 - thanks!
> Fixed comparison for SVN info parameter

- DEVELOPMENT.md
- README.md
- completion/available/bash-it.completion.bash
- lib/appearance.bash
- lib/helpers.bash
- lib/log.bash
- test/completion/bash-it.completion.bats
- test/lib/log.bats
Resolves #1501
Lemme know what do you think about my implementation :smile:
Please note that currently there are no logs at all, we can try to start add logs one by one after this is merged :)
> Bash it doctor command + log functions

- bash_it.sh
Looks like I missed this during my review, @NoahGorny
> Added missing colon and space while loading custom files

- completion/available/ssh.completion.bash
Add completion for sftp command.
> completion/ssh: support sftp command

- plugins/available/fzf.plugin.bash
I have this cleanup that's been lingering on one of my workstations. I probably copied my config to a new host and got an error about no `fzf` and wrote this. Just re-tested locally in linux and it seems fine. Let me know what you think.
> Minor cleanups to fzf plugin

- plugins/available/alias-completion.plugin.bash
- test/plugins/alias-completion.plugin.bats
Resolves #1625
I think this solution is working well
> plugins: Fix quotes around prec_word agruments

- completion/available/terraform.completion.bash
> Use terraform to complete itself

- test/lib/search.bats
> Adding log library to search tests

- test/plugins/alias-completion.plugin.bats
> Fixed test execution

- aliases/available/git.aliases.bash
> Add new git push/pull/log aliases

- plugins/available/gif.plugin.bash
Seems to break on MacOS otherwise.
> Correct the commandline for gifski on MacOS

- aliases/available/terraform.aliases.bash
- aliases/available/terragrunt.aliases.bash
Add Terraform and Terragrunt aliases (IaaC software)
> Add Terraform and Terragrunt aliases

- completion/available/kind.completion.bash
Add completion for project **Kind** (local Kubernetes cluster).
> Add Kind support

- completion/available/github-cli.completion.bash
- lib/helpers.bash
- test/lib/helpers.bats
gh was also used as an git alias, and caused _command_exists to not fail as expected
Closes #1684
> Add _binary_exists and use in github-cli completion

- .github/workflows/ci.yml
- Add github action to replace travis
Tested on my fork, works great (could not get caching to work.. not a must anyway)
> migrate to github actions

- .github/no-response.yml
Another nice github feature, will help us close stale issues﻿
> github: Add no-response bot

- aliases/available/git.aliases.bash
- Add "gsr" for "git svn rebase"
- Add "gsd" for "git svn dcommit"
> Add aliases for GIT-SVN (rebase and dcommit)

- docs/index.rst
- docs/themes-list/index.rst
- docs/themes.rst
- docs/troubleshooting.rst
Another important step after #1688
> Migrate wiki docs to rtd format

- docs/README.md
> readme: Change join chat to IRC from gitter

- install.sh
> Disable auto-reload in install.sh

- docs/contributing.rst
- docs/help_screens.rst
- docs/misc.rst
- docs/proxy_support.rst
- docs: Restructure sentence about adding screenshots
- docs: misc: Move help_screens and proxy_support into seperate pages
Closes #1699
> docs more improvements

- scripts/reloader.bash
Please refer to commit messages.
Please test this works as you desire, _before_ merging.
> Optimizations to reloader.bash

- docs/contributing.rst
Improve the contributing document with updated details, and remove irrelevant information
This PR includes:
* Drop mention of travis in contributing.rst, mention github actions instead
* Add section about the command builtin (as discussed in https://github.com/Bash-it/bash-it/pull/1757#issuecomment-752220605)
* Drop irrelevant information in the issue section, as we have templates that police this better.
Prompted by my discussion with @davidpfarrell, I thought that the document need some refreshing
I built the docs locally and saw that they look good
> Update contributing document

- clean_files.txt
- plugins/available/basher.plugin.bash
This PR seeks to add support for [Basher](https://github.com/basherpm/basher/).
We don't want to handle installing stuff, and I want a package manager for my bash stuffs (e.g. *env language tools).
Note: to implement full support for Basher, we'll need adjust the load priority of tools it would commonly manage, but after attempting a large PR to address that, I decided that breaking all the changes into separate PRs was a better plan.
Locally, and it follows established conventions
> add plugin for basher

- clean_files.txt
- completion/available/sdkman.completion.bash
Add sdkman bash completion to the list of clean files, fix the issues reported by shellcheck, and reformat the code with shfmt.
Follow up to Bash-it/bash-it#1763 as suggested by @NoahGorny.
Manually, the same way Bash-it/bash-it#1763 was tested before. See bash version there.
> Add sdkman bash completion to the list of clean files

- clean_files.txt
- completion/available/brew.completion.bash
Cleanup brew completion as part of #1782
> formatted brew completion

- clean_files.txt
- completion/available/awless.completion.bash
Cleanup awless completion as part of #1782
> formatted awless completion and used helper function

- clean_files.txt
- completion/available/conda.completion.bash
Cleanup conda completion as part of #1782
> formatted conda completion and used helper function

- clean_files.txt
- completion/available/consul.completion.bash
Cleanup consul completion as part of #1782
> formatted consul completion and used helper function

- clean_files.txt
- completion/available/docker.completion.bash
Cleanup docker completion as part of #1782
After #1801
> completion: Lint docker completion and add about-completion

- clean_files.txt
- completion/available/helm.completion.bash
Cleanup helm completion as part of #1782
> formatted helm completion and used helper function

- clean_files.txt
- completion/available/gem.completion.bash
Cleanup gem completion as part of #1782
> formatted gem completion

- clean_files.txt
- completion/available/jungle.completion.bash
Cleanup jungle completion as part of #1782
> formatted jungle completion and used helper function

- clean_files.txt
- completion/available/kontena.completion.bash
Cleanup kontena completion as part of #1782
> formatted kontena completion and used helper function

- clean_files.txt
- completion/available/kubectl.completion.bash
Cleanup kubectl completion as part of #1782
> formatted kubectl completion and used helper function

- clean_files.txt
- completion/available/minikube.completion.bash
Cleanup minikube completion as part of #1782
> formatted minikube completion and used helper function

- clean_files.txt
- completion/available/npm.completion.bash
Cleanup npm completion as part of #1782
> formatted npm completion and used helper function

- clean_files.txt
- completion/available/lerna.completion.bash
Cleanup lerna completion as part of #1782
Untested
> formatted lerna completion and used helper function

- clean_files.txt
- completion/available/go.completion.bash
Complements #1824 to ensure that go completion works well when using goenv.
locally and manually
> ensure go completion works well with goenv

- aliases/available/git.aliases.bash
> Added alias for git rebase

- aliases/available/npm.aliases.bash
Add a new npm alias for `npm test`
`alias nt='npm test'`
because I'm _that_ lazy & don't want to type `npm t` 😊
Tested locally on macos
n/a
> add npm alias nt="npm test"

- docs/README.md
- docs/index.rst
- docs: Add license notice to readme
- docs: Add newline in readme and index.rst
I felt like the readme could use a notice like this, also a newline was missing
> add license to docs

- clean_files.txt
- docs/themes-list/easy.rst
- docs/themes-list/index.rst
- themes/easy/easy.theme.bash
> easy theme added

- install.sh
Dont quote number vars, to support older bash versions
Closes #1861
Locally, with a docker image of an older bash and my machine
> install: Dont quote number vars, to support older bash versions

- clean_files.txt
- completion/available/ngrok.completion.bash
> Added completion for ngrok tool

- LICENSE
- docs/README.md
Add the logo of Bash-it to the readme- makes the readme more pretty and engaging!
> docs: Add logo of bash-it to readme

- docs/commands/reload.rst
Add docs about bash-it restart
Closes #1868
Built the docs locally
> docs: Add a section about bash-it restart

- clean_files.txt
- themes/candy/candy.theme.bash
Added to `clean_files.txt`, ran `./lint_clean_files.sh` and fixed the errors﻿
> Clean candy theme

- clean_files.txt
- completion/available/wpscan.completion.bash
> FIxed wpscan completion linting

- lib/helpers.bash
> Replace reload with restart bash it after upgrade

- lib/helpers.bash
Closes #1889 
Manually on docker container
> Abort upgrade if unsaved changes found in bashit directory

- aliases/available/git.aliases.bash
Modify git aliases to check out the `main` branch instead of `master` if the former is present.
To reflect the growing adoption of `main` as the default branch, in place of `master`. 
Currently aliases that rely on `git checkout master` don't work in repos that have adopted this new pattern. With changes in this PR, the modified aliases will behave as follows
- If a `main` branch is present in the repo, check out the `main` branch
- If `master` is present, check out `master`
- If both branches are present, priority is given to `main`
I did the following
1. Create two repos, one using `master` as the default branch and another using `main`
2. Create a new branch `dev` in both repos, and check out this branch
3. Run `gcom` and confirm the expected default branch has been checked out in both …
> Have git check out main branch if present

- .github/workflows/ci.yml
Reverts #1767 
Closes #1768
I think it is about time
> Reinstate macOS 11 job

- plugins/available/pyenv.plugin.bash
This commit cleans up the pyenv plugin to follow the newer conventions of the
other *env plugins, as well as addresses the changes made to pyenv for PATH
munging.
Fixes #1882
locally
> clean up pyenv plugin

- aliases/available/git.aliases.bash
add a git command for faster rebases 
add a new alias
I rebase alot and this saves considerable amount of time
ran this in my local bash shell and it worked
> feat(git): make auto squashing non-interactive

- clean_files.txt
- plugins/available/gif.plugin.bash
Use `type -p` instead of `which`, and run `shfmt`.
> plugin/GIF: use `type -p` and lint

- themes/atomic/atomic.theme.bash
Use `[[` instead of `[`, set some local variables
> theme/atomic: lint/cleanup

- clean_files.txt
- themes/norbu/norbu.theme.bash
Lint and simplify `prompt_command()` slightly.
Simplicity, clarity, and #1696.
`bash-it preview norbu`
> theme/norbu: `shellcheck` && `shfmt`

- .github/workflows/ci.yml
This should (hopefully) speed up tests!
The OSX runners are *so* _dang_ **_slow_**...
> CI: install `parallel` on OSX

- clean_files.txt
- plugins/available/battery.plugin.bash
Lint `plugins/battery`
Who needs testing?
> plugin/battery: `shellcheck`

- plugins/available/alias-completion.plugin.bash
Fix a typo in the plugin stub...
Oops.
This time, I have manually verified both the path and that the plugin stub loads and runs as intended.
> completion/aliases: typo

- aliases/available/general.aliases.bash
Fixes #2056 and I also feel having too much aliases will cause confusion and break others in future
> Remove redundant aliases for clear screen

- completion/available/aliases.completion.bash
- Slightly shorten completion discovery.
- Replace `sed` with `$BASH_REMATCH`.
- Add redirection operators (`<`/`>`) to skipped characters.
- `local` `line`.
- Fixes #1995.
- Reduces `fork()`s.
I was able to reproduce errors from #1995  and this eliminates what I could reproduce. I think some more error checking can be done regarding replacing an existing completion, e.g. `alias mv='mv -i`' maybe shouldn't be replaced.
> completion/aliases: redirection, quote, temp file

- themes/pure/pure.theme.bash
Minor changes for hopefully slightly better readability and reliability.
> theme/pure: cleanup

- completion/available/knife.completion.bash
no idea when this one was broken, I was using a local pristine copy so I didn't notice...
> knife completion was broken, fixing

- .github/workflows/ci.yml
Use bashcov and upload coverage to codecov
Closes #1053 
Not tested as of yet
> ci: Add bashcov codecov report

- .github/workflows/ci.yml
> Revert "ci: Add bashcov codecov report"

- clean_files.txt
- completion/available/awscli.completion.bash
Adds the completion/available/awscli.completion.bash to clean_files.txt and format it via shfmt
> Clean awscli completion

- docs/conf.py
- docs/requirements.txt
This pull request fixed the sphinx-build [here](https://github.com/Bash-it/bash-it/runs/6327809837?check_suite_focus=true#step:5:21)
> Upgrade the sphinx version

- clean_files.txt
- completion/available/flutter.completion.bash
Formats the file with shfmt
Clean bashit from #1696
> Clean flutter completions

- themes/parrot/parrot.theme.bash
This branch will fix the parrot theme ps1 escape sequences in `parse_git_branch` which occur some text overwritting in alacritty terminal. (i had this issue in alacritty terminal but probably happens in other terminal).
I remplaced the escape sequences with correct ones.
As the ps1 seems to not be correctly ended, the termianl emulator lines was never ended to which occur a text overwriting
[example](https://camo.githubusercontent.com/b9885e445573b8497032300d25b37663a7b75db459531b5cdff32a960be31022/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f5a6969414a5a38344630636951446777646c2f67697068792e6769663f6369643d373930623736313133353430363533353966323436636266313133343931623034316531336264373739656562653935267269643d67697068792e676966)
> fix(theme): use correct escape sequence to avoid weird text overwriting

- completion/available/brew.completion.bash
Fixed the false-positive variable not defined (SC1091) in brew.completion.bash
Locally on Linux
> Suppress SC1091 in brew completions

- plugins/available/gif.plugin.bash
- themes/oh-my-posh/oh-my-posh.theme.bash
> Fix commandline options for the current versions of gifski, gifsicle and oh-my-posh

- clean_files.txt
- themes/clean/clean.theme.bash
Followed instructions in #1696 to cleanup `clean.theme.bash`
Addresses #1696
Ran `./lint_clean_files.sh`
> Clean `clean.theme.bash`

- .github/workflows/ci.yml
- test/plugins/battery.plugin.bats
update the CI definitions to include newer versions of macos.
macos-11 machines seem to be no longer relevant nor available at github.
> Check newer macos, the old versions are getting irrelevant

- plugins/available/z_autoenv.plugin.bash
After merge I saw I managed to break this plugin. never fix code you don't fully understand :(
> redo the z_env cleanup because I broke it badly

- clean_files.txt
- themes/cupcake/cupcake.theme.bash
- themes/doubletime_multiline/doubletime_multiline.theme.bash
- themes/doubletime_multiline_pyonly/doubletime_multiline_pyonly.theme.bash
- themes/dulcie/dulcie.theme.bash
- themes/duru/duru.theme.bash
Followed instructions in #1696 to cleanup these files.
Addresses #1696
Ran `./lint_clean_files.sh` successfully.
> Clean doubletime variants, dulcie, and duru theme files

- clean_files.txt
- completion/available/aliases.completion.bash
- themes/powerline-naked/powerline-naked.base.bash
- themes/robbyrussell/robbyrussell.theme.bash
small fixes I missed in other PRs.
> important  catches by @akinomyoga
