Bash-it/bash-it

plugins/available/base.plugin.bash
This is in reference to Issue: #399
1. Renamed pass function to passgen.
2. If the pass command (password store) is not found or BASH_IT_LEGACY_PASS is true then define alias pass.
=> Rename pass function to passgen to avoid conflict with pass (password store) utility.

README.md
This is in reference to Issue: #399. The addition explains the renaming of the `pass` function to `passgen` and `BASH_IT_LEGACY_PASS` usage.
=> Added BASH_IT_LEGACY_PASS usage notes to README.

bash_it.sh
Using the same logic as in the install script. When #396 was added, the `reload` alias was not updated accordingly.
=> Fixed reload alias.

README.md, install.sh
The install script now allows to specify one of the following options:
* `--all`
* `--none`
Both result in any questions being skipped. This is convenient when running the install script from a script, or a provisioning tool like Ansible.
=> Added option for skipping questions in installer.

README.md, template/bash_profile.template.bash
this adds `completion/custom.completion.bash` to the customization list for consistency with other list items
=> minor fix in Readme to add completion/custom.completion.bash to the customization list

plugins/available/textmate.plugin.bash, template/bash_profile.template.bash
often `which mate` will be different from hardcoded `/usr/bin/mate`
```
uname -a
Darwin ipovalmac.local 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
```
```
which mate
/usr/local/bin/mate
```
=> fix textmate path on some platforms

plugins/available/dirs.plugin.bash
prevent usage of functions `S` and `R` without a single argument
before:
```
S
sed: first RE may not be empty
-bash: =/Users/ipoval/.bash_it: No such file or directory
R
sed: first RE may not be empty
```
after:
```
S function requires 1 argument
```
=> add argument presence check for functions in dirs plugin to bad usage

plugins/available/ruby.plugin.bash, template/bash_profile.template.bash
This path `~/.gem/ruby/1.8/bin` used to work only for version of ruby 1.8, which is EOL, together with 1.9; 
make the path work for many versions of ruby including the latest one:
reference: http://guides.rubygems.org/faqs/#user-install
=> fix path to commands installed by gem install --user-install

install.sh, plugins/available/base.plugin.bash, test/plugins/base.plugin.bats
[-] preserve attributes of $CONFIG_FILE on backup (attributes may incl. modification time, access time, file flags, ...)
[-] make buf() to respect file attributes on file backup
=> Backup with cp dash a

themes/powerline-multiline/powerline-multiline.theme.bash
If the user is currently in a valid sudo session (sudo currently does not require a password), then the last part of the left prompt will use a different color (orange). This gives an indication to the user that sudo commands will not require a password at the moment. One example for this might be that the user is reminded to run a `sudo -k` to terminate the current sudo session before stepping away from the screen.
This is what it looks like:
@tswicegood @edubxb @ifosch - would like to get your opinion on that. Let me know what you think.
=> Added sudo indicator to the Powerline-Multiline Theme

aliases/available/homebrew.aliases.bash
Homebrew currently gives a warning about how this flag will be required in the future, as merged in Homebrew/homebrew#38572
=> Homebrew upgrade command wants --all flag

plugins/available/battery.plugin.bash
The previous version was printing an error when the battery percentage was in the single digits, e.g. "7.04%". The code cuts returns the first two digits, which in the case of "7.04%" are "7.". Any code that tries to use that, e.g. the powerline-multiline theme will fail with an error.
This change corrects that by zero padding single digits, i.e. "07.04%" instead of "7.04%".
=> Fixed conversion when the battery percentage is in the single digits.

bash_it.sh
This seems to fix the unicode line wrap issue mentioned in #409
Nota bene, This fixed the problem for me on Fedora 21 and Ubuntu 15.04
Needs to be tested on other systems
=> Fix unicode line wrap problem (issue #409)

plugins/available/aws.plugin.bash
This plugin has a helper function, awskeys, that simplifies to export profile keys as environment variables, useful when some programs that interact with the AWS API only work with these variables.
=> Added AWS plugin

aliases/available/vagrant.aliases.bash
A single line addition to the vagrant aliases file... a Vagrant up alias that logs output to vagrant.log file.
=> Add vagrant up log alias

aliases/available/docker.aliases.bash
I get an error at startup from the docker aliases file. Enclosed change fixes this so there is no error on startup.
=> Fix startup error with enabled docker alias file

aliases/available/docker.aliases.bash
The docker images subcommand was returning all columns due to unescaped
'$3' in awk filter.  This was throwing a lot of errors as rmi tried to
remove non-existent images.
In any case docker images has a flag to filter and only show dangling
image IDs which makes this simpler.
=> Fix dkrmui alias (delete untagged images)

plugins/available/base.plugin.bash
Some platforms (e.g. Arch Linux) don't have `ifconfig` by default. They use `ip` instead.
=> Fix ips command for platforms without ifconfig

plugins/available/history.plugin.bash
After running a dist upgrade on one of my Ubuntu 14.04 test workstations I started receiving errors after a graphical login. This should also fix remote ssh login problems as seen in http://superuser.com/questions/892658/remote-ssh-commands-bash-bind-warning-line-editing-not-enabled
=> Check for PTY before attempting to use bind

completion/available/npm.completion.bash
The _npm_completion function was generated with the `npm completion` command (npm version 2.11.0)
=> npm autocompletion

themes/base.theme.bash, themes/bobby-python/bobby-python.theme.bash
Added prompt functions for the version of the Python interpreter and the name of the current Conda package manager environment (http://conda.pydata.org similar to rbenv) to base.theme.bash.
The final python_version_prompt function to be used in themes includes these and the Virtualenv name to cover both Conda and Virtualenv usage.
=> Add Python version and Conda environment prompt functions.

aliases/available/docker.aliases.bash
Due to use of double-quotes ``docker ps`` was executed when the aliases
were loaded and as a consequence ``dklcip`` would always show IP of a
container that was last then instead of at runtime.
This changes the alias to use single quotes which fixes that.
It also changes the alias to use docker's ``--format`` option so
there's no need of parsing the output using grep and cut.
=> Fix dklcip alias

lib/history.bash
- there is no point to call `export HISTCONTROL="ignoredups"` since it gets over-written by the next statement; so removed it and mentioned in comment
- small cleanup of the comments
=> [history-bash] remote unused export call; cleanup history.bash file

plugins/available/git-subrepo.plugin.bash
For [git-subrepo](https://github.com/ingydotnet/git-subrepo), an excellent replacement for git-submodule and git-subtree.
=> Add git-subrepo plugin

plugins/available/osx.plugin.bash
This will allow to open new terminal tabs in the same directory as the
current terminal. Uses the fact that plugins are loaded after the
selected theme. Themes often manipulate the $PROMPT_COMMAND variable.
Implementation inspired by the pathmunge function.
=> Added check for OS X update_terminal_cwd

themes/base.theme.bash
The current check of `git symbolic-ref HEAD` does not detect git
repositories in the 'detached HEAD' state. This is the state a
repository is in if HEAD is not pointing to a valid branch or tag (e.g.
you are in a recently-initiated submodule).
=> Show git prompt when in a detached HEAD state

plugins/available/xterm.plugin.bash
Use '\033' instead of '\e' as escape character in set_xterm_title.
=> Fix for issue #108 that restores xterm plugin functionality on OS X.

plugins/available/less-pretty-cat.plugin.bash
When pygmentize is not installed, the functions less/cat are not
defined, the native commands will be used instead. Also removed the
error message that was shown when the command was not found.
Using `command -v` instead of `which` to check for the existence of the
executable - this works better as it does not print an error message if
the executable is not found.
=> Fixed error handling in less-pretty-cat plugin

plugins/available/boot2docker.bash, plugins/available/docker-machine.bash, plugins/available/docker.plugin.bash
Moved boot2docker functionality to its own file. Also added a docker-machine plugin, which sets the same variables for docker-machine.
This will allow an easier transition from boot2docker to docker-machine.
=> Docker plugin --> boot2docker, docker-machine plugins

plugins/available/boot2docker.bash, plugins/available/docker.plugin.bash
Using the recommended enter approach (exec) instead of the previously used nsenter.
=> Moved docker-enter function to docker plugin

themes/dulcie/dulcie.theme.bash
I've add the following upgrades in to a Dulcie theme:
- Colorize prompt
- Support for multiline prompt
- Set tab title (OSC 0) and keep the current directory (OSC 7)
=> Dulcie theme upgrades

themes/powerline-multiline/powerline-multiline.theme.bash
For battery percentages of 08 and 09 percent, the `-le` would fail with
an error ("value too great for base"), since the numbers with leading
zeros are treated as octal numbers when using double brackets.
The solution is to force base 10 for the numbers. More details here:
http://stackoverflow.com/a/24777667/1228454
=> Fixed battery conversion

README.md, uninstall.sh
Added an uninstall script and instructions. The script does the following:
* Restores the previous Bash profile (`~/.bash_profile.bak` or `~/.bashrc.bak`).
* If the backup file was not found, it simply renames the current profile. It also prints out a message in this case.
* Prints a goodbye message and next steps: Remove the `$BASH_IT` folder, open a new shell
=> Uninstall script and instructions

themes/colors.theme.bash
When using `set -x` with a `$PS4` variable which calls a external
command (e.g. `PS4='+ $(true)'`) the color functions end in a infite
loop.
The solution is `shift` the arguments unconditionally in the color
funtions.
This fixes #546
=> Fix #546: infinite loop when $PS4 calls external command

plugins/available/osx-timemachine.plugin.bash
A set of functions to simplify listing OS X Time Machine backups, and
deleting old ones. Pulled from various script solutions found on Stack
Overflow, adapted to the Bash-it framework.
The functions allow to show which backups can be found on the connected
Time Machine volume. The 'delete' function allows to safely remove all
backups except for the latest one - this can be used to free up space on
the Time Machine volume. The 'delete' function uses functionality of the
OS to safely remove the old backups, no information is lost.
The 'delete' function will only ask for the password once, then keep the credentials.
Source: http://stackoverflow.com/a/30547074/1228454
=> Added plugin for OS X Time Machine

plugins/available/base.plugin.bash, plugins/available/osx.plugin.bash
Some functions were specific to OS X, but were defined in the `base` plugin. I have moved them to the `osx` plugin:
* pman
* pcurl
* pri
As for `pcurl`, the `osx` plugin already had an existing `prevcurl` function, which was doing the same thing. I've aliased `pcurl` to simply call `prevcurl` to avoid breaking existing installations.
As far as I know the `open -fa $PREVIEW` thing only works on OS X, which means that these functions have only worked on OS X anyway.
=> Moved some functions

themes/powerline-multiline/powerline-multiline.theme.bash, themes/powerline/powerline.theme.bash
Sometimes I find myself unable to remember if I am currently in bash coming from vim (via `:sh`), usually when I have multiple terminals open.
I patched the `powerline` theme to indicate to me if I stepped in from `vim` or not:
If there is an interest in having this throughout all themes and having this as a feature, I am willing to do the work.
=> Indicator if running bash in vim

plugins/available/alias-completion.bash
This plugin adds completion to aliases, just as with their regular
commands. Example:
* Completion works for `git checkout <TAB>`, which shows available
branches.
* You have an alias like `alias gco="git checkout"`
* The plugin adds support for `gco <TAB>`, which will also show the
available branches.
Reference: http://superuser.com/a/437508/119764
=> Added alias-completion plugin

README.md, themes/base.theme.bash
- Improve ref detection
- Add the option to show git branch remote tracking info in git prompt
- Git prompt now indicates when remote tracked branch is "gone"
- New env var (SCM_GIT_DETACHED) that indicates when HEAD is detached
- New env vars available for themes (SCM_THEME_BRANCH_TRACK_PREFIX,
- SCM_THEME_BRANCH_GONE_PREFIX, SCM_GIT_DETACHED_CHAR)
See: https://github.com/Bash-it/bash-it/issues/413#issuecomment-111072247
=> Improvements in git prompt

themes/simple/simple.theme.bash
PS1 definition via PROMPT variable produces an invalid prompt
=> Update simple theme

plugins/available/docker-machine.plugin.bash
The `~` caused docker commands to error with the following:
```
$ docker images
Could not read CA certificate "~/.docker/machine/machines/dev/ca.pem"
```
Switching to $HOME fixes the issue
=> Replace `~` with $HOME in docker-machine plugin

aliases/available/emacs.aliases.bash
As requested, here's a pull request fixing issue #578
=> Addresses duplicate emacs alias use of 'et'. See Issue #578

aliases/available/git.aliases.bash
Adds `gf` as an alias for fetching all git remotes and pruning obsolete remote branches.
=> Add `gf` alias for fetching all and pruning

plugins/available/docker-machine.plugin.bash
The docker-machine IP can change if the machine is recreated. `docker-machine env dev` sources the current machine settings.
Signed-off-by: Frank Kotsianas <fkotsian@pivotal.io>
=> Source docker-machine environment variables rather than hardcoding

plugins/available/explain.plugin.bash
This PR adds an `explain()` function which allows explaining other commands via mankier.com man page data.
Reference: [Explaining Shell Commands in the Shell][1]
[1]: https://www.mankier.com/blog/explaining-shell-commands-in-the-shell.html?hn=1
=> Adding mankier.com explain() function to explain other commands

plugins/available/less-pretty-cat.plugin.bash
Was not working correctly with file extensions unknown to pygmentize. Added the -g option to pygmentize command.
The issue fixed by this commit can be reproduced with the follwing command (considering the master branch):
```bash
echo "This is a test" > test.toto | less test.toto
``` 
which returns
```
Error: no lexer for filename 'test.toto' found
```
Also I removed the double quotes around ```$*``` (maybe I should have done it in another PR) because this does not allow to pass additional options to pygmentize (at least on OS X) as claimed in commit e143d4f6969eb1774a0d83cf378c171967d0487f (unless I am missing something). For instance:
```bash
less -l matlab hessian.m
```
does not work because of the double quotes. If you want I can split this PR in two parts.
=> Fixed pygmentize in less.

lib/appearance.bash
This will look for a theme in $BASH_IT/custom/themes before $BASH_IT/themes.
=> Allow custom themes to be in $BASH_IT/custom/themes

plugins/available/docker-machine.plugin.bash
Add the variable BASH_IT_DOCKER_MACHINE to set a name other than 'dev' as
Virtual Machine name.
=> Add Support for different docker-machine VM names

themes/base.theme.bash
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html
=> Add support for AWS Tools Profile.

completion/available/jboss7.completion.bash
JBoss 7 (EAP 6 is still used in most environments. It also works with WildFly, might need to rename it later)
=> Added jboss 7 completion

themes/zork/zork.theme.bash
Add features to zork theme.  Show activated python virtualenv and chromebook crouton debian chroot, if and when either apply.
=> Show crouton debian_chroot and python virtualenv (if applicable) (feature)

completion/available/system.completion.bash, install.sh
In addition to the regular /etc/bash_completion, the one from Homebrew is loaded when running on OS X, and when Homebrew is installed.
Also added the system completion to the default install options, since this is a feature that's requested frequently.
=> Loading Homebrew Bash Completion if installed

install.sh
As per Issue #621 I added an option to let the user to keep his .bashrc and just append the general template of bashrc at the end. Also, in the normal flow I simply add the cp -aL options as suggested by @naught101 to let the installation process follow symlink in case .bashrc is one of them. First pull request for me here so, I hope it's all ok. In other case, please be patient :)
=>  Add follow sym link and option to append template to existing .bashrc

aliases/available/ag.aliases.bash
`ag` (["the silver searcher"][1]) is a fast alternative to `grep` or [`ack`][2] for source code repo searching.  This PR adds a default alias with some sane defaults similar to those used for `ack`.
[1]: http://geoff.greer.fm/ag/
[2]: http://beyondgrep.com/
=> Adding alias for sane default options to "ag" ("the silver searcher")

themes/base.theme.bash
The git prompt causes bash to use 100% CPU for large amounts of time when dealing with long `git status` outputs.
Repro:
- clone a repo with a large number of files (e.g. the linux kernel)
- delete all files in the working tree
cd'ing in the directory should now be painfully slow for users of the git prompt.
The issue is noticeable starting from ~100 modified/deleted files on my machine.
It becomes unmanageable for large working tree changes - after removing 100k+ files from a working tree for instance, bash used 100% CPU on one core for a few hours before I killed it.
----
The idea is to use awk to pre-process the output of `git status`, condensing the needed information into a 4-line summary, rather than processing the raw output in multiple places as was done before.
I timed the …
=> [bugfix] Fixed performance issue with git prompt

themes/base.theme.bash
Running `rvm tools identifier` seems to be really slow. Using [`rvm-prompt`](https://rvm.io/workflow/prompt) greatly speeds up the evaluation of `$PROMPT_COMMAND`.
=> Speed up $PROMPT_COMMAND by using rvm-prompt

completion/available/sdkman.completion.bash
The version completion was broken caused by a renamed function from sdkman to determine local installed versions of a candidate and a variable that got removed.
=> fixed version completion for sdkman 3.3.2

completion/available/projects.completion.bash, plugins/available/projects.plugin.bash
Howdy! Found some time to cleanup the plugin I wrote a few months ago.
- added `pjo` alias for `pj open`
- cleaned up indentation to conform to editorconfig
- added menu for identical project names condition (e.g. /projects/foobar  &&  /work/projects/foobar)
- added more verbose error messages and handling
=> Projects Plugin cleanup

lib/history.bash
Set these before sourcing Bash-It in `.bashrc` or `.bash_profile` to override defaults.
If [unset or null][1], the original hard-coded defaults are still used.
[1]: http://stackoverflow.com/a/16753536/645491
=> Make all vars defined in lib/history.bash overridable

themes/powerline-multiline/powerline-multiline.theme.bash
- following existing patterns, clearing out RBENV prefix and suffix
- using existing function to read the prompt
=> Adding support for rbenv in addition to rvm to the powerline-multiline theme

README.md, themes/base.theme.bash
The reasoning is stated in the README diff below. 
I know several people at Pivotal are customizing their bash_it to include this, but i thought that adding an optional support for this "properly" would be valuable to a quite a few folks.
I chose to name the prefix and suffix with the generic `SCM` because I expect that users of other SCMSs may want to implement their own. At that point the `SCM_GIT_SHOW_CURRENT_USER` switch can also become a more generic `SCM_SHOW_CURRENT_USER`.
=> Adding support for git user & git pair in git prompt (off by default)

completion/available/bash-it.completion.bash, lib/helpers.bash
Tidying up search feature – now searching in constant time, by caching output of each of `bash-it show plugin|aliases|completions` instead of running it for each search term.
Also, ensuring there is no auto-completion after search, eg: `bash-it search[TAB]` stops and shows no options, as there are none – user is supposed to provide search terms there.
Thanks! Hopefully this is it! (LOL, famous last words :)
=> Faster search, and cleaner completion

plugins/available/battery.plugin.bash
Clean cases and remove spaces and % symbol in one awk command
Needs some testing but it seems to work ok. It will include 3 chars for full battery, besides that the output follows the same format as before.
=> Fix battery plugin

plugins/available/osx.plugin.bash
The update_terminal_cmd is interfering with the $? variable. Somehow it
is always 0.
```
caesium@Mac:~/Documents/projects/git/bash-it 0 >export PROMPT_COMMAND="update_terminal_cwd;set_prompt"
caesium@Mac:~/Documents/projects/git/bash-it 0 >false
caesium@Mac:~/Documents/projects/git/bash-it 0 >true
caesium@Mac:~/Documents/projects/git/bash-it 0 >export PROMPT_COMMAND="set_prompt;update_terminal_cwd"
caesium@Mac:~/Documents/projects/git/bash-it 0 >false
caesium@Mac:~/Documents/projects/git/bash-it 1 >true
caesium@Mac:~/Documents/projects/git/bash-it 0 >
```
After the fix it is working properly.
=> osx_terminal_exit_code_fix

plugins/available/fasd.plugin.bash
The flag `-s` don't works on Linux, this PR fix this.
=> Make #691 work on Linux

test/lib/helpers.bats, test/run
Creating this PR to benefit from the automatic CI integration and figure out why the tests were failing. 
* Re-enabling failing test on Travis
* Adding a much more full featured test for searching of ruby-related terms (passes locally).
* Adding concrete path to `bats` and `test` to avoid path-munging magic.
=> Trying to go back and figure out why tests were breaking on Travis

plugins/available/autojump.plugin.bash
See https://github.com/wting/autojump for more details.
Currently only supports the version installed through Homebrew on OS X.
Please feel free to provide a PR for supporting additional installation
options.
=> Added Autojump plugin

themes/iterate/iterate.theme.bash
This change allows for the capture of the expanded prompt (rather than the raw `PS1`) so that
it is easier to maintain context when changing directories.
Fix is based on the comments from [this stackoverflow](http://stackoverflow.com/a/24006864)
=> Display the prompt when changing directories

plugins/available/battery.plugin.bash, themes/powerline-multiline/powerline-multiline.theme.bash
Not sure about the logic for returning 1/0 from the function, though - will have to clarify.
@edubxb - You added the `ac_adapter_connected` function back then. What is the return value of this function? From the code, it looks like this:
* return 1 if the AC adapter is connected
* return 0 if the AC adapter is not connected
Is this correct? I found that in that case, the `[[ $(...)]]` condition in the theme does not seem to work. At least that's what I've seen on OS X.
The below fix makes it work on OS X, but I don't know whether it still works on Linux (or has ever worked)...
Let me know what you think.
=> Added AC indicator support on OS X

plugins/available/plenv.plugin.bash
Fails silently when plenv not found, only munges path if plenv path exists
=> Initial plenv plugin created.

themes/gallifrey/gallifrey.theme.bash
I love the gallifrey theme in oh-my-zsh, so I've made a similar-looking theme for bash-it 😄 
Doesn't have the RPS1 features of the oh-my-zsh one but is otherwise good enough for me!
This screenshot shows Gallifrey from oh-my-zsh on one of my machines, lonsdaelite, and my port on the 'nsa' machine. I changed the double chevron to a $ so I can tell at a glance whether I'm using bash or zsh. If you have this theme and are root you'll see a # instead of the $.
=> Rough port of oh-my-zsh's gallifrey theme

plugins/available/history.plugin.bash
This pull request resolves issue #726. A trailing semi-colon and space have also been removed since 'then' was already on another line.
=> Add history cite and about-plugin lines

completion/available/tmux.completion.bash
Downside: it requires version at least 2.1 of tmux.
Advantage: it contains actual list of commands. 
Please compare `${_tmux_cmds}` with  the output of `tmux list-commands` for the current version. 
See also difference https://github.com/przepompownia/tmux-bash-completion/commit/76f8d9d02cd78cca80a4214a39ea3920bb1c689f for older versions.
=> Replace static command list by generated.

bash_it.sh
- where we used to load lib/*.bash, skip loading lib/appearance.sh, otherwise it would be first due to alphabetical order
- load lib/appearance.sh after enabled plugins, etc
- this allows themes to assume that certain basics are available, like `command_exists`
- fixes #729
=> load theme _after_ loading any plugins, etc

themes/powerline-plain/powerline-plain.theme.bash
This will basically show the current ruby and gemset using the rvm-prompt command and improves the color of the powerline-theme for better readability.
=> Adding support for rvm-prompt to powerline-plain theme

plugins/available/git.plugin.bash
When the .gitignore file is changed, running this plugin will empty git's cache and readd all the files. This will pick up on the change to .gitignore and blacklist the unwanted files.
=> Added gitignore-reload plugin

aliases/available/docker-compose.aliases.bash, plugins/available/docker-compose.plugin.bash
Only function so far: `docker-compose-fresh`, which shuts down a running docker-compose instance, deletes the containers, and starts up fresh instances, then tails the container logs.
Converted this from an alias to a function so that a parameter can be provided for the name of the `docker-compose.yaml` file name.
=> Added docker-compose plugin

install.sh
This pull request satisfies #676 requesting a silent install option without prompts. I have followed requirements provided by @nwinkler in the issue thread.
=> Silent install - solution to issue #676

themes/base.theme.bash
Calling the `safe_append_prompt_command` function results in the PROMPT_COMMAND environment variable having a `;` suffix. e.g. `COMMAND1;COMMAND2;`
A subsequent append to the environment variable, like in the preexec_install function
```
function preexec_install () {
....
PROMPT_COMMAND="${PROMPT_COMMAND};preexec_invoke_cmd"
....
}
```
will result in the variable being set to `COMMAND1;COMMAND2;;preexec_invoke_cmd `. This causes the following error.
```
-bash: PROMPT_COMMAND: line 0: syntax error near unexpected token `;;'
-bash: PROMPT_COMMAND: line 0: `direnv_hook;prompt_command;;preexec_invoke_cmd`
```
This change ensures that the `safe_append_prompt_command ` function does not set the `;` suffix.
This fixes #772.
=> PROMPT_COMMAND env var should not end in ';'

aliases/available/laravel.aliases.bash
Changed the laravel alias a:controller from 'php artisan controller:make' to 'php artisan make:controller'.
Added the laravel alias, so for new projects, can be used "laravel new project"
=> Changed the laravel alias a:controller to php artisan make:controller 

lib/preexec.bash
Fix for https://github.com/Bash-it/bash-it/issues/767
In iTerm on OSX El Capitan, the `PROMPT_COMMAND` variable can be empty when it is referenced in `preexec_install`. This causes an extra semicolon to appear at the beginning of the `PROMPT_COMMAND` var.
This fix checks for an empty or whitespace only `PROMPT_COMMAND` before appending `preexec_invoke_cmd`
=> Check for empty PROMPT_COMMAND before appending preexec_invoke_cmd

lib/helpers.bash
Running `bash-it help plugins` results in the following error in the output:
```
lib:
cat: /tmp/grouplist.v0W0.lib: No such file or directory
:cat: helpers: No such file or directory
helpers:
```
It appears that the group value for the pathmunge function is set to 'lib helpers' which throws off the parsing logic in the _help-plugins function. Changing the group value for pathmunge to 'helpers' fixes this.
=> Fix for bash-it help plugins error (pathmunge group value).

plugins/available/base.plugin.bash
The usage function appears to be broken on OS X. When executing the function without a depth parameter you got the following error:
`>_ usage
du: option requires an argument -- d
usage: du [-H | -L | -P] [-a | -s | -d depth] [-c] [-h | -k | -m | -g] [-x] [-I mask] [file ...]`
The if-statement appears to be executed in reverse. Adding the quotes to the condition fixes this. If this change needs to added to the Linux section of the function please let me know and I'll update the pull request.
=> OS X fix for usage function.

plugins/available/fasd.plugin.bash
This should fix the additional issue found in #775.
=> Added empty check for PROMPT_COMMAND in fasd plugin

aliases/available/homebrew.aliases.bash
The “upgrade and clean up” Homebrew alias `bupc` doesn't need to use `&&` chaining to run `brew cleanup` after `brew upgrade --all`; Homebrew's `upgrade` command supports a `--cleanup` option that does just that.
I imagine this will also more gracefully handle situations where Homebrew is able to upgrade some but not all of the outdated packages on the system.
=> Use --cleanup on upgrade in Homebrew “bupc” alias

plugins/available/fasd.plugin.bash
According to fasd [README](https://github.com/clvv/fasd/blob/master/README.md):
> Optionally, if you can also source fasd if you want fasd to be a shell function instead of an executable.  
fasd can be also used by sourcing it and not only by including it into path. This patch will ensure that fasd will be properly recognized, even when it is sourced and not included in path.
=> Recognize fasd when sourced

lib/helpers.bash
This is an artifact left over from when this function was extracted from
inside a loop https://github.com/Bash-it/bash-it/commit/b524bb604756d33ec330abe5300a7a1a6d3a833b
However, `continue` isn't doing anything when not inside a loop and this
now raises a warning in bash 4.4:
"continue: only meaningful in a `for', `while', or `until' loop"
=> Remove `continue` from conditional

themes/base.theme.bash
- Made `scm_prompt_info` leverage `scm_prompt_vars` and independent of _# backwards-compatibility_ functions
- The _# backwards-compatibility_ functions will still work as expected
=> improve scm_prompt_info

plugins/available/rbenv.plugin.bash
- Check if `rbenv` exists and is executable.
- Removed auto-completion script loader because `eval "$(rbenv init -)"` automatically does that.
- If [ruby-build](https://github.com/rbenv/ruby-build) (rbenv plugin for `rbenv install` command) is installed as plugin, add it to PATH
=> improve plugin for rbenv

aliases/available/homebrew.aliases.bash
Recently when you run `bcup` you'll get this nice little warning.
`Warning: We decided to not change the behaviour of `brew upgrade` so
`brew upgrade --all` is equivalent to `brew upgrade` without any other
arguments (so the `--all` is a no-op and can be removed).`
This PR removes `-all` from the bup and bupc aliases.
=> Fixing bcup alias as per Brew note

themes/brainy/README.md, themes/brainy/brainy.theme.bash
Add Brainy - a simple colorful terminal prompt theme (inspired by a number of other themes).
Readme: [Theme features and description](https://github.com/MunifTanjim/bash-it/blob/62554b84c8f9a5ec4c8dab3a4b7d85b1168d160f/themes/brainy/README.md)
Screenshot:
=> add brainy theme

aliases/available/curl.aliases.bash
I find this command extremely helpful in my day-to-day work, much better than using -I for a HEAD request since the site you are looking at might show different headers for GET vs HEAD
=> adding new curl alais to show only headers on a GET request

README.md, install.sh
- ask whether you want to modify existing config file (i.e. `.bashrc`) during installation
there is no way to run `install.sh`, keeping config file (i.e. `.bashrc`) unchanged.
therefore, i add this option for interactive mode.
=> [install.sh] add flag not to modify exist config file during installation

completion/available/ssh.completion.bash
Hi there, 
I think `scp` should have completion too. Basically it can use same completions with `ssh`
=> scp should have completion too

completion/available/system.completion.bash
This is required for projects completion, otherwise you get this error:
```
_init_completion: command not found
```
=> Load bash-completion2 on macOS

completion/available/system.completion.bash
Fedora import that script from /etc/bashrc script that can import /etc/profile.d/*.sh
See issue #849
=> Add other bash completion importation for other distribution

completion/available/vault.completion.bash
Adding latest vault completion from https://github.com/iljaweis/vault-bash-completion.  I'm using the credit header that was there from the author hopefully that's good enough.  If not let me know and I'll add anything that's missing.
=> Adding latest vault completion

plugins/available/gradle.plugin.bash
Just adds a little function that uses the gradle wrapper if it's present in your current directory hierarchy or falls back to the system-level gradle if there's no wrapper.
=> Gradle plugin

completion/available/makefile.completion.bash
Sometimes, Makefile won't be completed (as for me on Fedora 25) as soon as bash-it is activated. This completion script can provide a Makefile completion.
=> Add Makefile completion

README.md, themes/base.theme.bash
This is an attempt to fix #873. It really only applies to git so left the other SCMs unmodified for backwards compatibility as I have not tested the speed of other SCM tools. If this is accepted, I'll create a PR with my theme that utilizes it.
=> Add option for basic git status prompt

plugins/available/percol.plugin.bash
Without the `function` keyword, the file did not load when using Bash
v3.x. With the added `function` keyword, the file can be parsed and the
error message about having to install Bash v4 is shown.
Closes #881
=> Fixed percol plugin function syntax

aliases/available/general.aliases.bash, lib/appearance.bash
Fixing the `ls` and `grep` aliases to be omitted if the `color` options are not available.
Closes #884 #643 #819 #818
=> Upstream grep color

aliases/available/homebrew-cask.aliases.bash
Remove bcup alias since it's being depreciated by Homebrew:
`Warning: Calling brew cask update is deprecated and will be disabled on 2017-07-01!
Use brew update instead.`
=> Remove bcup alias

aliases/available/osx.aliases.bash
Sublime Text was not opening specified file or folder using the alias. Fixed by removing `--args`
Details in  #889
=> Fix Sublime Text alias. Solves #889

themes/base.theme.bash, themes/bobby/bobby.theme.bash
- Refactor common code into scm_prompt_info_common
- Add AIO function to echo scm prompt char and info.
Invoking the `scm_char` and `scm_prompt_info` functions separately for `PS1`
duplicates calls to the `scm` and `scm_prompt_char` functions to check what
`${SCM}`, if any, we currently reside in. This problem was exacerbated
when working outside of any repo as we had to go through all the
conditionals twice just to determine we're not in any scm repo. Unnecessary
conditionals slows down the prompt so this adds a new function that
streamlines printing out both the scm char and scm prompt info with one
invocation.
- Add prefix and suffix capability to SCM char
- Update bobby theme to use `scm_prompt_char_info`.
The bobby theme now uses `scm_prompt_char_info` to print out the SCM char
and …
=> Add AIO function to echo scm prompt char and info

plugins/available/docker.plugin.bash
Instead of piping the standard output of `docker ps` and `docker images`
through a series of heads, tails, and awks, use the flags available to
the `docker` command to achieve the same goal.
=> Simplify docker functions

completion/available/pip3.completion.bash
When you install Python 3 you also get pip3 which doesn't have a completion setup.
=> Adding pip3 completion

aliases/available/general.aliases.bash, completion/available/bash-it.completion.bash
Title and diff should be self-explanatory.
=> Alias and complete common misspellings of bash-it

plugins/available/python.plugin.bash
Do now show python warnings (import or syntax) if module name is bad.
=> Python errors handling in 'pyedit' command

themes/powerline/powerline.base.bash
If you're running a script which returns errors for unbound variables and doesn't unset it, powerline will fail to load the prompt as there are some potentially empty variables in those functions.
This PR fixes unbound variables errors you can get if bash got `set -u`.
=> Prevent unbound variable errors in Powerline

README.md, lib/appearance.bash
I wanted to track my custom theme file in a different repo outside of the .bash_it directory.
This tweak here allows you to set the BASH_IT_THEME to point at the specific theme file you want to use without worry of the putting it into the `.bash_it/themes/(name)/(name).theme.bash` scheme.
Example of my .bashrc for setting the theme using this tweak:
```
#export BASH_IT_THEME='modern'
export BASH_IT_THEME="$HOME/.local/bash_it-theme.bash"
```
=> adding ability to set theme as a path to specific file

themes/colors.theme.bash
`\[\e[0;37;1m\]` means bold_white, and bash-it has it as `bold_white` already. I replaced it with `\[\e[0;37m\]` to use it as a normal white color.
Thanks!
=> Fix white color in colors.theme

completion/available/ng.completion.bash
This PR dynamically adds completion support to Bash-It.
It is forward-compatible, meaning that currently Angular CLI 1.0.0.beta.28.3 is the main version.
With 1.0.0.beta.30 onwards, the option --bash is taken effect to produce bash-only syntax.
This works, because beta.28.3 "ignores" --bash.
The output is a clever mix of bash and zsh, which detects the shell and sets up the completion accordingly.
In future, the clever monkey-patching is not included anymore, thanks to --bash, yay!
=> Add support for ng (Angular CLI) completion.

themes/base.theme.bash
From issue: https://github.com/Bash-it/bash-it/issues/920
Addresses the vulnerability described here: https://github.com/njhartwell/pw3nage
We use a whitelist to [a-zA-Z0-9\/-] and replace malicious branch names.
Branch name: `$(./pw3n)`
```
2017-04-19 18:39:40 ⌚  curtis in ~/workspace/source/mine/pw3nage
± |---/pw3n- ✓| →
```
Normal branch name
```
2017-04-19 19:53:56 ⌚  curtis in ~/workspace/source/mine/bash-it
± |denmat-issues-920 U:1 ?:3 ✗| →
```
I did battle with this for some time trying various different ways to address the issue but nothing else worked. Open to alternatives to this approach.
=> issue #920 - bash interpolation vulnerability

plugins/available/autojump.plugin.bash
as title, load autojump.sh in debian system.
This is a more general version of #758
=> plugins: autojump: support debian system

plugins/available/xterm.plugin.bash, template/bash_profile.template.bash
This allows users with long usernames (ie full name) to only see a part of it.
I'm open to suggestions about what the default "short username" should should actually _be_. I chose to just truncate at 8 chars, but maybe there's better options. I am also unaware if there's an utility to get a short username automatically (something like `hostname -s` but for users).
=> Support short username in xterm title plugin

plugins/available/xterm.plugin.bash, template/bash_profile.template.bash
This allows the user to see only last level of the current path (if dirname is longer than 8 chars),
and only first word of the ongoing command line if it's longer than 8 chars.
For example:
```
find / - type f {/var/foo/long} (user@server)
```
will become:
```
find {long} (user@server)
```
=> Support shortened command & dir name in xterm title plugin

install.sh
NOTE: This doesn't make Bash-it usable as there's so many similar errors scattered in other locations, this commit simply makes installer works
Signed-off-by: 林博仁 <Buo.Ren.Lin@gmail.com>
=> Make installer more path-with-spaces-proof, fixes #952

aliases/available/git.aliases.bash
`gw` is currently aliased to `git whatchanged` but that collides  with the gradle  plugin, which defines a `gw` function.
See https://github.com/Bash-it/bash-it/blob/master/plugins/available/gradle.plugin.bash#L4
=> aliases: git: change 'gw' to 'gwc' to avoid collision with gradle plugin

plugins/available/percol.plugin.bash
Percol defines zz alias by default. This ensures that the percol
plugin will work as expected.
=> plugins: percol: Unalias zz before defining zz function

lib/helpers.bash
This closes Bash-it/bash-it-docker#1
=> fix(docker): "bash-it help plugins"

plugins/available/battery.plugin.bash
`upower` is the new standard for knowing the power status of devices connected to the Linux kernel > v3.x. The `acpi` package is now only an optional package that requires an additional installation. This change-set adds support for `upower` over-riding `acpi` for first preference. However, the `acpi` mechanism has been maintained as a fallback mechanism for legacy systems running the Linux  kernel < v3.
Reading Reference : https://askubuntu.com/questions/69556/how-to-check-battery-status-using-terminal
=> Battery upower

plugins/available/nvm.plugin.bash
Some people (including myself) like building / compiling and binding libraries in custom directories rather than the default (`$HOME`). The `nvm` plugin hard-codes `NVM_DIR` to `$HOME/.nvm`. This change would honor the externally set `NVM_DIR` shell variable and then fall-back to the default `$HOME/.nvm` if the variable isn't set externally.
=> Honor NVM_DIR shell variable set externally

themes/iterate/iterate.theme.bash
When logging in to a new CentOS 7 machine COLUMNS has not been set before the theme is evaluated, causing the following error:
```shell
irongiant-mbp → ssh clayreimann@toren.ddns
Last login: Fri Jun 23 10:05:11 2017 from cpe-24-209-155-17.wi.res.rr.com
-bash: /1: syntax error: operand expected (error token is "/1")
-bash-4.2$ 
```
This fix is based on advice from https://stackoverflow.com/a/3601734
=> Guard against unset COLUMNS

.travis.yml, CONTRIBUTING.md, DEVELOPMENT.md, README.md, aliases/available/general.aliases.bash, bash_it.sh, completion/available/bash-it.completion.bash, install.sh, lib/helpers.bash, lib/preview.bash, plugins/available/alias-completion.plugin.bash, plugins/available/base.plugin.bash, plugins/available/fzf.plugin.bash, plugins/available/nvm.plugin.bash, plugins/available/z.plugin.bash, test/install/install.bats, test/install/uninstall.bats, test/lib/helpers.bats, test/lib/search.bats, test/plugins/base.plugin.bats, test/run, test/test_helper.bash, test/themes/base.theme.bats, themes/atomic/atomic.theme.bash, themes/base.theme.bash, themes/brainy/brainy.theme.bash, themes/demula/demula.theme.bash, themes/rana/rana.theme.bash
See #944 for more details... This implements the first part of that issue.
Here's what I changed:
* When enabling a component, it is now linked to `enabled/150---foo.aliases.bash` instead of just `enabled/foo.aliases.bash`. This will allow to prioritize the order in which files are loaded. Default priorities are:
* Aliases: 150
* Plugins: 250
* Completions: 350
* The default priority can be changed by including a comment with the new priority in the file, e.g. like this for the `nvm` plugin:
```bash
```
* Changed the default priority for some components, e.g. loading the `node` plugin after the `nvm` plugin.
* Added a `bash-it migrate` command that moves existing implementations to the new priority-based load order. The `migrate` command is automatically called when running `bash-it …
=> Load Order/Priority

aliases/available/general.aliases.bash
If .bashrc is sourced while `set -e` is set, and `gshuf` is not installed,
then running `which gshuf` will cause the shell to error and exit.
Running `which gshuf` during an if condition will capture the error.
=> general.aliases: Run `which gshuf` in if condition

themes/bakke/bakke.theme.bash
i am using the bakke theme and just noticed that it does not display a potential virtual environment in the prompt. this pull request fixes this issue; it’s just a minimal change.
=> fix: missing virtualenv prompt

themes/liquidprompt/.gitignore, themes/liquidprompt/liquidprompt.theme.bash
see: https://github.com/nojhan/liquidprompt
Might be a bit hacky, but people can improve on it.
=> Liquidprompt Theme

CONTRIBUTING.md, README.md
Bash-it previously did not specify compatibility with any particular
Bash version, but uses features in Bash 3.2 (like omitting quoting for =~
expressions) while ignoring features in Bash 4 (like associative
arrays). By explicitly mentioning the minimum supported version, it is
easier for contributors to understand which shell features are usable.
=> Explicitly mention Bash 3.2 compatibility

aliases/available/systemd.aliases.bash
Just a few common used systemd aliases for less typing. 
How I use it: 
'sc' means systemwide systemctrl, 'scu' means systemctrl --user. Stop and start has same beginning letter, so 'e' is used to denote 'end', for example scue means systemctrl --user stop.
=> Added aliases for easier systemd use.

plugins/available/sshagent.plugin.bash
sshagent plugin:
- manage setup of sshagent in bash session:
- force opinionated agent management based on ~/.ssh/ file
- support for shared file systems on different host (file name contains hostname)
- check env for any live/dead agents
if alive - use it
otherwise - spawn our own
Signed-off-by: Max Kovgan <max@opsguru.io>
=> reference implementation of #1016

completion/available/bash-it.completion.bash
this completion was printing annoying error messages from `ls` to stderr when no matching item found
=> bash-it.completion suppress ls error when none found

test/plugins/ruby.plugin.bats
ruby plugin obviously only adds gem to the PATH if ruby is present
=> skip ruby PATH test if ruby not installed

README.md, bash_it.sh
I found the out-of-place folder for custom configuration quite interesting (```BASH_IT_CUSTOM ```), as I would be able to load my current setup maintained in a separated repository. However, I think the current approach that only load ```*.bash``` files directly under the specified folder is too restrictive. With this addition, scripts could be organized in sub-directories.
In order to maintain compatibility with bash before version 4, it just adds an additional file pattern nstead of using ```**/*.bash``` pattern and ```globstar``` bash option.
=> Recursive load of out of place custom config files

completion/available/export.completion.bash
Auto-completion for `export`. Will find already defined environmental variables using `printenv` and provide those for autocompletion.
=> export.completion.bash

plugins/available/osx.plugin.bash
This PR fixes issue #708 where themes were sometimes left in a partially broken environment with missing dependencies, causing recurring error messages on every prompt.
On OS X, when a theme is active with a dynamic `PROMPT_COMMAND` which it does not bother to export, and said `PROMPT_COMMAND` is backed by shell functions which are not exported either, and at the same time the theme is not OS-X-aware (with respect to `update_terminal_cwd`), and the user then launches a (non-login) interactive subshell from the OS X Terminal, a `command not found` message appears on every command invocation.
The issue is caused by a regression in PR #514, which injects `update_terminal_cwd` into the prompt in order to support Terminal’s open-tab-in-current-directory feature. As a side effect, this PR also …
=> Preserve `PROMPT_COMMAND` exportedness for subshells

bash_it.sh
Disable trap DEBUG on subshells, this will fix issue where some sub-shell could issue unexpectedly some of the subshell commands.
Example:
~ for i in $(ls /tmp | head -2) ; do ssh $i lala; done 
ssh: Could not resolve hostname \033]0;fri: Temporary failure in name resolution
ssh: Could not resolve hostname sep: Temporary failure in name resolution
ssh: connect to host 2017 port 22: Invalid argument
ssh: Could not resolve hostname 14:51:18: Temporary failure in name resolution
ssh: Could not resolve hostname +0200: Temporary failure in name resolution
ssh: Could not resolve hostname for: Temporary failure in name resolution
ssh: Could not resolve hostname i: Temporary failure in name resolution
ssh: Could not resolve hostname in: Temporary failure in name resolution
ssh: Could not resolve …
=> Fix execution of trap DEBUG on subshells

.gitignore, DEVELOPMENT.md, bash_it.sh, completion/available/bash-it.completion.bash, lib/helpers.bash, plugins/available/battery.plugin.bash, test/README.md, test/bash_it/bash_it.bats, test/completion/bash-it.completion.bats, test/fixtures/bash_it/aliases/available/a.aliases.bash, test/fixtures/bash_it/aliases/available/b.aliases.bash, test/fixtures/bash_it/plugins/available/c.plugin.bash, test/install/install.bats, test/install/uninstall.bats, test/lib/helpers.bats, test/lib/search.bats, test/plugins/ruby.plugin.bats, test/run, test/themes/base.theme.bats, themes/atomic/atomic.theme.bash, themes/base.theme.bash, themes/brainy/brainy.theme.bash, themes/demula/demula.theme.bash, themes/powerline/powerline.base.bash, themes/rana/rana.theme.bash
This PR includes the second half of the functionality discussed in #944.
What has been changed:
* When enabling components (aliases, completions or plugins), they are now enabled in a global `$BASH_IT/enabled` directory, instead of having separate directories per component type (e.g. `$BASH_IT/aliases/enabled`). This allows for more flexible ordering of the load priority, where aliases, completions and plugins are mixed, instead of loading them one by one. See #974 for the first half that allows for defining a load order/priority for each enabled component.
* Moved the `command_exists` function from the `base` plugin to an internal function called `_command_exists` in the `helpers.bash` file, to break the dependency on the `base` plugin. See #1009 for an example of an error.
* Added lots …
=> Move enabled components to a global directory

completion/available/brew.completion.bash
Two commits, split for clarity.
The first addresses the brew bash completion file path, as discussed in #1046.
The second is a performance optimization to reduce the forks called during evaluation, as [seen in this pattern](https://github.com/Bash-it/bash-it/blob/a75a53b7863cd63d489bb3f8669c1b293278c52c/completion/available/system.completion.bash#L17-L22). A naive test for the second commit:
```console
$ sudo dtruss -f -t 'syscall::fork*' -c bash completion/available/brew.completion.bash 2>&1 | grep ^fork
fork                                           25
fork                                           15
```
Happy to squash, or split, depending on what is desired.
=> Update brew completion

README.md, lib/composure.bash, lib/helpers.bash, plugins/available/alias-completion.plugin.bash
https://github.com/Bash-it/bash-it/blob/517d4b2ca486945aa1bec3b496f946d3b8493350/plugins/available/alias-completion.plugin.bash#L32
This should normally be handled by the system, right?
The reason I'm asking is that in prefixed environments such as [Termux](https://wiki.termux.com/wiki/Differences_from_Linux) the temporary directory is not `/tmp`. 
A safer way to create temp files is to use `mktemp -t ` which will use `$TMPDIR` (or some other heuristics). 
Cleanup could also change to `rm $TMPDIR/...` but isn't it better to just leave that to the system?
=> Do we need to explicity `rm` tempfiles?

plugins/available/docker-compose.plugin.bash
The `--all` flag was removed in docker-compose 1.7.0 last year. https://github.com/docker/compose/pull/3466
Currently produces:
```
WARNING: --all flag is obsolete. This is now the default behavior of `docker-compose rm`
```
=> Update docker-compose plugin

plugins/available/go.plugin.bash
As of Go v1.8, $HOME/go is the default $GOPATH. See https://github.com/golang/go/issues/17262 for the discussion.
=> Change default $GOPATH to $HOME/go

.gitmodules, CONTRIBUTING.md, test/bash_it/bash_it.bats, test/completion/bash-it.completion.bats, test/install/install.bats, test/install/uninstall.bats, test/lib/helpers.bats, test/lib/search.bats, test/plugins/base.plugin.bats, test/plugins/ruby.plugin.bats, test/run, test/test_helper.bash, test/themes/base.theme.bats
Closes #1044.
Closes #1045.
Move to the forked and maintained `bats-core` library (https://github.com/bats-core/bats-core) instead of the unmaintained one. Provide it as a Git submodule instead of cloning it locally - this makes it easier to point to a different version if needed.
Also moved to using the `assert` functions from https://github.com/ztombol/bats-assert and https://github.com/ztombol/bats-file (also included as Git submodules) to get rid of the custom implementations.
Modified all of the test cases to use the new functions were needed.
I added a custom function for checking for symbolic links, since the `bats-file` library does not support that. It would be great to get that added to bats-file, but it looks like that repo is no longer maintained.
Some of the tests need to be …
=> Bats migration

test/plugins/base.plugin.bats, test/run
Fixes #1059 
Checking for several file names as part of the test for the `buf` function, since that seems to fail from time to time (corner case).
Also fixed a couple of smaller issues in the test cases for the base plugin.
=> Buf unit test

themes/purity/purity.theme.bash
By specifying `PURITY_THEME_PROMPT_COLOR` in your environment you can change the path to a different color. Useful for signifying that you're in a particular environment and such.
=> Add ability to specify the path color

README.md
Very minor.
https://www.wired.com/2016/06/apple-os-x-dead-long-live-macos/
=> Mac OS X -> macOS

plugins/available/sdkman.plugin.bash
sdkman can be installed to any [arbitrary directory ](http://sdkman.io/install.html) by way of setting `SDKMAN_DIR`.
This is a small change to the sdkman plugin to use `SDKMAN_DIR` if already set, and fall back to `$HOME/.sdkman` if not.
=> Use custom SDKMAN_DIR if set

plugins/available/aws.plugin.bash
This change adds the support to assumed role profiles. To have the full list of profiles it gets it from .aws/config
=> fixed awskeys with all profiles

plugins/available/battery.plugin.bash, test/plugins/battery.plugin.bats, test/run
Fixes #1022 
This could also help with #948 
Added lots of test case for the `battery_percentage` function, and tried to consolidate the output format for the function, all numbers should be formatted as two digits with leading zeroes (except for the "100").
Since this has only been tested with the test cases, it would be good if people with different operating systems (Linux, Windows) could test this locally...
=> Fixed battery low 

themes/base.theme.bash
This PR allows to theme the git stash count and it keeps the same color as the git branch.
With this PR, the style of the stash count can be changed:
The PR introduces 2 new attributes: `SCM_GIT_STASH_CHAR_PREFIX` and `SCM_GIT_STASH_CHAR_SUFFIX`. I would prefer to keep consistency with the other git attributes, but this way it keeps compatibility with current themes.
=> Allow theming git stash chars

themes/axin/axin.theme.bash, themes/binaryanomaly/binaryanomaly.theme.bash, themes/sexy/sexy.theme.bash
The used terminal emulator (urxvt, xterm, ...) is responsible to set this variable correctly. If the bash-it theme overrides this setting some applications behave unexpected, because they use the wrong escape sequences. Setting the TERM variable manually inside scripts is bad practice and shall be avoided.
See also https://unix.stackexchange.com/questions/108410/is-it-correct-to-set-the-term-variable-manually
=> bash-it themes must not set the TERM variable

themes/base.theme.bash
Added feature to detect the ruby version interpreter
```bash
rb_interp_prompt
```
and added to the existing function to be used in any theme.
=> Update base.theme.bash with RUBY interpreter version check

aliases/available/laravel.aliases.bash
On a mac where the homedirectory is in /User/{username} instead of /home/{username} this alias broke my laravel comand. This fix is tested on mac and on linux ubuntu.
=> Alias laravel using /Users/andreas variable instead of /home/andreas.

completion/available/sdkman.completion.bash
There is no more the CSV variable after __sdkman_build_version_csv
=> Fix "sdkman use" version completion

themes/base.theme.bash
With the added $ in there, it would show an error in Git repos:
-bash: ##: command not found
This was introduced in #1109.
=> Fixed issue introduced in #1109

aliases/available/general.aliases.bash
If `IRC_CLIENT` is not set then `alias irc` is set to an empty string. So executing `irc` in that case will return an empty output which is kind of misleading. Expected behavior could be `-bash: irc: command not found`.
To achieve the expected behaviour I have made `alias irc` fallback to value `irc` if `IRC_CLIENT` is not set
=> Fallback value for alias irc

README.md
GitHub strips commas from the auto-generated anchor links for section headings.
This PR fixes the TOC by removing the commas from  `Custom scripts, aliases, themes, and functions` link.
=> Fix table of contents link to its correct section

bash_it.sh, test/themes/base.theme.git.bats, themes/base.theme.bash, themes/githelpers.theme.bash
Currently, if a branch has a name like `my_branch`, the non-alphanumeric characters are escaped to dashes to avoid potential code injection. By replacing the branch name in $PS1 with a function that is evaluated later (e.g. `$(branch-name)`), the branch name is only evaluated once and "special" characters in the branch variables are not evaluated by bash.
This PR refactors a lot of the git prompt logic, so I've begun adding tests. There are still some pending tests, so this PR isn't ready for merging, but will get updates as I add more tests and respond to any feedback.
@nwinkler When the tests are complete, I can add them as an initial commit before the refactor and injection fix to prove that functionality has remained the same. It's a bit harder to do, and is backfilling tests, so I'd …
=> Allow non-alphanumeric git branch names

themes/simple/simple.theme.bash
simple theme had a wrongly escaped `$` which resulted in `~/.bash_it($(_git-friendly-ref) U:1 ✗)`
this should fix it
tested on macOS and linux
=> fix simple theme

themes/clean/clean.theme.bash
There is a bug in the clean theme. The `scm_prompt_info` function should be executed and not escaped.
=> clean theme: Remove extra \

plugins/available/gif.plugin.bash
1. sometimes mediainfo returned the wrong FPS value, changed the logic.
2. Added an option to create a WebM file in addition to the gif. they are tiny and already supported on some social media as a replacement for Animated GIFs.
A future PR will include a GIF-to-WebM function, I'm just working on improving the output quality.
=> GIF plugin: Fix the FPS detection and add webm creation as a future-looking feature

plugins/available/percol.plugin.bash
The original patch (659ecd038818c1b27bddaa2e60b0eb7f044f644a)
unaliases the percol alias, however, does not validate if the alias
is already defined. This leads to the following message that is shown
everytime a new bash session is spawned where this variable is not
defined when the percol plugin is enabled.
bash: unalias: zz: not found
=> Fixes: 659ecd038818 plugins: percol: Check for alias zz before unalias

plugins/available/proxy.plugin.bash
many setups have `python` set to `python3`, causing a syntax error
```
$ svn-show-proxy
SVN Proxy Settings
==================
File "<stdin>", line 14
print 'http-proxy-host      : ' + proxy_host
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('http-proxy-host      : ' + proxy_host)?
```
explicitly using `python2` fixes this
=> explicitly use python2 for svn proxy functions

bash_it.sh, themes/base.theme.bash, themes/p4helpers.theme.bash, themes/powerline/powerline.base.bash
This patch adds very simple support for the Perforce SCM:
>   https://www.perforce.com/
Although perforce is proprietary software, it's somewhat prevalent in enterprise
companies. This patch looks to provide some basic bash_it functionality that
I've come to love for git. I base everything off of two perforce commands:
`$ p4 set`
This command does not require a connection the perforce server, it simply tells
us if a directory is managed by the Perforce SCM or not. In addition the
command:
`$ p4 opened`
is used to provide the list of pending changes in the client and the number of
opened files in the client. The `p4 opened` command requires a connection to the
perforce server, hence it's run under a `timeout` command. The "p4 opened"
processing into it's own bash file that now has to be …
=> Add priliminary support for perforce SCM

themes/powerline-multiline/README.md, themes/powerline-naked/README.md, themes/powerline-plain/README.md, themes/powerline/README.md
I've collected the supported prompt options from reading `themes/powerline/powerline.base.bash` and documented them in all powerline* themes.
=> Improve documentation on prompt options for powerline themes

aliases/available/clipboard.aliases.bash
Breaking up alias declarations into their own lines so that bash-it help aliases will register them
=> Clipboard's aliases will now appear on bash-it help aliases

lib/helpers.bash
In order to make a swift comparison between the currently-installed
version vs the latest commits on `master`, emit a clickable URL that
will show the user the exact changes.
Signed-off-by: Mike Fiedler <miketheman@gmail.com>
=> Add a comparison URL to version

plugins/available/osx.plugin.bash
The layout will have returned to the default, placing all bundled
apps onto the first screen of Launchpad, and third party apps onto
the secondary (and third, if applicable) screens
=> Add reset launchpad layout function

completion/available/pipenv.completion.bash
use `--completion` from pypa/pipenv docs instead of old `_PIPENV_COMPLETE`
=> Update pipenv completion

themes/powerline/powerline.base.bash
Reverts Bash-it/bash-it#1175
Sorry - just noticed that this is referring to a variable that you have only introduced in a different pull request, #1176.
I would like to see this cleaned up before it gets added.
=> Revert "fix wd_prompt multiline croping"

plugins/available/explain.plugin.bash
Fixes bug where Bash prints a "command not found" message when the
function is run, due to incorrect quoting of the argument to the
meta function example.
See: https://stackoverflow.com/a/1250279/2573172
=> Fix quoting in the Explain plugin

themes/base.theme.bash
On some hosts if a vcs tool is missing, eg. git, function scm_prompt_info does work properly. 
I noticed this behavior on a host without the git.
=> Function scm_prompt_info does not work properly if a vcs tool is missing

themes/candy/candy.theme.bash
The default text style was not being set back to normal so terminal output was rendering bold, e.g. for an ls command
=> Fix bold text issue

themes/powerline-multiline/powerline-multiline.base.bash
During usage I noticed that a lot of the times when the path is long enough to reach the right side prompt but not long enough to enter a second line, the part that overlaps with the right prompt gets covered and it's very inconvenient:
If I'm inside a folder at `~/Documents/some/long/path/to/folder`, it would show
```
~/Documents/some/long/path/to/fo<12:00:00 <user
>
```
whereas after the edit it will correctly show
```
~/Documents/some/long/path/to/folder>
<12:00:00 <user
>
```
=> Update powerline theme to avoid overlapping left and right prompt

themes/codeword/README.md, themes/codeword/codeword.theme.bash
- Single line PS1 with conveniences for `ssh` and `scp`
- Shares history in realtime among bash windows
Screenshots:
=> Add `codeword` theme

completion/available/ssh.completion.bash
Handle includes in `.ssh/config` and fix bug that caused `Host` entries with wildcards in them to be included in the autocomplete suggestions.
E.g. `Host *-server` host entry in `~/.ssh/config` leads to either the suggestion "*-server", or worse, the wildcard being expanded in `bash-it/completion/available/`. The latter would yield `my-server` if, a file `bash-it/completion/available/my-server` existed, i.e. the wildcard was successfully expanded in the script directory. 
This pull request also handles the `Include` directive in ssh config files (although non-recursive).
>     Include
>             Include the specified configuration file(s).  Multiple path‐
>             names may be specified and each pathname may contain glob(3)
>             wildcards and, for user configurations, …
=> Fix wildcards and handle includes in ssh complete

themes/base.theme.bash
Python 3.7 version prompt now includes compiler version in the second line. Bash it would print both Python and GCC version as the "py" version.
Before:
```
py-3.7.0
py-5.4.0 localhost in ~
```
After:
`py-3.7.0 localhost in ~
`
=> Display only first line of Python 3.7 version

themes/base.theme.bash
```
login@host:~  |master → origin/master ↑1 ✓| 0
$ env | grep SCM_GIT
SCM_GIT_SHOW_REMOTE_INFO=true
SCM_GIT_SHOW_DETAILS=false
SCM_GIT_SHOW_MINIMAL_INFO=false
SCM_GIT_IGNORE_UNTRACKED=true
login@host:~  |master → origin/master ↑1 ✓| 0
$ git config --get bash-it.hide-status
1
login@host:~  |master → origin/master ↑1 ✓| 0
$ bash -l
login@host:~  0
```
I've marked a repository to not check git status but despite this, bash-it checks it. 
Ps. I could not upload an image.
=> The function _git-hide-status is invoked to late

plugins/available/fzf.plugin.bash
fd is orders of magnitude faster when searching for files. This patch
will force fzf to use fd instead of find.
This change is implemented per the recommendation:
https://github.com/junegunn/fzf#environment-variables
=> Use fd for fzf if available on system

plugins/available/osx.plugin.bash
The direnv bash hook already adds a semicolon to the PROMPT_COMMAND and this
plugin will add another one if direnv is installed. This commit will avoid to have double semicolon by removing trailing semicolon from PROMPT_COMMAND if presented before appends "update_terminal_cmd" function
=> Avoid double semicolon in the PROMPT_COMMAND

completion/available/sdkman.completion.bash
The versions that can be installed were not completed. The list of available versions showed the installed versions.
The function retrieves the available versions and removes the already installed versions.
=> Added completion of installable versions

README.md, themes/base.theme.bash
In order to make `git_prompt_vars` run faster
As a user with slow `git stash list`
I want to be able to optionally disable running `git stash list` when
`git_prompt_vars` is executed
Note that this doesn't implement the complete feature set proposed in #914
=> Add SCM_GIT_SHOW_STASH_INFO flag #914

plugins/available/aws.plugin.bash
AWS_DEFAULT_PROFILE is deprecated, AWS_PROFILE is the correct one now.
+info:
https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html
=> Update AWS variable name

plugins/available/aws.plugin.bash
Added support to awskeys to `AWS_SESSION_TOKEN`. This is needed if you are working with temporary credentials using STS
More details: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_use-resources.html#using-temp-creds-sdk-cli
=> aws session token support on awskeys

plugins/available/aws.plugin.bash
Honor the environment variables:
```
AWS_CONFIG_FILE
AWS_SHARED_CREDENTIALS_FILE
```
in the aws plugin.
+info:
https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html
=> Allow custom aws config files path

aliases/available/docker.aliases.bash
New aliases that were added in PR #1257 would execute the commands instead of setting them as an alias, which is _highly_ undesirable.
=> Fixing quotes around new docker aliases

README.md, bash_it.sh, template/bash_profile.template.bash
Fixes #1001
All PS theming will only be applied if `$BASH_IT_THEME` is not empty.
My IDE was trimming some lines in the readme, I hope that's alright. :)
=> disable theming by checking theme var for value

plugins/available/fzf.plugin.bash
After this [PR](https://github.com/junegunn/fzf/pull/1282) fzf can use the XDG spec in the installation, so now the plugin is able to load from it.
=> Support XDG in fzf plugin

lib/helpers.bash
After updating when there are pending changes, **bash-it** doesn't returns to the previous path.
=> Bash-it don't returns to the previous path after update

lib/helpers.bash
This fixes #1038 by showing the merge commits prior to upgrading and prompting the user to accept them. 
This is a bit crazy to test. Here's how I went about it:
```console
> git log --merges origin/master
> git checkout master && git reset $commit_id_from_previous_step
> git cherry-pick --no-commit feature/show-upgrades^
> git cherry-pick --no-commit feature/show-upgrades
> git commit -m "Just for testing purposes…"
> bash-it reload && bash-it update
```
After I confirmed that, I reset back against `origin/master`.
=> Show upgrades before blindly upgrading

lib/helpers.bash
Adding `--first-parent` ensures that only commits from the master branch are used when showing the history. I've verified this change directly by comparing the `rev-list` output for `703105c..97df5c45`:
```console
$ git rev-list --merges 703105c...97df5c4
97df5c4540534c57da2381b1675cd2461274b2a6
b5976ada25a351ee603fa6a2c4aee99d56f0cabe
$ git rev-list --merges --first-parent 703105c...97df5c4
97df5c4540534c57da2381b1675cd2461274b2a6
```
Note: I've created this branch from 703105c so that I can merge `master` into it and test `bash-it update` once merged.
=> Adjust to only show merges into master

plugins/available/go.plugin.bash, test/plugins/go.plugin.bats
Because `GOPATH` supports a colon (`:`) separated list of directories, the current strategy of using `pathmunge` results in a wrong path appended to `PATH`.
This PR isolates the solution to the `go` plugin, but I could see the value of moving this logic to `pathmunge` if you agree as well. Let me know what you think.
```
$ echo $GOPATH
/home/cornfeedhobo/go:/usr/share/go/1.9/contrib
```
```
$ echo -e ${PATH//:/\\n}
/home/cornfeedhobo/go
/usr/share/go/1.9/contrib/bin
/usr/lib64/go/1.9/bin
...
```
```
$ echo -e ${PATH//:/\\n}
/home/cornfeedhobo/go/bin
/usr/share/go/1.9/contrib/bin
/usr/lib64/go/1.9/bin
...
```
=> Add multiple path support to go plugin

lib/helpers.bash
In e5b6869 (part of #1283), a regression was introduced, which caused `bash-it reload` to return with the working directory set to `.bash_it` and the original working directory discarded.
The root cause is the function wrapper in `helpers.bash`, which has always relied on the working directory not to change during execution of the wrapped code. This assumption no longer holds with the [changes introduced in #1283](https://github.com/Bash-it/bash-it/commit/e5b68695c0e77403e9ceda6e2707c1be326da81b#diff-9ec933b9deff7a50e810f0211b467399R2).
This PR fixes the regression by using `pushd`/`popd` in `bash-it reload`.
=> Make `bash-it reload` preserve working directory

aliases/available/homebrew.aliases.bash
`brew upgrade --cleanup` command is deprecated now so it should be removed.
```
○ → brew upgrade --cleanup
Updating Homebrew...
Fast-forwarded master to origin/master.
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask-versions).
No changes to formulae.
Warning: Calling 'brew upgrade --cleanup' is deprecated! Use 'HOMEBREW_INSTALL_CLEANUP' instead.
```
=> Remove Deprecated Brew Command

.gitignore, lib/helpers.bash, lib/search.bash, lib/utilities.bash, test/lib/helpers.bats, test/lib/search.bats, test/lib/utilities.bats
This commit improves Bash-It search functionality in a couple of ways:
* `bash-it search` (with no arguments) will print detailed help.
* `bash-it search` now accepts terms prefixed with '@' sign, indicating an exact match.
* `bash-it search` now performs smarter caching of the component listings/status
* The cache is automatically wiped upon a component enable/disable.
* The cache can be force-wiped by passing `--refresh` to the `bash-it search` command.
* Search command should now be much much faster in general.
The slightly improved search syntax is as follows:
```bash
$ bash-it search [-|@]term1 [-|@]term2 ... \
[ -e/--enable ] [ -d/--disable ] [ -r/--refresh ] [ -c/--no-color ]
```
=> Speed up bash-it Search & support exact matches

install.sh
Silence errors when installing
```
Would you like to enable the ag aliases? [y/N] y
~/.bash_it/lib/helpers.bash: line 488: _bash-it-clean-component-cache: command not found
ag enabled with priority 150.
```
=> Fixes #1309 _bash-it-clean-component-cache: command not found

lib/utilities.bash
Found if this `${cache}` file doesn't exist, the single line conditional command would return false causing a `exit 1`.
This little change makes the conditional verbose and not cause a false return failing the function.
Happens to be related to #1273
=> Fixes early exit if tmp cache is missing

lib/helpers.bash
An ungraceful patch but fixes this one case where the command is singular `alias` while the file is plural with `aliases.
you can now 
```bash
bash-it enable alias all
```
again
=> Fixes #1203 convert alias to aliases

template/bash_profile.template.bash
Bash is run either in interactive mode (e.g. in a terminal) or
non-interactive mode (e.g. on an SSH server handling an SCP request). In
the latter example, any output performed by bash-it's actions will be
interpreted as SCP reply on the client side, typically leading to failed
transfers. This is a well-known limitation of the SCP:
https://bugzilla.redhat.com/show_bug.cgi?id=20527.
In bash's own bashrc example, the first lines of code query for the mode
and return early if it's non-interactive:
http://git.savannah.gnu.org/cgit/bash.git/tree/examples/startup-files/bashrc?h=bash-5.0#n1.
This practice is adopted by Linux distributions (e.g. Ubuntu) and
probably other systems.
Current mode can be queried as described here:
https://www.gnu.org/software/bash/manual/html_node/Is-this-Shell-Intera …
=> template/profile: Require interactive shell

plugins/available/less-pretty-cat.plugin.bash
old approach would override systems cat, which is malicious when used in conjunction with shell piping or redirection
=> turn coloured cat and less into ccat and cless

themes/powerline/powerline.base.bash
Fixes an issue with the SCM widget in `powerline-multiline` when the SCM widget is on the right hand side, shown below.
The issue was that the function `_git-friendly-ref` was escaped inside `${SCM_BRANCH}`, and thus the character count kept to work out how much to move the cursor left to print the right hand prompt was incorrect. This explains why when the branch is `master` below, the offset is worse than when it is `detatched:upstream-master`.
=> Remove escape characters in SCM_BRANCH variable

themes/modern-time/modern-time.theme.bash
It's the modern theme with the battery charge indicator replaced with the current time
```bash
┌─[11:44pm][~]
└─▪
┌─[11:44pm][~]
└─▪ cd workspace/
┌─[11:44pm][workspace]
└─▪ cd bash-it/
┌─[±][modern-time-theme ✓][11:44pm][bash-it]
└─▪ git status
On branch modern-time-theme
Your branch is up to date with 'origin/modern-time-theme'.
nothing to commit, working tree clean
┌─[±][modern-time-theme ✓][11:45pm][bash-it]
└─▪
```
=> Add modern-time theme

completion/available/system.completion.bash
I noticed after switching to `bash-completion@2` that the ones installed by `brew` in `/usr/local/etc/bash_completion.d/` weren't getting loaded. Found [this](https://discourse.brew.sh/t/bash-completion-2-vs-brews-auto-installed-bash-completions/2391/2?u=danemacmillan) reference and updated `system.completion.bash` to set the necessary environment variable for backwards compatibility.
=> adding env var for bash-completion@2 compatibility

themes/base.theme.bash
When current-context does not exist or is unset in $KUBECONFIG, kubectl
is throwing a message to stderr "error: current-context is not set".
Ignore it.
=> Ignore unset and empty Kubernetes context

themes/base.theme.bash
Stop as soon as "svn status" shows a change, not needed to walk through
all the changes in the whole repository. For my large repository this is
about twice as fast.
Extract just the information we need from "svn info"
=> faster subversion status

plugins/available/history.plugin.bash
Exisitence of a tty is not sufficient condition to determine whether a bash session is interactive or not.  Checking if shopts have emacs or vi turned on is a better test.
=> Fixed test of whether or not current session is interactive

themes/base.theme.bash, themes/powerline-plain/powerline-plain.base.bash, themes/powerline-plain/powerline-plain.theme.bash, themes/powerline/powerline.theme.bash
I might be missing something but I couldn't see any function/feature for this, so I've created.
Also, I haven't wanted to use a theme specific var. I thought other themes might want to use this as well.
=> add an env var that themes can save history immediately

.gitignore
In a dotfiles-setup it is handy to track everything in your dotfiles-repo that makes up your environment. In this context `BASH_IT_CUSTOM` is very handy to track every custom plugin/alias/... in your dotfiles-repo. This is not possible for your enabled-plugins/aliases/... in the enabled-dir. This means every environment has to manually enable the plugins/aliases/... you want. There is a way to fix this by making the enabled-dir a symlink to somewhere else.
The enabled-symlink in the root is not ignored by the current .gitignore.
Ignore `/enabled` which fixes the issue.
A better solution would be to have something like `BASH_IT_CUSTOM` but this seems like a fine solution for now.
=> Completely ignore enabled-dir in root to support symlinking

themes/base.theme.bash
When SCM_CHECK is enabled every time you do a command in the terminal it will spawn many `which` processes to check the existence of the SCM executables, this increase the delay of commands on the terminal and CPU/battery usage. This PR make this check more lightweight by checking at startup. This behavior was found by monitoring terminal usage with `forkstat` tool:
```
Time     Event   PID Info   Duration Process
09:18:23 exec  10280                 which git
09:18:23 exit  10280      0   0.002s which git
09:18:23 fork  10279 parent          /bin/bash
09:18:23 fork  10281 child           /bin/bash
09:18:23 fork  10281 parent          /bin/bash
09:18:23 fork  10282 child           /bin/bash
09:18:23 exec  10282                 git rev-parse --is-inside-work-tree
09:18:23 exit  10282 …
```
=> Optimize SCM checks

plugins/available/ssh.plugin.bash
This PR adds a helper function called `ssh-add-all` to add all private identities under `~/.ssh` to ssh authentication agent. Its an extension of `ssh-add` command.
=> Add helper function to add all ssh private keys to agent

plugins/available/node.plugin.bash, plugins/available/pyenv.plugin.bash, plugins/available/rbenv.plugin.bash
Remove error output if plugin is enabled for npm, pyenv, rbenv but the executable is not available.
Useful for keeping the same configs synced across machines that may not have them installed.
=> Remove errors if plugin executable not available

plugins/available/proxy.plugin.bash
NPM has to support proxy exceptions/exclusions. Now proxy command can add/remove/show exclusions for npm too.
=> Added proxy exceptions (noproxy) for npm

themes/clean/clean.theme.bash
https://github.com/Bash-it/bash-it/issues/1422
Removed `\[` and `\]` around `$(scm_prompt_info)`. This created an issue with ghost characters in combination with nvm.
=> Trivial fix for clean theme

plugins/available/less-pretty-cat.plugin.bash
Pygments offers great styles and in dark terminals the default is unsatisfactory.
Use two new env variables BASH_IT_CLESS_STYLE and BASH_IT_CCAT_STYLE to select pygment themes.
Availables styles can be listes using pygmentize -L styles
=> Update less-pretty-cat plugin to support pygment style selection

plugins/available/go.plugin.bash, test/plugins/go.plugin.bats
This PR seeks to simplify the wrapped pathmunge logic setup in #1267.
Tests have been updated to account for cases with spaces in $PATH.
=> Simplify multiple path support in go plugin

themes/ramses/ramses.theme.bash
Based on the [zork](https://github.com/Bash-it/bash-it/blob/master/themes/zork/zork.theme.bash) theme, it separates user info and git status from the pwd and the prompt line.
It also activates vi-mode and tells you if you're in insert mode by showing a small *+* before your prompt, and a long dash otherwise.
Here in insert mode
Here in normal mode and inside a git repo
=> Adds a new vi-mode theme called ramses

themes/powerline-naked/powerline-naked.base.bash
This PR brings in the `LAST_SEGMENT_COLOR` tracking logic from the default theme, resulting in the prompt having the normal background color and the last segment's foreground color.
*before*
*after*
I'm not sure if the "before" result was intended or not, but it felt like an oversight to me, as the stark change in bg color feels like it breaks the `naked` theme's goals for simplicity.
-DF
=> Fixes prompt bg color on powerline naked theme

themes/powerline/powerline.base.bash
Brings the `short` user and hostname variables into the powerline themes.
I use these so I can explicitly set the values in my prompt just as in my terminal title.
-DF
=> Adds SHORT_USER/HOSTNAME support to powerline themes

completion/available/brew.completion.bash
Fix completion/available/brew.completion.bash for the case of installation of brew using the git cloned version.
=> Fix completion/available/brew.completion.bash

completion/available/pip.completion.bash, completion/available/pip3.completion.bash
Use the official suggested method for  pip/pip3 completion described here :
https://pip.pypa.io/en/stable/user_guide/#command-completion
```
Command Completion
pip comes with support for command line completion in bash, zsh and fish.
To setup for bash:
$ pip completion --bash >> ~/.profile
To setup for zsh:
$ pip completion --zsh >> ~/.zprofile
To setup for fish:
$ pip completion --fish > ~/.config/fish/completions/pip.fish
Alternatively, you can use the result of the completion command directly with the eval function of your shell, e.g. by adding the following to your startup file:
eval "`pip completion --bash`"
```
=> Fix the completion for pip/pip3

themes/bira/README.md, themes/bira/bira.theme.bash
This is a port of Oh My Zsh's [Bira](https://github.com/ohmyzsh/ohmyzsh/blob/master/themes/bira.zsh-theme) theme. It looks the same as the original, except for the following changes:
- Exit code of last command is not shown
- More informative git prompt (if you want to keep it minimal, please read: https://github.com/Bash-it/bash-it#git-prompt)
- Position and colour of virtualenv prompt
- No ruby version prompt
=> Bira theme

aliases/available/git.aliases.bash
Add `gprom` and `gpunch` git aliases which are useful for working on large projects where you have to rebase with latest master before creating a PR -- note: would like some thoughts on adding gprom (it might not be a good alias to add since it specifically assumes/references origin as remote and master as the main branch)
=> add gprom and gpunch to git aliases

completion/available/makefile.completion.bash
This PR seeks to enhance the existing support for make completion by searching all 3 possible filenames, and supporting gnumake which is commonly found on macs.
Linted with shellcheck. Tested locally.
I'm on linux today, but will be able to test on Mac next week. If anyone beats me to it and tests on Mac sooner, feel free to post your results.
Thanks.
=> Enhance make completion to support multiple files and gnumake

plugins/available/alias-completion.plugin.bash
This PR provides a fix for #1497, which occurred when alias completion uses the `_filedir_xspec` function from bash-completion which requires the first argument to be the aliased command name.
=> Pass the aliased command as an argument to _filedir_xspec

lib/utilities.bash
This is a fairly petty PR. Just feels cleaner keeping generic and shared functions at the top of the file, since ordering in bash matters.
=> Nit pick ordering

plugins/available/cht-sh.plugin.bash
This PR is a continuation of #1484 which tried to add support as an alias, which wasn't the right fit.
Instead, we add support as a function, `cht.sh`.
We purposely name the function to match the project's [supported cli tool](https://github.com/chubin/cheat.sh#command-line-client-chtsh).
The plugin does nothing if the user has already installed the cli tool.
Tested locally (`GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin18.2.0)`)
-DF
PS: TIL that both alias and function names can have dots in them !
---
cc: @nwinkler , @jrjang, @chubin
=> Add cht.sh plugin

lib/preexec.bash
The semicolon cause some issues in some cases, mainly, when there're several apps modifiying the `PROMPT_COMMAND` variable.
This change is motivated by this [issue](https://github.com/starship/starship/issues/842) in the [Starship](https://github.com/starship/starship) project.
=> Use new line character instead semicolon in the preexec hook

plugins/available/goenv.plugin.bash
This PR adds support for [goenv](https://github.com/syndbg/goenv)
Larger question: What do you think about updating the other env plugins to follow this pattern of checking for the tool before modifying the environment? I already drafted a branch if you're interested :-)
=> Add goenv plugin

themes/powerline/powerline.base.bash
Small change to the powerline theme.
Instead of calling uptime utilize the buildt-in sudo validate. This is just a small change but it should speed up the checks, especially when you have a valid sudo session.
If this is not something you guys would like just close the pull request.
Regards
```
$ time for _ in {1..1000}; do sudo uptime | grep "load" >/dev/null; done
real	0m8.246s
user	0m5.691s
sys	0m4.682s
$ time for _ in {1..1000}; do sudo -vn; done
real	0m4.083s
user	0m2.574s
sys	0m1.579s
$ sudo -k
$ time for _ in {1..1000}; do sudo -vn 2>/dev/null; done
real	0m4.138s
user	0m2.407s
sys	0m1.806s
$ time for _ in {1..1000}; do sudo -n uptime 2>/dev/null | grep "load" >/dev/null; done
real	0m5.855s
user	0m4.617s
sys	0m3.271s
```
```
$ bash --version
GNU bash, version 5.0.16(1)-release …
```
=> Simplified-sudo-check

themes/barbuk/README.md, themes/barbuk/barbuk.theme.bash
Using an ssh session, this theme will now detect and display the user and fqdn to provide clear information about the remote host.
The theme keep the same format but prefix the prompt with `user@hostname`.
Documentation has been updated:
- configuration usage to enable / disable ssh info
- configuration usage to use short or long hostname
- how to configure sudoer to keep the theme when using `sudo -s`.
A script like https://github.com/BarbUk/dotfiles#ssh-connect can be used to synchronise user dotfiles on remote host.
=> Theme barbuk: Add ssh detection and user@host information in ssh session

plugins/available/goenv.plugin.bash
The original version suffers from a few bugs:
* If the user defined `$GOENV_ROOT`, **but** defined it outside of `$HOME/.goenv`, then the script would exit without finding it.
* For path-munging, the script checked for the tool in `$HOME/.goenv` instead of `$GOENV_ROOT` - This would cause the tool to **not** end up on the path if the `$GOENV_ROOT` was defined outside of `$HOME`
* The script would path-munge `$GOENV_ROOT/bin` even if the binary was already on the path (say by using homebrew), causing it now to appear on the path twice, with the `$GOENV_ROOT` version overriding the homebrew version.
=> Fix goenv plugin

aliases/available/git.aliases.bash
Per discussion in #1541, git has deprecated `git stash save` in favor of `git stash push`.
This PR adds aliases to support the push action.
Fixes #1541
---
cc: @finn-matti
=> aliases/git: Add aliases fo git stash push/pop

plugins/available/base.plugin.bash
Out of the box, `curl` reports success (via exit code) even if the
server returns an error, e.g. _429 Too Many Requests_ which was
sometimes the case with `http://myip.dnsomatic.com`. So, errors went
undetected.
There is the `--fail` switch which enables us to use the exit code the
way we need:
> -f, --fail
>        (HTTP) Fail  silently  (no  output  at  all)  on  server
>        errors. This is mostly done to better enable scripts etc
>        to better deal with failed  attempts.  In  normal  cases
>        when  an  HTTP  server  fails  to deliver a document, it
>        returns an HTML document stating so  (which  often  also
>        describes  why  and  more).  This flag will prevent curl
>        from outputting that and return error 22.
Use it to make the `myip()` deliver results …
=> plugins/base: Detect HTTP errors in `myip()`

test/plugins/base.plugin.bats
Test of `myip` was skipped, allegedly for it being slow. It's fast for
me (60 ms), so enable it unconditionally.
=> Run `myip` test

test/test_helper.bash
Git uses system-wide and user-wide configurations per default and these
can interfere with our tests. Keep `git` from using them by setting the
according environment variables.
This might also help with other tools which access user's home
directory.
In my case, I had issues because I turned on commit signing per default  and some of the tests try to make commits and fail because they PGP key is pin-protected.
=> test/test_helper.bash: Don't use system/user `git` config

test/plugins/go.plugin.bats
In case `go` is not installed, tests of the according plugin fail. It's
better to just skip them since `golang` isn't commonly installed on
`bash-it` developers' machines.
In CI environment, no tests should be skipped, so run them anyway.
=> test/plugins/go: Skip tests in absence of `go`

aliases/available/kubectl.aliases.bash, aliases/available/uuidgen.aliases.bash
My bad.  macOS uses `uuidgen` and produces upper case by default.  Linux uses `uuid` (if installed) and produces lower case by default.
This fixes it for `uuidgen.bash` & `kubectl.bash`.
=> fix: uuid behavior for linux

.gitmodules
Inspired by @rico-chet's PR #1555, I looked into updating the other Bats test libraries to their latest versions:
* `bats-support`: Updated the remote and pointing to `v0.3.0` tag (no changes)
* `bats-assert`: Updated the remote and pointing to `v2.0.0` tag, validated migration changes (no changes required): https://github.com/bats-core/bats-assert/wiki/Migrating-from-v1.1.1
As a next step, I will look into updating bats-core as outlined by @rico-chet in #1555 
@rico-chet Does this look reasonable?
=> Update Bats libs "assert" and "support"

.gitmodules, test/plugins/base.plugin.bats
Had to adjust one test case since the semantics of `assert_file_exist` have changed.
CC @rico-chet
=> Updated bats-file to https://github.com/tralston/bats-file v0.3.0

.editorconfig
Configuration files of `git` are managed by the tool and thus are
tab-indented. If a developer happens to edit such a file manually, the
indentation would become inconsistent.
Add an explicit section for such files and set the indentation to tabs.
=> editorconfig: Add `.git*` section

completion/available/git.completion.bash
Although not documented in the completion script, it finally occurred to me that maybe @trmaphi didn't write this completion script, but integrated an existing one.
A quick search confirmed that the script was (likely) sourced from the official git repo's contrib folder:
* [github.com/git/git/contrib/completion/git-completion.bash](https://github.com/git/git/blob/master/contrib/completion/git-completion.bash)
[edit] A not-so-quick search confirmed that the existing completion file exactly matches the file from the `v2.21.0` release of git.
I simply pulled the completion script from the latest official release : 
* https://github.com/git/git/releases/tag/v2.26.2
I also added a small section at the top of script explaining the version and the source:
```
```
First, a version of that same …
=> completion/git: Updates completion script to v2.26.2

plugins/available/extract.plugin.bash
added tar extract-directory creation and usage
(also removal of unnecessary recursion where appropriate)
positive side-effect:
- no lingering *.tar file when exracting a *.tgz/*.tar.xz/... or similar
- it now behaves like uncompressing *.zip or *.7z: the archive file remains as-is and is extracted in a new directory with the name of the archive (without suffix) in the same directory as the archive
=> added tar extract-directory creation and usage

aliases/available/git.aliases.bash
Fixes https://github.com/Bash-it/bash-it/issues/1498
`gh` was for `git home` so I am renaming it `ghm`
=> Check gh command exists before setting git gh alias

plugins/available/aws.plugin.bash
Minor fix to address cases where there is no aws_session_token set. Checked the docs and only saw these three values are supported in the credentials file.
=> fix for issue #1418

.travis.yml
It's easier to read a long job list when the jobs are named.
Reference:
https://docs.travis-ci.com/user/build-stages/#naming-your-jobs-within-build-stages
=> travis: Give jobs names

test/lib/search.bats
Had to move the `cite` definition up a couple of lines, since `_about`
is used in some of the tested plugins
Fixes #1582
=> Fix search plugin tests

plugins/available/sshagent.plugin.bash
This case can be safely ignored, no need to print a message for that.
Fixes #1579
=> Remove echo when a dead SSH Agent PID is found

aliases/available/bash_it.aliases.bash, aliases/available/bashit.aliases.bash, aliases/available/general.aliases.bash
I think that the **general** aliases are not the same for every user: if someone does not want some **general** alias, but still needs the _bash_it_ command, is then forced to remove it manually. With these changes bash_it aliases gets separated from the general ones, so that the user can choose what to use.
=> Separate bashit alias from general

README.md
=> Update build badge link to travis-ci.com

test/bash_it/bash_it.bats, test/test_helper.bash
For bulk copying, `rsync` is used in test code, which is rather fast and
capable of saving needless write operations. The downside is that tests
fail when the tool is missing, which is the case with most minimal Linux
setups (e.g. containers or even Gnome installations of Debian).
Provide an alternative way for sufficiently fast copying by means of
`find -exec cp`. Measured total test time penalty is less than 0.5%.
Downside of needless write operations remains in case of fallback.
=> test: Make `rsync` optional

themes/robbyrussell/robbyrussell.theme.bash
This pull request adds the robbyrussell-theme to bash-it. robbyrussell is the default theme for oh-my-zsh.
This pull request replaces the abandoned https://github.com/Bash-it/bash-it/pull/329. Once this is merged https://github.com/Bash-it/bash-it/pull/329 can be closed, too. This is pretty much an exact copy of https://github.com/Bash-it/bash-it/pull/329, with just colors fixed.
=> add robbyrussell theme

plugins/available/fasd.plugin.bash
This PR seeks to add support for [`fasd`](https://github.com/clvv/fasd).
In case anyone is wondering why I chose `auto`, it's because I think `fasd` does a fine job of detecting bash, and I don't want to maintain any parity changes if they change defaults upstream. For posterity, here is a copy of the current output from `init`
```
$ fasd --init auto
{ if [ "$ZSH_VERSION" ] && compctl; then # zsh
eval "$(fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install \
zsh-wcomp zsh-wcomp-install)"
elif [ "$BASH_VERSION" ] && complete; then # bash
eval "$(fasd --init posix-alias bash-hook bash-ccomp bash-ccomp-install)"
else # posix shell
eval "$(fasd --init posix-alias posix-hook)"
fi
} >> "/dev/null" 2>&1
```
=> Add fasd plugin

plugins/available/fasd.plugin.bash
This PR fixes two mistakes I made in #1602:
1) when checking for a command `||` should be use to silence the non-0 exits
2) `fasd`s `--init` output needs to be wrapped in quotes, as is documented in their readme :man_facepalming:
My bad y'all!
Fixes #1605
=> use || to silence exit 1 properly and quote fasd init

plugins/available/xterm.plugin.bash
Fix issue: when using pushd/popd, the terminal title remains at the original location because, from `man bash`:
dirs [-clpv] [+n] [-n]
...
+n     Displays the nth entry counting from the left of the list shown by dirs ...
-n     Displays the nth entry counting from the right of the list shown by dirs ...
=> Fix _short-dirname

themes/base.theme.bash
Fixes #1612 
Fixes #914 
Can you please validate that this fixes the slowness, @arturmartins?
This should detect the broken `svn` command when you open a new shell or run `bash-it reload`.
=> Add check for broken XCode SVN command

DEVELOPMENT.md, bash_it.sh, lib/appearance.bash, lib/helpers.bash, lib/log.bash, lib/utilities.bash, scripts/reloader.bash, test/lib/helpers.bats, test/lib/log.bats, test/themes/base.theme.bats, test/themes/base.theme.git.bats, test/themes/base.theme.svn.bats
Continuation of #1501
Also add prefix option for the logs, not by a stack, but rather by a variable set by the owning file
TODO:
=> Add load/reloader logs

plugins/available/node.plugin.bash
`nodenv` manages executable location through "shims", and these can conflict with the normal way one would configure their workspace. This addresses that. Thanks!
=> Ensure node plugin plays nice with nodenv

completion/available/projects.completion.bash, plugins/available/projects.plugin.bash
For systems without bash-completion >= 2, `projects` were erroring out. This now uses the doctor command to at least tell the user what they can do.
=> Projects logging

plugins/available/jenv.plugin.bash
This translates the pattern set in `go.plugin.bash` to `jenv`.
=> clean up jenv to follow the newer pattern

completion/available/git.completion.bash
This was always failing on macOS instead of working there...
See #1635 for the original commit that introduced this issue. We somehow missed this, @cornfeedhobo...
=> Fixed OS comparison for macOS

lib/helpers.bash
This PR allows the caller to pass a custom log message when the command is not found.
I considered a few other approaches, so I'm open to opinions, but this seems easy enough.
Example use case:
```bash
! _command_exists \
"pyenv virtualenv --help" \
"pyenv plugin 'virtualenv' is not installed - skipping" ||
eval "$(pyenv virtualenv-init - bash)"
```
```bash
$ bash-it doctor
...
WARN: plugin: pyenv: pyenv plugin 'virtualenv' is not installed - skipping
...
```
=> _command_exists - custom log message

themes/robbyrussell/robbyrussell.theme.bash
A fix to align with robbyrussell theme of zsh, which the command line is not bold, just the theme by itself.
=> [robbyrussell theme] Cleaning up bold markup after theme

plugins/available/gitstatus.plugin.bash
I think we should gradually see (and encourage) more PR's like this, which in the long run will ensure there are many logs throughout `bash-it`
=> gitstatus: Add informative warning in case dir is not found

themes/base.theme.bash
hexdump by default will replace any repeated groups with an asterisk and
a newline, which breaks prompts. This can be disabled with the `-v`
flag. For example:
```
printf 'aac' | hexdump -e '1/1 "%02x"'
61*
63
printf 'abc' | hexdump -e '1/1 "%02x"'
616263
printf 'aac' | hexdump -ve '1/1 "%02x"'
616163
```
=> hg SCM_CHANGE: prevent hexdump squeezing

completion/available/brew.completion.bash, completion/available/crystal.completion.bash, completion/available/system.completion.bash, test/lib/helpers.bats
This was inspired from the conversation over at #1635
- Prefer the brew/bash provided wrapper (`/usr/local/etc/profile.d/bash-completion.sh`) when loading `bash-completion@2`
- Remove completions that should be utilizing `system` and notify the user through `doctor`
=> System completion nitpick

themes/barbuk/barbuk.theme.bash
Fix for #1660.
Currently the barbuk theme doesn't show the activated python virtual environment in the prompt.
This PR uses modified code from the powerline theme to add that functionality.
=> Detect python venv and show in prompt

test/lib/helpers.bats
On trying to run the tests locally, the `@test "helpers: _command_exists function exists"` failed with the following:
```bash
✗ helpers: _command_exists function exists
(from function `_command_exists' in file test/lib/../../lib/helpers.bash, line 26,
in test file test/lib/helpers.bats, line 24)
`_command_exists &> /dev/null' failed
..../bats-assert/src/assert_success.bash: line 33: output: parameter not set
```
Upon examining the `test/lib/helpers.bats` file I found that the bats `run` was missing.
> Bats includes a run helper that invokes its arguments as a command, saves the exit status and output into special global variables, and then returns with a 0 status code so you can continue to make assertions in your test case.
=> Fix the _command_exists function exists test use case

themes/bobby-python/bobby-python.theme.bash, themes/bobby/bobby.theme.bash
This PR attempts to make the `bobby` and `bobby-python` themes slightly more readable by breaking up PS1 into its individual components. I tested the proposed changes locally and can confirm they don't alter the appearance of the themes.
Edit: Just realized after opening the PR that I had forgotten to create a feature branch on my fork and used master directly. Happy to open a new PR with a feature branch instead. Just let me know.
=> Make bobby and bobby-python themes more readable

lib/helpers.bash
Closes #1665
We need to think about when we fully reset the shell, as this is a useful behavior, just not when auto reloading on add/disable of plugin
=> helpers: Auto reload now only reloads and not reset the shell

completion/available/bash-it.completion.bash, lib/helpers.bash, test/completion/bash-it.completion.bats
This command will re exec the shell, yet `cd` to the prev `pwd`
I briefly floated the idea in https://github.com/Bash-it/bash-it/issues/1665#issuecomment-706459916
I still did not test this on Mac, and also I could not enable the `--login` option, as I wanted to run command after shell initialization. @ahmadassaf could you please test this and tell me if this works on Mac?
=> Add bash-it restart command

README.md, completion/available/bash-it.completion.bash, lib/helpers.bash, template/bash_profile.template.bash, test/completion/bash-it.completion.bats
Part of solution for #1500
we will need to push a tag someday :smile:
=> bash-it update to stable or dev 

lib/helpers.bash
As we now have "stable" releases and "dev" type of versions, `version` command should
provide usefull output on that
=> Improve bash-it version output

clean_files.txt, themes/90210/90210.theme.bash
This is an example of how the newly pre-commit cleaning process should go.
I took a file from the repo, added to clean_files.txt, ran `pre-commit run --files `cat clean_files.txt` and fixed the errors﻿
=> Clean 90210 theme

.readthedocs.yml, .travis.yml, docs/Makefile, docs/commands/doctor.rst, docs/commands/index.rst, docs/commands/reload.rst, docs/commands/search.rst, docs/commands/update.rst, docs/conf.py, docs/contributing.rst, docs/custom.rst, docs/development.rst, docs/index.rst, docs/installation.rst, docs/make.bat, docs/misc.rst, docs/requirements.txt, docs/test.rst, docs/themes.rst, docs/uninstalling.rst, docs/vcs_user.rst
Part of #1680 
I moved large parts of the documentation to `.rst` format, ready to be deployed to [readthedocs](https://readthedocs.org/)
[Here](https://my-bash-it.readthedocs.io/en/docs/) is a working example, based on my imported fork.
Some notes
- I did not change the documentation, only moved it to `rst` format.
- Some commands are still do not have docs (as I only ported the docs)
- We can now use auto-generation of some kind in order to generate some of the command docs
- In the [theme contribution docs](https://my-bash-it.readthedocs.io/en/docs/contributing/#contributing-theme) it is still suggested to update the wiki and create a `README.md`. We would want to move away from those solutions
- <del>There is no CI stage currently to check if the docs compile, and there should be one …
=> Basic ReadTheDocs

.travis.yml, clean_files.txt, lint_clean_files.sh
Moves the lint logic from `.travis.yml` into `lint_clean_files.sh`, updating travis to use it.
(open to a better name for the shell script)
This makes it easier to run the lint checks manually.
I added `lint_clean_files.sh` itself to `clean_files.txt` and fixed warnings accordingly.
Other than lint warnings/fixes, this PR contains the minimal changes for moving the lint check into a separate file.
I will save the addition of directory/comment support for a separate PR.
---
@NoahGorny you still around today?
=> Moves lint logic into lint_clean_files.sh

clean_files.txt, lint_clean_files.sh, themes/powerline/powerline.base.bash, themes/powerline/powerline.theme.bash
_lint_clean_files.sh_
```
mapfile -t FILES < <(
cat clean_files.txt \
| grep -v -E '^\s*$' \
| grep -v -E '^\s*#' \
| xargs -n1 -I{} find "{}" -type f
)
BASH_IT='' pre-commit run --files "${FILES[@]}"
```
To test the directory support, we add `themes/powerline` to the file.
This PR incorporates all the auto-fixes and recommended changes resulting from executing the pre-commit command locally:
```
BASH_IT='' pre-commit run --files $(cat clean_files.txt | xargs -n1 -I{} find {} -type f);
```
NOTE: Using the `"Hide whitespace changes"` features on the `"Files Changed"` tab will make the PR much easier to review.
[edit] Updated local pre-commit run to include prefix `BASH_IT=''` which is needed to suss out source includes that need a `"# shellcheck source"` directive.
=> Clean Powerline; Add Dir Support to Clean_Files

.pre-commit-config.yaml
Now that #1698 is merged, the lint checks `docs/_build` folder, which is unnecessary﻿
=> pre-commit: Exclude docs _build folder

docs/installation.rst, install.sh, test/install/install.bats
My first draft for the option to append template to existing config file in silent mode.
Closes #1720
=> Add option to append template to existing config

.github/PULL_REQUEST_TEMPLATE.md
Adding a issue and PR templates will help newcomers understand how to contribute to Bash it
I felt like having no template is leaving the repo a bit unorganized, and felt its an appropriate change.
=> github: Add pr template

.editorconfig, .gitattributes, .pre-commit-config.yaml, docs/README.md
This will help newcomers, and not confuse them by redirecting them to
another site instantly. @cornfeedhobo I think you will like this :)
=> docs: Add simple installation instructions to readme

plugins/available/alias-completion.plugin.bash, test/plugins/alias-completion.plugin.bats
=> Use command rm in alias_completion

aliases/available/vim.aliases.bash, clean_files.txt
I don't use it very often and am fine with not putting it in, but worth pushing it out there
=> feat(vim-alias): add full screen help

.editorconfig
- fix wildcards to include nested files (see the [format docs](http://docs.editorconfig.org/en/master/editorconfig-format.html#patterns))
- include `test/run` in the bash section
- I noticed that my personal editorconfig was taking over because the wildcards
- I'm playing around with a new approach to running tests, and noticed `test/run` not respecting editorconfig styles
Locally
=> Editorconfig fixes

clean_files.txt, themes/barbuk/barbuk.theme.bash
Add barbuk theme to `clean_files.txt`.
shfmt lint only.
=> Clean barbuk theme

completion/available/sdkman.completion.bash
The sdkman CLI added new commands, command aliases, and changed some output formats. This pull request adapts the completion script to support such changes. These were all tested using sdkman `5.9.1`, but I suspect most of them were present in recent previous versions.
Properly support newer versions of sdkman.
I've tested locally using sdkman `5.9.1` and with the following bash version:
```
GNU bash, version 5.1.0(1)-release (x86_64-apple-darwin20.1.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
Tested all the commands and validated that they are all working.
It is a breaking change …
=> Add support to newer versions of sdkman

clean_files.txt, themes/agnoster/agnoster.theme.bash
After #1694
Cleaning up agnoster theme, works after my cleanup
=> clean agnoster theme

.github/workflows/ci.yml
I am removing the macos-11 runner as it is crashing and causing us trouble
Removed the runner from our ci.yml, to address the runner issues
This runner really caused us trouble by delaying builds and failing sometimes
=> ci: Remove macos-11.0 as it is unreliable

.pre-commit-config.yaml, aliases/available/vim.aliases.bash, clean_files.txt, completion/available/cargo.completion.bash, completion/available/knife.completion.bash, completion/available/packer.completion.bash, completion/available/pipx.completion.bash, completion/available/rustup.completion.bash, completion/available/sdkman.completion.bash, completion/available/vault.completion.bash, hooks/dot-bash.sh, hooks/dot-sh.sh, plugins/available/basher.plugin.bash, themes/90210/90210.theme.bash, themes/agnoster/agnoster.theme.bash, themes/barbuk/barbuk.theme.bash, themes/powerline/powerline.base.bash, themes/powerline/powerline.theme.bash
Adds local pre-commit hooks to check `.sh` and `.bash` files for *proper* headers and executable flags.
Introduces a `hooks/` folder on root to act as a home for custom pre-commit hooks.
Adds a `local` repo to `".pre-commit-config.yaml"`
Adds the `dot-sh` hook to check `.sh` files against bash-it requirements:
* Proper `#!` header
* File is executable
_file.sh_ header:
```
#!/usr/bin/env bash
```
Adds the `dot-bash` hook to check `.bash` files against bash-it requirements:
* Proper `#!` header
* Proper `shellcheck` header
* File is NOT executable
_file.bash_ header:
```
#!/usr/bin/env echo run from bash: .
```
Once the hooks were activated, some existing `.bash` files from `"clean_files.txt"` triggered errors.
This PR also includes fixes to those few files.
Intended to help enforce …
=> Add hooks to check .sh and .bash headers - Fixes #1491

aliases/available/git.aliases.bash, clean_files.txt
- move all comments to the same line so they wont be jumbled
=> refactor(aliases): sort

completion/available/sdkman.completion.bash
sdkman has a specific output format for Java candidate since
there are multiple vendors and builds. For example, when running
`sdk list maven`, the format is a simple list like:
3.6.2
3.6.1
3.6.0
3.5.4
3.5.3
3.5.2
3.5.0
3.3.9
But for `sbt list java`, the output is a table like:
================================================================================
Vendor        | Use | Version      | Dist    | Status     | Identifier
--------------------------------------------------------------------------------
AdoptOpenJDK  |     | 15.0.1.j9    | adpt    |            | 15.0.1.j9-adpt
|     | 15.0.1.hs    | adpt    | installed  | 15.0.1.hs-adpt
...
Amazon        |     | 15.0.1       | amzn    |            | 15.0.1-amzn
|     | 11.0.9       | amzn    |            | 11.0.9-amzn
...
Azul Zulu …
=> Support multiple sdkman output formats

clean_files.txt, themes/base.theme.bash
Review with [?w=1](https://github.com/Bash-it/bash-it/pull/1785/files?w=1).
- Add themes/base.theme.bash to clean files
- Run code fomatter for themes/base.theme.bash
- Fix shellcheck warnings for themes/base.theme.bash
- Fix shellcheck header script to consider multiple lines
I've picked this file because it is the file with most changes (commits, at least) based on:
git log --name-only --pretty="format:" | grep -v -e "^[[:space:]]*$" | sort | uniq -c | sort
I thought about adding other files, but that would probably make it harder to review.
Besides running the bats tests locally, I've manually tested that the most significant in isolation (checking they are resulting in the same effect as before).
=> Add themes/base.theme.bash to clean files

clean_files.txt, themes/atomic/atomic.theme.bash, themes/axin/axin.theme.bash
- axin theme was just linted
- atomic theme needed an update of the args parsing in internal function to be compliant with shellcheck:
```bash
args=($1)
```
become
```bash
read -r -a args <<< "$@"
```
https://github.com/Bash-it/bash-it/issues/1696
Tested both theme by using before and after the update
=> Clean atomic and axin theme

aliases/available/clipboard.aliases.bash
Added shortcut for xclip commands
The complete command is lengthy
Check screenshots
=> added alias for xclip command

themes/base.theme.bash
Fix a typo in rbenv_version_prompt function.
When using `rbenv_version_prompt` to display ruby version
with rbenv installed, there is an error:
```bash
bash: 2.7.2: command not found
87% 2021-01-16 09:24:20 ⌚  |2.7.2| ThinkbUk in ~
○ →
```
The function define a variable containing the ruby version with `rbenv version-name`
and use that variable like the `rbenv` binary.
`rbenv commands | grep -q gemset` is a valid command when using [rbenv gemset](https://github.com/jf/rbenv-gemset).
No error after modification.
Using rbenv-gemset display the gemset used.
=> Fix rbenv version prompt

clean_files.txt, themes/atomic/atomic.theme.bash, themes/bakke/bakke.theme.bash, themes/binaryanomaly/binaryanomaly.theme.bash, themes/bira/bira.theme.bash, themes/bobby-python/bobby-python.theme.bash, themes/bobby/bobby.theme.bash, themes/brainy/brainy.theme.bash, themes/brunton/brunton.theme.bash
Clean and lint b* themes
https://github.com/Bash-it/bash-it/issues/1696
Tested all themes before and after changes.
1 error was detected, resulting in an other PR: https://github.com/Bash-it/bash-it/pull/1789
=> Clean b* themes

clean_files.txt, themes/modern/modern.theme.bash
Lint and cleanup for the `modern.theme.bash` | PR: #1812
Ran the `lint_clean_files.sh`
One issue arised, which i asked input for, on line 49
=> Cleanup for modern theme

test/test_helper.bash
Stumbled across this when I fixed a test in #1776
Internal composure `cite`s are missing from the tests, this causes some confusing and misleading errors when
loading bash-it files which uses those `cites`
This was pretty annoying, and I am happy to improve our tests
locally
=> test: helper: cite plumbing metadata

scripts/reloader.bash
This PR stops changing directories while reloading, which I'm calling a bug because it is completely different from my expectations and caused a lot of debugging confusion. I'm also labeling this as help-wanted because I'd like some people to test this manually since we don't really have integration tests yet, but I'm feeling pretty good about it.
While playing around with the *env plugins, I discovered that if I started a fresh shell from a directory with a `.*-version` file, the tools were still unable to figure out the set version, because we are changing the working directory while loading.
locally and with bats
=> use absolute paths instead of changing directory

vendor/github.com/erichs/composure/LICENSE, vendor/github.com/erichs/composure/README.md, vendor/github.com/erichs/composure/composure.plugin.zsh, vendor/github.com/erichs/composure/composure.sh
Points `composure` at the newest commit because they don't push tags anymore
fixes #1827 
locally
=> Composure bump

clean_files.txt, plugins/available/go.plugin.bash, plugins/available/goenv.plugin.bash, test/plugins/go.plugin.bats
This PR seeks to address several issues surrounding the go and goenv plugins.
The nature of goenv allows for a situation where the initial shell does not
point to a working go binary, and instead at the included shim script. The
result is that one must run reload after moving to a project directory with a
version file, however in doing so, PATH is updated, requiring they exit the
shell or risk lookup collisions and unexpected behavior.
This is solved by using preexec to check the version before changing
directories and restarting the shell if the version has changed. The exec
pattern is copied from _bash-it-restart, but is edited to support this specific
use case.
Additionally, tests have been updated and these are now being linted.
manually and locally. opening up for discussion while I …
=> Ensure goenv and go play together well

install.sh
- install: Move modify config check into separate function
- install: Move backup check into a separate function
- install: Add --overwrite-backup flag
Cleans up the config backup logic and split it into smaller functions.
Also add a new flag which allows us to overwrite backups silently (previously we did not check for existing backups in silent installations). This does change the default behaviour, so I am open to a debate on that.
#1829 prompted me to take a look- and I indeed saw a problem. I refactored the code a bit in order to fix this.
Closes #1829 
Locally, tested various flags and combinations, with and without backup. Works as expected.
As I said, now silent installations fail if a backup is already present, unless "-f/--overwrite-backup" is specified
=> simplify install

clean_files.txt, completion/available/composer.completion.bash
Cleanup composer completion as part of #1782
=> formatted composer completion and used helper function

aliases/available/kubectl.aliases.bash
It now defaults to pod, so the --generator option is not required.
--generator will be removed in a future kubectl update
Running the command starts a pod, like intended
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have read the **CONTRIBUTING** document.
=> Remove deprecated kubectl run --generator

aliases/available/systemd.aliases.bash
Refactor naming
Add restart
Systemd Aliases don't include restart.
I converted naming to be postfix-oriented.
As restart-daemon is always restart, then "r" is not semantic, I changed it to "d" for daemon.
Better naming. Adds restart.
Manually via aliases I use in my Arch.
=> Improved systemd aliases

aliases/available/git.aliases.bash
- I have not updated my bashit in a while so this alias broke for me recently. Included are some screenshots of what I am seeing. 
The alias is broken in bash `version 5.1.4(1)-release`
- see below
=> fix: Git alias quote style broke functionality

lib/helpers.bash, test/lib/helpers.bats
Fix some broken things after the vendoring of the composure lib (#1820)
`bash-it help *` was broken after the vendoring change. This PR fixes that
Closes #1846
Locally and added a test
=> helpers: Fix broken compoure references after vendor change

clean_files.txt, themes/purity/purity.theme.bash
Added a function to show the name of the python virtualenv, when its being used.
I consider having the name of the virtual environment we're in very useful.
Entering and leaving a virtualenv has the desired behaviour.
[Demo](https://imgur.com/qS2tvca)
=> purity theme, added virtualenv name display

plugins/available/extract.plugin.bash
Update extract plugin, zip extraction should be put into sub directory
1. Extract zip to target directory
2. Extract C# package (.nupkg) as zip
3. Extract 7zip to directory
Put zip to sub directory no current directory.
Tested on local Ubuntu 20.04
=> Update extract.plugin.bash, extract compressed file to target directory

clean_files.txt, plugins/available/alias-completion.plugin.bash
Add these files to `clean_files.txt`
`plugins/available/alias-completion.plugin.bash`
`test/plugins/available/alias-completion.plugin.bats`
ran `./lint_clean_files.sh` and fix errors.
=> Clean alias completion plugin

.pre-commit-config.yaml, clean_files.txt, hooks/check-clean-files-txt.sh
We now sort clean_files.txt alphabetically!
Added a hook that checks that the lines in clean_files.txt are sorted alphabetically.
I have splitted the checks into 3 parts- root files, root directories, and non root directories
I also sorted clean_files.txt according to said feedback :smile:
Closes #1871
Locally, by runnnig `lint_clean_files.sh`
=> Add clean_files.txt sorting hook

plugins/available/alias-completion.plugin.bash
Fix read command in alias-completion plugin
In our lint process of alias-completion, we changed a "read" command to use the "-r" flag.
https://github.com/Bash-it/bash-it/blob/7b8dbd39bc821a5be25043375920823fd168e6ea/plugins/available/alias-completion.plugin.bash#L52
This broke the completion, so we revert this change
Broken plugin after
Locally
=> plugins: alias-completion: Revert back to read without -r

plugins/available/alias-completion.plugin.bash
So, after having issues with alias-completion again, I re investigated and found out the correct fix
The completion comparison to the alias should not be regex at all, it should be literal check
Local bug in alias-completion
Locally, but better
I will add a test to combat the bugs here
=> plugins: Fix alias-completion by comparing completions to alias literally

.pre-commit-config.yaml
done in the beginning because of build issues, but was solved during the work on #1897
=> chore(pre-commit): bump version

docs/README.md
Change up chat networks
Freenode changed owners and governance and as a result there has been a mass exodus to Libera.Chat. This includes other big names like KDE, Ubuntu, Debian, and many others.
=> move to Libera.Chat

clean_files.txt, themes/base.theme.bash, themes/binaryanomaly/binaryanomaly.theme.bash, themes/brunton/brunton.theme.bash, themes/codeword/codeword.theme.bash, themes/doubletime/doubletime.theme.bash, themes/gallifrey/gallifrey.theme.bash, themes/mairan/mairan.theme.bash, themes/modern-t/modern-t.theme.bash, themes/modern-time/modern-time.theme.bash, themes/modern/modern.theme.bash, themes/pure/pure.theme.bash, themes/ramses/ramses.theme.bash, themes/rjorgenson/rjorgenson.theme.bash, themes/slick/slick.theme.bash, themes/zork/zork.theme.bash
Lint "pure" theme, and refactor `scm_prompt` usage in themes, which used copied code instead of a centralised location
Problems I encountered during debugging of https://github.com/akinomyoga/ble.sh/issues/110 prompted me to fix the theme.
Locally
=> Refactor scm_prompt usage in many themes

clean_files.txt, completion/available/dart.completion.bash
=> Added completion for dart cli

completion/available/defaults.completion.bash
=> Fixed defaults autocompletion.

completion/available/brew.completion.bash, completion/available/fabric.completion.bash, completion/available/git.completion.bash, lib/helpers.bash, plugins/available/base.plugin.bash, plugins/available/boot2docker.plugin.bash, plugins/available/osx.plugin.bash, plugins/available/python.plugin.bash, themes/demula/demula.theme.bash, themes/rana/rana.theme.bash
The only use case for invoking the `uname` binary in our usage is to find out if we're on Darwin or Linux or whatnot. `$OSTYPE` is a shell builtin constant that tells us this, so use it.
I'm on a bit of a crusade to reduce launching external programs and to make use of constants and features already provided by Bash. This is _Bash It_, after all!
More of an *optimization* than a fix...
=> Don't call external `uname` when `$OSTYPE` will do

.editorconfig
`indent_size` should be set to `tab`, and `tab_width` should be set to the desired indentation distance. However, `tab_width` is a deeply personal religious conviction and should not be set by a shared community project.
It's possible someone forces `tab_width` to 8 and then their editor may half-tab by using spaces of `indent_size`...which is somehow worse than always using tabs or always using spaces...
I've never used `.editorconfig` before, but I installed the TextMate plugin.
=> Don't set `indent_size` when using tabs

completion/available/defaults.completion.bash
Also fix a small bug along the way :)
Revert back to straight comparison instead of regex one
Mistakenly added in #1913
I want to say that this file is seemingly broken in many ways already, so I did not bother fixing all of the other stuff
that did not work..
Locally
=> defaults: Revert to old comparison

lib/helpers.bash
Correctly restore old pwd in all cases of bash-it update
When we update, we usually call `bash-it restart`, which re-execs bash. It means that the code of restoring
old pwd at the end is not being executed. I fixed this and another problem by correctly `cd`ing into to old pwd in time.
Closes #1920
Locally, sadly it is very hard to automate testing of bash-it update, as it uses actual git repo and tries to pull information.
=> fix update not popping back cwd

bash_it.sh, completion/available/system.completion.bash, lib/helpers.bash, lib/log.bash, lib/preview.bash, lib/utilities.bash, plugins/available/base.plugin.bash, test/lib/log.bats
Expressly handle parameter values as empty when the parameter is not set at all, instead of letting comparisons fail for missing arguments. Change $BASH_PREVIEW to "${BASH_PREVIEW:-}" and similar for $BASH_IT_LOG_PREFIX, $BASH_IT_LOG_LEVEL, &c. This helps towards #1696.
This reduces errors by explicitly testing for blank values rather than silent syntax errors. I'm very careful about what code I allow to run, and I use `set -u` to ensure that I'm not inadvertently confusing an edge-case when scripting. There's a lot of unbound variables here.
This is my live branch in use on my own system now.
=> Gracefully handle unbound parameters

completion/available/system.completion.bash
On Mac OS X, where _Bash_ as shipped is version 3.2, support loading _Bash Completion_ version 1 or version 2 from [Homebrew](https://brew.sh) based on the version of the _Bash_ shell in operation. E.g., if we're running _Bash_ v4+, then source _Bash Completion_ from /usr/local/opt/bash-completion@2/etc/profile.d/bash_completion.sh, but if we're running the built-in _Bash_ v3.2, then source from /usr/local/opt/bash-completion@1/etc/bash_completion.
I want to install _Bash_ from [Homebrew], but I alsö don't want to.
Tested locally and CI passes.
...more of an optimization...
=> Support multiple versions of _Bash Completion_

plugins/available/alias-completion.plugin.bash, plugins/available/git.plugin.bash
For some reason, running `lint_clean_files.sh` locally resulted in some errors for me, although it is ran on every PR...
Fix small shellcheck quoting warnings
Clears up `lint_clean_files.sh` to not error out
lint ran, tests as well
=> plugins: Fix shellcheck warnings on already linted files

.editorconfig
Despite `indent_size` being set to `tab` by default, it turns out that we set `indent_size` to `2` for `*` at the top of this file. So, for everywhere else, explicitly set `indent_size` to the default (`tab`). This should achieve the goal of my last patch to `.editorconfig`.
Linters and formatters are good; they make tedium easy. But, they need to be configured properly and it was my PR that removed the explicit `indent_size=4`.
This PR makes *no* formatting changes; just fixes my previous patch.
[EditorConfig.org]( https://editorconfig.org/ ):
> indent_style: set to tab or space to use hard tabs or soft tabs respectively.
> indent_size: a whole number defining the number of columns used for each indentation level and the width of soft tabs (when supported). When set to tab, the value of …
=> EditorConfig: set `indent_size = tab`

test/themes/base.theme.svn.bats, themes/base.theme.bash
If we are specifically in the situation #1612 (where Xcode's `xcrun` is masquerading as `svn`), then check for a working `svn` command. If we're not in that situation, then don't waste time on it. This check was added in #1613.
This is one of the causes of my shell taking several seconds to start.
Tested locally.
=> themes/base: don't invoke svn if possible

install.sh, lib/helpers.bash, lib/utilities.bash, plugins/available/jekyll.plugin.bash, plugins/available/osx-timemachine.plugin.bash, plugins/available/virtualenv.plugin.bash, plugins/available/z_autoenv.plugin.bash
Reduce subshells and external commands by using _Bash_'s string processing features instead of `dirname` and `basename`. This basically uses `$PWD`, `$BASH_SOURCE`, and "${pathname%*/}" and similar constructs to avoid subshells for `$(pwd)`, `dirname`, and `basename`. 
This is part of a set of patches to reduce usage of subshells and external binaries in _Bash It_.
The two commits here were part of #1914, but that PR went further than this one and some edge cases were identified which could lead to unintended behavior so those uses were left as-is. Both commits here operate specifically on code which specifies the full path within the same function and thus won't run in to possible issues with user-supplied strings. Merging this PR resolves #1914.
The two edge-cases are: 
1. too many `/`, …
=> Use parameter substitution instead of `dirname`/`basename`, where safe to do so

completion/available/gradle.completion.bash, completion/available/hub.completion.bash, lib/helpers.bash, plugins/available/dirs.plugin.bash, test/plugins/base.plugin.bats, test/run, themes/powerturk/powerturk.theme.bash
NOTE: This PR assumes that my `basenamed` branch has already been merged (#1926)! This PR does not do anything with `basename`/`dirname`; it's just based off that branch.
_Bash_ maintains the `$PWD` shell parameter with the current and correct full path to the present working directory. The shell builtin `pwd` returns the value of `$PWD`, so just skip the subshell and use the parameter directly.
This is part of a patch set to reduce the use of subshells.
Tested locally, and all tests pass.
...more of an optimization.
=> Use `$PWD` instead of `$(pwd)`

completion/available/pip.completion.bash, completion/available/pip3.completion.bash
Invokes pip only when actively trying to complete it.
This should greatly reduce shell load time, as the pip invocation takes
a lot of time.
Locally
=> completion: pip: Only invoke pip when trying to complete it

aliases/available/vim.aliases.bash
Simplifies the flow of `aliases/vim` by short circuiting instead of doing a whole `if` block and reducing weirds.
These were part of my `_command_exists` branch, but was out of scope.
=> aliases/vim: simplify code flow

clean_files.txt, plugins/available/ruby.plugin.bash
Quote some things and handle unbound parameters.
This was part of my `_command_exists` branch (#1938) but was out of scope.
=> plugin/ruby `shellcheck`

clean_files.txt, completion/available/laravel.completion.bash
Apply `shfmt`, fix `shellcheck`, and simplify code flow by short-circuiting at the top rather than indenting the whole function definition in an `if` clause.
=> completion/laravel: simplify code flow

completion/available/wpscan.completion.bash
Convert from indented if-block to return then unindented code. This should have basically one line change at the top, one line removed at the bottom, and then all whitespace.
=> completion/wpscan: simplify code flow (whitespace)

clean_files.txt, plugins/available/percol.plugin.bash
Adopt `_command_exists`, use `_log_warning`, some cleanup, `shellcheck`, and finally `shfmt`.
This was part of my `_command_exists` branch (#1938) but was out of scope.
=> plugin/percol `shellcheck`

clean_files.txt, plugins/available/base.plugin.bash, test/lib/helpers.bats, test/lib/log.bats, test/plugins/base.plugin.bats, test/plugins/battery.plugin.bats
I've run `shellcheck` on `base.plugin.bash` and made a bunch of tweaks to the functions. No behavior changes are intended except the removal of `banish-cookies()` and `command_exists()`.
Just trying to clean up.
Tested locally, and all tests pass.
=> plugin/base: improvements

completion/available/pip.completion.bash, completion/available/pip3.completion.bash
Short-circuit the loader rather than indenting nearly the whole file.
Alsö, assign the `_pip_completion()` handler directly once it's loaded so that we get out of the way once we load it.
Indenting the entirety of the logic of the file just weirds me out...it alsö makes future diff's weird, and makes any whitespace changes look like the whole file was replaced.
Alsö, this function doesn't need to run ever once the real completion is loaded.
Alsö alsö, I feel like the `_command_exists _pip_completion` branch of the if statement will *never* be taken, no matter what else is loaded already. Won't `eval "$(pip completion --bash)"` register the full handler itself and then we never run?
=> completion/pip: simplify control flow

clean_files.txt, lib/utilities.bash
This is a partial PR covering only the `lib/utilities` portion of #1917 in support of #1696.
My `shellcheck` branch (#1917) got a bit large, so I'm splitting it up. Each change is split out in to its own commit, so it should be easy to review that way. There are no intended behavior changes whatsoever; this is almost entirely quoting things, plus a few improvements to functions. 
The full test suite and `shellcheck` have run on #1917 and this is part of my main branch.
=> Lint: prepare `lib/utilities` for `shellcheck`

completion/available/gradle.completion.bash, lib/helpers.bash, plugins/available/gradle.plugin.bash
New function to do a search looking for a sibling to a parent of the current directory, for example to find `../../.git` to indicate that `$PWD` is inside a git repository.
This removes the remaining path traversal logic in the `gradle` plugin and completion, and I suspect may be useful for SCM stuff in themes.
Suggestions for a better function name welcome!!
All tests pass.
=> lib/helpers: new function `_bash-it-find-in-ancestor()`

clean_files.txt, plugins/available/blesh.plugin.bash
Added a new plugin, which loads ble.sh
I ping @akinomyoga here, in case we should do more things in here except loading ble.sh plainly
[ble.sh](https://github.com/akinomyoga/ble.sh) is a really interesting project, and seems like a nice addition as a Bash-it plugin :smile:
Locally
=> plugins: Add ble.sh plugin

bash_it.sh, plugins/available/xterm.plugin.bash, vendor/init.d/preexec.bash
This is a work around for the refusal of `bash-preexec` upstream to fix their mangling of user's `$HISTCONTROL`. See upstream PR 119 for a complete, working patch which maintains their desired behavior, while alsö allowing the user to choose their own settings including fall-back code to emulate user intent, *and* fall-back code for close-enough when the user forces `$HISTCONTROL`, *and* compatibility with Bash 3.2–5.x.
This workaround is intended to avoid the need to patch upstream (see #1966). We could of course just patch upstream and carry the patch ourselves, but that would introduce additional friction for updates in the future. 
Basically, this asks the `bash-preexec` lib to not run it's initializer when we load it, then we overwrite the problematic function, then we call the …
=> preexec: work around upstream mangling of `$HISTCONTROL`

docs/requirements.txt
Seems like docutils 0.18 has some problems and it is breaking our docs build (https://issues.apache.org/jira/browse/FLINK-24662)
Lets use 0.17.1 for now :)
Use docutils pinned to 0.17.1
Avoiding bogus docs build failure
Locally
=> docs: Pin docutils to 0.17.1

aliases/available/git.aliases.bash
When finding the default git branch, use a regex that matches only the word `main`, instead of any branch that has the substring `main` in it.
I have a repo with many other branches that contain the string `main`,
but our default branch is still `master`.  This grep was seeing those other branches
and deciding that my default branch was `main`.  
I tested this change on the repository I described above, and it correctly decided my default branch was `master` again.
- I didn't see any existing tests for the git aliases (or any aliases).  Should I add a new test file?
=> Look for branches that are literally the word main

clean_files.txt, plugins/available/zoxide.plugin.bash
zoxide is a smarter cd command for the terminal.
zoxide is fast, configurable, and feature-rich. In addition to bash/zsh/other shells, it supports a variety of programs like ranger, vim, etc.
=> plugin: add zoxide

themes/doubletime_multiline/doubletime_multiline.theme.bash, themes/doubletime_multiline_pyonly/doubletime_multiline_pyonly.theme.bash
Fix errors in doubletime_multiline and doubletime_multiline_pyonly themes caused by missing `doubletime_scm_prompt` function.
Replace calls to `doubletime_scm_prompt` with `scm_prompt` within `prompt_setter`
The `doubletime_scm_prompt` function was removed in favor of `scm_prompt` in commit dff892e0a31e3e2797d5406099cb8513b59e5eb4. This caused the doubletime_multiline and doubletime_multiline_pyonly themes to raise errors when generating prompts.
Manually tested on Ubuntu 20.04 (WSL) and on CentOS 7
N/A
=> Themes: Fix doubletime_multiline scm_prompt

clean_files.txt, completion/available/git.completion.bash, plugins/available/autojump.plugin.bash, plugins/available/base.plugin.bash, plugins/available/history-eternal.plugin.bash, plugins/available/history-search.plugin.bash, plugins/available/history-substring-search.plugin.bash, plugins/available/history.plugin.bash, vendor/init.d/preexec.bash
- remove the use of redundant cite
- minor cleanups to history.plugin.bash
- set explicit load orders for history-search and history-substring-search
- add new plugin history-eternal
history plugins needed some love now that we have dealt with preexec
locally
=> Wholesale cleanup of all history plugins

plugins/available/dirs.plugin.bash
Removes `shopt` setings from `dirs` plugin
Remove thes `shopt -s cdable_vars` setting from the `dirs` plugin.
I decided that I no-longer wanted `cdable_vars` enabled as I have too many environment variables and they were constantly getting in the way of tab-completing `cd`.
After removing the option from the my local bash config (I had it explicitly enabled), I discovered that it was **STILL** enabled when launching a new terminal.
I tracked it down to this plugin.
As much as possible, `shopt` settings should be left to the user.
Additionally, this plugin does not require the cdable_vars be enabled.
Marking as Breaking Change since some users may have picked up the setting from this plugin and may not realize why its missing after their next update.
=> plugin(dirs): remove shopt -s cdable_vars

completion/available/pipenv.completion.bash
Reference: https://buildmedia.readthedocs.org/media/pdf/pipenv/latest/pipenv.pdf 4.2.18 Shell Completion
change to `_PIPENV_COMPLETE=bash_source pipenv`
fix the problem:
```
Usage: pipenv [OPTIONS] COMMAND [ARGS]...
Try 'pipenv -h' for help.
Error: No such option: --completion Did you mean --python?
```
Yes. It fixes the problem.
- [ x] Bug fix (non-breaking change which fixes an issue)
---
Fixes #1993
=> "pipenv --completion" is obsoleted

bash_it.sh, clean_files.txt, plugins/available/jekyll.plugin.bash
Run `shellcheck`, `shfmt`, and then try to clean up a bit. 
No behavior changes intended with one exception: `source ~/.jekyllconfig` is moved from main to the Jekyll plugin.
Tested?
=> Plugin/jekyll: lint and stuff

themes/90210/90210.theme.bash, themes/bakke/bakke.theme.bash, themes/bira/bira.theme.bash, themes/codeword/codeword.theme.bash, themes/powerline/powerline.base.bash, themes/pure/pure.theme.bash, themes/purity/purity.theme.bash
This is a chunk of my `SC2154` branch (#1954), hopefully small enough to merge quickly.
I think the changes here should be uncontroversial and without behavior changes.
=> Themes: fix `shellcheck` (SC2154); Part A

completion/available/git.completion.bash, plugins/available/autojump.plugin.bash, vendor/init.d/preexec.bash
This reverts most of commit 2c8ee405662d03193510f57ab44391d20628999c.
- _Shellcheck_ documentation for the [`source-path`]( https://github.com/koalaman/shellcheck/wiki/Directive#source-path ) directive indicates this is correct usage. We're `source`ing the `bash-preexec.sh` file from inside the `vendor/github.com/rcaloras/bash-preexec` directory. If we used the [`source`]( https://github.com/koalaman/shellcheck/wiki/Directive#source ) directive, then the full complete path to the file itself would need to be specified.
- Fix `disable=1090` to `disable=SC1090` and remove duplicate lines since this `shellcheck` directive will apply to the entire if-ladder.
- Disabling `SC2154` is almost never appropriate. In this case, several `_git_bash_completion*` variables are expressly assigned in this …
=> Revert most of "Fix linting errors that snuck in."

plugins/available/fzf.plugin.bash
The check in fzf plugin for whether it's sourced already was inverted. Let's correct it.
=> Fix checking whether fzf is already in PATH

clean_files.txt, plugins/available/git-subrepo.plugin.bash
If the outer variable is double-quoted, then the default expansion when undefined does not get tilde-expanded; use `$HOME`. Alsö, fix `SC1091`
=> plugin/git-subrepo: use `$HOME` instead of `~`

clean_files.txt, plugins/available/base.plugin.bash, plugins/available/todo.plugin.bash
Clean up `plugin/todo`, add to `clean_files.txt`, and use `_bash-it-component-item-is-enabled()` in `plugin/base`.
Mostly just cleaning up, but alsö getting rid of that abomination in `plugin/base`.
Tests pass locally and in CI.
=> Plugin/todo: cleanup and simplify

clean_files.txt, plugins/available/man.plugin.bash
Add `R` to `$LESS`, which is interpreted as flags on the command line. Alsö, don't clobber user-set variables.
Otherwise, `-R` must be added on the command line or colors just won't be rendered and these variables will be ignored. Usually, `less` gets aliased or wrapped in a function, but if it's not then we'd like to use our settings. This alsö reduces the need to alias or wrap `less` and is much less likely to break.
=> Plugin/man: Add `R` to `$LESS`

clean_files.txt, plugins/available/dirs.plugin.bash
Use `$XDG_STATE_HOME`, and alsö run `shfmt` and `shellcheck` and all that jazz.
Just cleaning up!
=> Plugin/dirs: use `$XDG_STATE_HOME`

clean_files.txt, themes/essential/essential.theme.bash
Handle unbound parameters, even colors! Alsö, `shfmt`.
=> theme/essential: cleanup

clean_files.txt, plugins/available/python.plugin.bash
Don't check for `$OSTYPE` in order to determine which version of `python` to use... Alsö, use some `$EDITOR`s, and finally `shfmt`.
=> plugin/python: OS detection & `shfmt`

themes/powerline/powerline.base.bash
Fix bug that powerline theme's scm feature does not work.
The commit 2991aa66ca3e3cee98d3e52399fef30cef771176 removed set +u
but still references the variable `scm` without defining it.
This commit remove the reference to `scm`.
This makes powerline theme's scm feature work again.
=> theme/powerline: fix error `scm: parameter not defined`

completion/available/bash-it.completion.bash
I went on and removed the usage of loops from the bash-it completions, and arranged the functions to essentially perform the same acts, but process the file lists after having accumulated them, instead of performing tests etc for each and every one of the files. While I'm at it, I also double quoted some variables to avoid having the interpreter spend time trying to perform splitting on them (a bit of nitpick, but why not), made a couple of variables local, since they seemed to have gotten unnoticed and replaced a usage of sed with the pattern substitution parameter of parameter expansion. I was also thinking of eliminating the usage of pipes by using process substitution, thus eliminating spawned subshells and having the rest of process substitution performance benefits, but I don't know …
=> Bash-it completions performance improvement

clean_files.txt, test/bash_it/bash_it.bats, test/completion/bash-it.completion.bats, test/install/install.bats, test/install/uninstall.bats, test/lib/composure.bats, test/lib/helpers.bats, test/lib/log.bats, test/lib/search.bats, test/lib/utilities.bats, test/plugins/alias-completion.plugin.bats, test/plugins/base.plugin.bats, test/plugins/battery.plugin.bats, test/plugins/cmd-returned-notify.plugin.bats, test/plugins/go.plugin.bats, test/plugins/ruby.plugin.bats, test/plugins/xterm.plugin.bats, test/run, test/test_helper.bash, test/test_helper_libs.bash, test/themes/base.theme.bats, test/themes/base.theme.git.bats, test/themes/base.theme.svn.bats
All tests now run when there are spaces in `$BASH_IT`, and boilerplate removed from the top of most test files. 
As I'm learning BATS, I'm cleaning up duplicate code and hopefully making the tests faster and more reliable. There's more to do! This is just my first pass.
I run the tests manually myself, and alsö through GitHub Actions.
=> tests: path quoting and boilerplate

clean_files.txt, plugins/available/nginx.plugin.bash
Dont overwrite user-set variable, and quote path. Local some variables, `shellcheck`, `shfmt`
=> plugin/nginx: cleanup

clean_files.txt, plugins/available/latex.plugin.bash
This plugin was hard-coded for the 2009 edition of MacTeX. I am 99.999999% sure literally zero people use this plugin, since it hasn't done anything in over a decade.
Now, it will attempt to locate the currently installed edition of MacTeX and add it to the path.
=> Plugin/LaTeX: 2009 was thirteen years ago

clean_files.txt, completion/available/system.completion.bash, test/install/install.bats, test/lib/helpers.bats
Set BASH_IT_LOAD_PRIORITY to 325 so that the distro-provided _bash-completions_ package is loaded before any other completions packaged here.
Several of the completions bundled in _Bash It_ test whether another completion is already installed, however `system` sorts lexicographically fairly late in the alphabet so it is unlikely that our tests are succeeding. I chose `325` so that it's still possible to deliberately place something *before* this component, if needed somehow.
=> completion/system: load earlier than others

themes/atomic/atomic.theme.bash, themes/bobby-python/bobby-python.theme.bash, themes/bobby/bobby.theme.bash, themes/candy/candy.theme.bash, themes/easy/easy.theme.bash
This is a chunk of my `SC2154` branch (#1954), hopefully small enough to merge quickly, but slightly more changes than #1977.
I think the changes here should be without behavior changes. There's some *very slight* refactoring with subshells, but really this is intended to be simple and similar changes across all these files.
=> Themes: `shellcheck` (SC2154); Part B

clean_files.txt, lib/log.bash
This is a partial PR covering only the `lib/log` portion of #1917 in support of #1696.
My `shellcheck` branch (#1917) got a bit large, so I'm splitting it up. This PR is independent of my other PRs.
The only non-trivial change here is renaming `_log_general()` to `_bash-it-log-message()` and new function to replace `_set-prefix-based-on-path()`. 
The full test suite and `shellcheck` have run on #1917 and this is part of my main branch.
=> Lib/log: linting and small improvements

lib/utilities.bash
- Refactor function `_bash-it-pluralize-component()`;
- Remove dependencies from `_bash-it-component-item-is-enabled()` (so it's much faster);
- Fix `_bash-it-component-help()` for long component names;
- Clean up tests a little.
Refactoring `_bash-it-pluralize-component()` started by accident while fiddling with `bash-it search` and resulted in:
- renaming the function so it better matches it's siblings,
- adding a matching `_bash-it-component-singularize()` which can be used when logging and other places,
- using `printf`'s `-v` flag to store to a variable, rather than echoing to `stdout` to reduce subshells,
- updating `_bash-it-component-cache-file()` and `_bash-it-component-help()` to use the variable,
- updating …
=> lib/utilities: refactor `_bash-it-pluralize-component()` & other improvements

bash_it.sh, docs/development.rst, themes/base.theme.bash
Create an array `_bash_it_library_finalize_hook` and loop at the end of the main `bash_it.sh` to run each element in the array.
The purpose here is to run some command after everything else has been loaded. For example, `lib/theme` checks for executables for SCM commands, but `$PATH` may be altered after `lib/theme` has loaded and therefore some available commands may never be discovered. To accommodate this problem, create `_bash_it_appearance_scm_init()` and add it to the hook. It will re-check at end of `bash_it.sh` just before prompt is first displayed.
This has been part of my main branch for months and all tests pass.
=> Create lib finalize hook

clean_files.txt, plugins/available/proxy.plugin.bash
Adopt `_command_exists`, quote variables, handle unbound parameters, code flow simplification.
This was part of my `_command_exists` branch (#1938) but was out of scope.
=> plugin/proxy: lint

lib/helpers.bash
This is a *tiny* PR since I'm having trouble rebasing my `helpers` PR (#1934). This change was in the middle and just much easier to pull it aside 😃 
The weird subshell is weird AF. Just do a normal `if`. Ditto `_binary_exists()`, `_completion_exists()`, and `_is_function()`! Alsö, make `all_groups()` literally 100x faster.
Simplicity, consistency, and #1696! And `git rebase` is hard sometimes.
Locale and all tests pass.
=> lib/helpers: fix `_command_exists()`

clean_files.txt, themes/pete/pete.theme.bash
Simplify Pete's `prompt_setter()` a little. It's more verbose, but it's clearer what's what.
Simplicity, clarity, and #1696.
`bash-it preview pete`
=> theme/pete: `shellcheck` && `shfmt`

clean_files.txt, completion/available/bash-it.completion.bash, test/completion/bash-it.completion.bats
- `shfmt`
- `shellcheck`
- Use `_bash-it-component-list-enabled()` and `_bash-it-component-list-disabled()` instead of reinventing the wheel.
- Use `read -ra` to populate `$COMPREPLY`, instead of unquoted word separation.
- New function `_compreply_candidates()` to simplify the loop for `read -ra`.
After the recent performance upgrades for this completion, I took a look at what was bogging it down before and decided to lint the file. I then fell down the rabbit hole and accidentally refactored it again. I preserved the structure and speed, but deleted quite a lot by using existing functions as well as ensuring we handle spaces and International/unicode characters properly.
Manual testing at the command line, `test/completion/bash-it.completion.bats`, and the full test suite.
=> completion/bash-it: lint and simplify

docs/README.md
This displays the build/test status of the latest commit the default branch, not neccessarily `master` branch, from whichever fork it's read from.
The test suite on my fork is broken (due to my not merging all my branches cleanly for my own main branch), but on the rare occasion I clicked on my own repo online it would show a clean build! This fixes it so that the badge is displayed from the *current* repository, and from the default branch.
Works for me!
=> README: Display latest build status from default branch

.github/workflows/ci.yml
Now that Mac OS X is "version 11", the "minor" version is no longer relevant.
Alsö, clean up the run conditions.
We've been running on the initial-release version for months.
All tests pass.
=> CI: fix version of OSX runner

clean_files.txt, completion/available/dotnet.completion.bash
This sets up `dotnet` to complete itself according to [vendor documentation]( https://docs.microsoft.com/en-us/dotnet/core/tools/enable-tab-autocomplete#bash ).
This closes #1983.
I'm a big fan of tools completing themselves!
I've tested this, and alsö opened an issue upstream to improve their example: dotnet/docs#27828.
=> completion/dotnet: new completion

themes/brunton/brunton.theme.bash
Handle all unbound parameters, even colors!
Simplicity, consistency, and #1696.
`bash-it preview brunton`
=> theme/brunton: `shellcheck`

clean_files.txt, plugins/available/projects.plugin.bash, template/bash_profile.template.bash
`shfmt`, `shellcheck`, and minor cleanup.
=> Plugin/projects: cleanup

.editorconfig, lib/preexec.bash, test/lib/preexec.bats
Add some BATS tests for `lib/preexec` to prevent minor mistakes from becoming big issues. 🙃
My patch for `lib/preexec` broke at least one use case, and alsö had a glaring logic-inversion that broke everything. Let's not do that again!
=> lib/preexec: tests!

lib/preexec.bash
- lib: helpers: Dont reload .bash_profile in login shells
- lib: preexec: Properly return if there was a conflict in check_*_conflict
We broke some things in our recent merges!
Locally
=> fix broken reload/restart and preexec

lib/helpers.bash
Bash loads initialization files on Mac just the same as it does on Linux or WSL. Our previous assumptions were wrong, and my fix was alsö wrong because I made more assumptions!
This patch eliminates the assumptions. Literally just load either the startup file the shell started with, or fall back to `~/.bashrc`. Don't check `shopt -q login_shell` and don't check `$OSTYPE` or anything else.
I broke @NoahGorny's WSL shell. WSL runs shells as login shells, just like on Mac. But, since it loads an entire Linux distribution under the hood, WSL includes workarounds for _Bash_'s weird startup file behaviours and, therefore, my assumption that the startup file for a login must always be `~/.bash_profile` (or `~/.profile`) was quickly proven wrong. 😞 
By Noah. 😆
=> lib/helpers: eliminate assumptions about login shells

clean_files.txt, lib/search.bash, test/lib/search.bats
This is a partial PR covering only the `lib/search` portion of #1917 in support of #1696.
My `shellcheck` branch (#1917) got a bit large, so I'm splitting it up. This PR is inclusive of my `helpers` (#1934) branch.
The full test suite and `shellcheck` have run on #1917 and this is part of my main branch.
=> Lib/search: lint, cleanup, and small fixes

clean_files.txt, scripts/reloader.bash
- adopt `_bash-it-log-prefix-by-path()`,
- `shfmt`,
- `shellcheck`,
Trying to get this thing to run with spaces in path...
This has been part of my main branch since September...
=> lib/reloader: lint and modernize

lib/helpers.bash
Fix error `awk: unterminated regexp` when `bash-it update` or `bash-it update dev` is called.
=> helpers: fix `awk: unterminated regexp`

bash_it.sh
Instead of $LIB and $CUSTOM variables, use the glob pattern in the foreach statement quoting the path but not the glob. Quoting the glob will make it not a glob, but when expanding the not-quoted $LIB or $CUSTOM variable Bash will split all words, including spaces in the actual path. This helps towards #1696.
This is literally one of the examples under Code Style on the contribution page.
Closes #1435.
This resolves the failure to source the files under $BASH_IT/lib when there is any space in $BASH_IT, such as when the user name contains a space or the path to the repository contains a space.
You can reproduce this with a user short name with a space, which is possible with the "MacBuddy" default setup assistant on Mac OS X, or if $BASH_IT is set to a path containing an (additional) …
=> Glob for *.bash properly when path contains spaces

clean_files.txt, lib/history.bash, plugins/available/history-eternal.plugin.bash, plugins/available/history-search.plugin.bash, plugins/available/history-substring-search.plugin.bash, plugins/available/history.plugin.bash, themes/base.theme.bash
Two new functions `_bash_it_history_auto_save()` and `_bash_it_history_auto_load()`, which append new history to disk and load new history from disk, respectively.
These functions operate based on four modes configured in `$HISTCONTROL`:
1. `autoshare`: append to `$HISTFILE` when `_bash_it_history_auto_save()` called, and read from `$HISTFILE` when `_bash_it_history_auto_load()` called.
2. `autosave`: append to `$HISTFILE` when `_bash_it_history_auto_save()` called, but do not do anything when `_bash_it_history_auto_load()` called.
3. `autoload`: do not do anything when `_bash_it_history_auto_save()` called, but do read from `$HISTFILE` when `_bash_it_history_auto_load()` called.
4. `noauto` (default): don't do anything.
This PR is based on @davidpfarrell's suggestions in and fixes #1595. …
=> Feature: automatic history management

completion/available/system.completion.bash
- Load the correct version of `bash-completion` even when not "linked".
I realized my completions were not working and realized I had `brew unlink`'d my `bash-completion`, since I have both v1 and v2 installed. This fixes `completion/system` to look for v1 and v2 *both* under their versioned directories. My previous version of this had looked for v1 in it's version'd directory, but looked for v2 only under the main directory. Shot my own foot there.
=> completion/system: correctly load version when not linked

clean_files.txt, completion/available/bash-it.completion.bash, docs/themes.rst, lib/helpers.bash, lib/preview.bash, test/completion/bash-it.completion.bats
Refactor in to a function, but continue to support current usage.
This allows running the preview without reloading the startup files multiple times, and alsö integrate to `bash-it` function, and alsö alsö offer it's own completions. 
Tested locally and all tests pass.
=> lib/preview: functionalize

plugins/available/battery.plugin.bash, test/plugins/battery.plugin.bats
When `upower --enumerate | grep -i BAT` returns multiple lines of results (which are file paths),
the added quotation (from commit 3cb5f3f7e66345a329cae8ad112f1ecbedc60dab) concatenates them all to provide an invalid path.
Thus to make the plugin work as before the commit,
take only the first line of the results.
Add `head -n 1` to filter out the rest of the result except the first line.
=> plugin/battery: bug fix

plugins/available/battery.plugin.bash, test/plugins/battery.plugin.bats
- Splits the `upower` invocation in two,
- expands the `upower` mock in the tests to return multiple paths.
Bash-it/bash-it#2074 / NariyasuHeseri/bash-it#1
=> DRAFT: plugin/battery: multiple batteries

lib/helpers.bash
When the file is being re-created, we write to it, instead of appending to
it. So, the rm here is unnecessary and prevents users from linking the profile
file to another location that is potentially under version control. For
instance, once could link to a profile file located at
"$BASH_IT_CUSTOM/profiles/*.bash_it".
- I ran `bash-it profile save` to create a profile file.
- Moved it into my `$BASH_IT_CUSTOM` directory
- Linked that file into the `$BASH_IT/profiles/` directory
- Tested loading and re-saving the profile after making changes
=> lib/helpers: Don't rm "$profile_path" before writing to it

lib/log.bash
- Replace `echo -e` with `printf` in `_bash-it-log-message()`.
- `local` positional parameters to allow for defaults.
- Use new `composure.sh` feature to reduce load order dependency.
- Use `if`/`then` properly.
- Clean up use of `$BASH_IT_LOG_PREFIX` slightly (eliminate duplicate colons).
Misuse of `&&`/`||` can cause unexpected return status, so I'm just fixing to use `if`/`then` wherever I see them. `echo -e` is unreliable and has differing behaviour in different contexts, such as in subshells and when `xpg_echo` is enabled. `printf` does exactly what it says on the tin. The parameter `$message` was leaking from every log function, so I `local`'d it. Alsö, `local` the rest of the parameters and fill in a default color, default log level, and strip duplicate colons from the message and …
=> lib/log: //echo/printf

bash_it.sh, plugins/available/blesh.plugin.bash
The recent change 23f9b741 has broken `plugin/blesh`. Because `ble.sh` now receives garbage arguments, it fails to interpret the arguments and cancels its loading.
- First, it should be noted that `source FILE` without arguments will inherit the arguments of the caller context.
- Originally, [`reloader.bash` has been called without arguments](https://github.com/Bash-it/bash-it/commit/23f9b7416a2db3290f27b1e45fab591218ba460c#diff-967b08ada7d8c340b3414a24e456ea88cd3e551147acfefa26a6cf2079f1fd36L58) for the current mechanism of enabling modules. The arguments have been [only supplied for the legacy loading](https://github.com/Bash-it/bash-it/commit/23f9b7416a2db3290f27b1e45fab591218ba460c#diff-967b08ada7d8c340b3414a24e456ea88cd3e551147acfefa26a6cf2079f1fd36L63). However, now the arguments …
=> bash_it.sh: source `reloader.bash` without arguments for the default enabling

lib/preexec.bash, vendor/github.com/rcaloras/bash-preexec/bash-preexec.sh
git-vendor-name: preexec
git-vendor-dir: vendor/github.com/rcaloras/bash-preexec
git-vendor-repository: https://github.com/rcaloras/bash-preexec
git-vendor-ref: fd2ffa8876d3940c97ffdc3cc807e43277cf72da
A few upstream changes, notably proper handling of previously-undefined `$PROMPT_COMMAND` and properly handling `extdebug` to prevent subshells from inheriting the `DEBUG` trap.
Alsö, use `_bash_it_library_finalize_hook` to avoid touching `$PROMPT_COMMAND` until the last possible moment, which fixes #2070. 
Live on my main branch for ages.
=> Update "preexec" from "https://github.com/rcaloras/bash-preexec@master"

lib/helpers.bash
when i tried to install, i got a message `_bash-it-pluralize-component` command not found; after checking `utilities.bash` the correct function name was `_bash-it-component-pluralize`
=> fix wrong function name call  in `helpers.bash`

clean_files.txt, themes/base.theme.bash, themes/githelpers.theme.bash, themes/p4helpers.theme.bash
Quote a bunch of things, adopt `shellcheck` recommendations, try to simplify a few parts...
Simplicity, clarity, and #1696! 
This is part of my main branch since September and the full test suite passes.
=> lib/theme: `shfmt`, `shellcheck`, and some cleanup

clean_files.txt, lib/appearance.bash, lib/log.bash, themes/base.theme.bash
- Export `$CLICOLOR`, instead of `$LSCOLORS`, and add a comment to the base theme to help theme authors;
- `shellcheck`;
- Alsö, since the *value* of `$CLICOLOR` is not used anywhere, overload it to count the number of colors available for use elsewhere.
Exporting `$LSCOLOR` from `lib/appearance` has always been weird to me and it took me a few rounds to figure out why: it's not useful. BSD `ls` enables color output if `$CLICOLOR` is set (to any value, even blank), and GNU `ls` doesn't use any variable to enable color listings. (GNU `ls` requires `--color=auto` or similar.) The `$LSCOLORS` (BSD) and `$LS_COLORS` (GNU) variables do *not* enable color listings; they just specify which color scheme to use (with incompatible formats).
Themes can and should customize `$LSCOLORS`/`$LS_COLORS`, …
=> lib/appearance: export `$CLICOLOR` instead of `$LSCOLOR`

plugins/available/battery.plugin.bash, test/plugins/battery.plugin.bats
This should fix both our BATS tests as well as the `battery_percentage()` (and related) function(s) to properly handle multiple attached batteries, and closes #2104.
The previous fix for multiple batteries returned by `upower -e` just tried to snip off the first line and run with it, but this seems to have triggered a bug in _Bash_ related to `set -o pipefail` (which is enabled by BATS during testing, and elsewhere). 
This patch changes `plugin/battery` to just read all the batteries into an array, thus not cutting off the enumeration prematurely and avoiding the testing bug. 
Currently, this patch does *not* handle any batteries after the first, but at least it doesn't just trim the list.
locally, and GitHub Actions
=> plugin/battery: fix handling of multiple batteries with `upower`

clean_files.txt, test/bash_it/bash_it.bats, test/completion/aliases.completion.bats, test/completion/bash-it.completion.bats, test/install/install.bats, test/install/uninstall.bats, test/lib/composure.bats, test/lib/helpers.bats, test/lib/log.bats, test/lib/preexec.bats, test/lib/search.bats, test/lib/utilities.bats, test/plugins/base.plugin.bats, test/plugins/battery.plugin.bats, test/plugins/cmd-returned-notify.plugin.bats, test/plugins/go.plugin.bats, test/plugins/ruby.plugin.bats, test/plugins/xterm.plugin.bats, test/run, test/test_helper.bash, test/test_helper_libs.bash, test/themes/base.theme.bats, test/themes/base.theme.git.bats, test/themes/base.theme.svn.bats
- Apply recommendations from BATS documentation to the boilerplate in the test files, 
- refactor large parts of `test_helper.bash`,
- use `git worktree` for a fast, reliable, and predictable test environment,
- remove dependency on `test_make`,
- make working tree stand up per-file, rather than per-test, so it's much faster,
- standardize test fixture staging,
- don't ever access my local `$HOME` or local `$BASH_IT`,
- update `bats-core` to tag `v1.5.0`.
I believe this closes #1821.
This is chapter 2 of my last BATS patch. This time I understand BATS slightly better!
I disabled intra-file parallelization, but this can be reverted as soon as configuration is no longer inside the repo. 
This alsö should resolve the drive behind #1753, as the test environment is now separated from the live …
=> BATS infra refactor

clean_files.txt
In the commit 7fcad6ed0d9427e51b94cc721a846666cef8ea82 the file rename was done [test/plugins/alias-completion.plugin.bats → test/completion/aliases.completion.bats](https://github.com/Bash-it/bash-it/commit/7fcad6ed0d9427e51b94cc721a846666cef8ea82#diff-d008e1016f48d53486ce8485a2ca7bdee00d69d6e41f2c0e001a996687e4da11). This PR resolve the file not found error caused while performing lint on the old file
For more context, check [this build output](https://github.com/Bash-it/bash-it/runs/5435367359?check_suite_focus=true#step:8:8)
=> fix test file path from the 7fcad6e commit

lib/preview.bash, lib/search.bash
- lib: preview: Load only bash-it.sh when previewing
- lib: search: Increase delay in _bash-it-flash-term to 0.2 secs
Hi @gaelicWizard, seems like I bumped into a problem with bash-it preview. Please take a look!
=> Fix bash-it preview

lib/command_duration.bash
UTF8 clock value can be set between [90](https://www.fileformat.info/info/unicode/char/1f550/index.htm) and [9b](https://www.fileformat.info/info/unicode/char/1f55b/index.htm) in hexadecimal.
The current code was between 90 and 101.
Clock icon was not correct for certain value.
```bash
for second in {1..15}; do
clock_hand=$(printf '%x' $(((${1:-${second}} % 12) + 144)))
printf '%b' "\xf0\x9f\x95\x$clock_hand"
done
```
Before:
After:
=> Fix dynamic clock icon

lib/utilities.bash
Fix function that try to find a full path for grep.
When a grep alias exists, `_bash-it-grep` and `_bash-it-egrep` are using `/usr/bin/grep` by default.
This break bash-it on debian based distribution, where grep is `/bin/grep`.
```bash
$ type -t grep
alias
$ type grep
grep is aliased to `grep --color=auto'
$ type -p egrep || type -p grep
```
The fix is to use `type -P`:
```
-P	force a PATH search for each NAME, even if it is an alias,
builtin, or function, and returns the name of the disk file
that would be executed
-p	returns either the name of the disk file that would be executed,
or nothing if `type -t NAME' would not return `file'
```
When using bash-it on a debian system, I have this error before each prompt command
```
-bash: /usr/bin/grep: No such file or directory
```
After the …
=> Fix grep path when a grep alias exists

aliases/available/general.aliases.bash
Provide a default editor in case EDITOR and ALTERNATIVE_EDITOR are not defined
Closes #2123 
Locally, I can probably add a test of this
=> general: Add default nano editor for the edit alias

plugins/available/projects.plugin.bash
Fix regression introduced in ea2002a.
Before this commit, when the provided project was unique under all the
project paths, the command automatically change the directory to it.
Currently this is no more the case.
If there are many project paths set, then the project path menu is shown
at every call.
Get the same behavior than before the regression was introduced.
=> fix projects plugin regression

lib/helpers.bash
Having merge logs with actual changes was too noisy. So in this PR, it will be removed and actual commits will be shown. Also when the upgrade fails, the directory doesn't change back to the source directory, rather it stayed in `$BASH_IT` directory. So I have also added popd just before returning the function.
=> Improve bashit upgrade function git log and add missing popd

docs/themes-list/barbuk.rst, themes/barbuk/barbuk.theme.bash
This is a complete rework of my theme.
I'm using more tools at work or for personal usage that need context in my shell:
- ruby version
- terraform 
- aws / scw profil
The theme is the same, but with more flexibility.
You can now configure it to display different information by setting `BARBUK_PROMPT` env variable.
All new block are inspired from base theme or powerline theme.
I use the theme to work, it's was tested in real work condition :).
=> Update of barbuk theme (add modular blocks)

aliases/available/general.aliases.bash
This PR fixes #2151 by by removing 'sudo' aliases because bash-it should not be the business of mucking about with sudo at all.
Initial purpose of this PR has changed and has been:
Use `sudoedit` instead of `sudo vim` which is a big security issue because users can get a root shell by executing arbitrary shell commands by `vim`!
Nobody wants users to allow to become root just because they can edit any file (which would also make them root by manipulating the "right" with the "right" commands).
Issue #2151 will be fixed by this PR.
I use `sudoedit` instead  of `sudo vim` for some decades on different linux distributions and also on MacOS 😁
=> Issue 2151 🛂 do not give users a root shell by executing arbitrary shell commands by 'vim'

.github/workflows/ci.yml
Github deprecated and will remove two runner images.
macos-10.15 will be removed on 2022-08-30
macos-12 is available
https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
ubuntu-18.04 will be removed on 2022-12-01
ubuntu-22.04 is available
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
I found this detail while investigating intermittent macos test failures. This doesn't appear to be the cause of my issues, but it seems important information to share.
This configuration successfully built on my fork's CI:
https://github.com/jakebman/bash-it/actions/runs/2848395734
=> Update Gitlab Runner images

completion/available/projects.completion.bash
The projects plugin was changed to reference `BASH_IT_PROJECT_PATHS` but the completion was still using `PROJECT_PATHS`
This fixes a regression in the project completion code due to a refactor in the project plugin code
Tested locally
n/a
=> Update variable name to match projects.plugin.bash

aliases/available/git.aliases.bash
Provides a Git alias for `git add -v`, which lists the files being added to the staging area.
This aligns with the idea of `grv` (short for `git remote -v`, to display remotes verbosely).
I use this alias for years on my developer laptop.
=> Verbose version of `git add` (gav)

completion/available/fabric.completion.bash, completion/available/gradle.completion.bash, completion/available/makefile.completion.bash, lib/helpers.bash, lib/utilities.bash, lint_clean_files.sh, plugins/available/aws.plugin.bash, plugins/available/jekyll.plugin.bash, plugins/available/postgres.plugin.bash, themes/rjorgenson/rjorgenson.theme.bash
Takes a pass at correcting usages of `egrep` and `fgrep`, replacing with `grep -E` and `grep -F`, respectively.
Also makes a few other modifications:
* Ensures that the `-E` or `-F` option, when used, is the _first_ option
* ie. `grep -oE` => `grep -E -o`
* Updates `_bash-it-grep` to invoke `grep` with _just_ the provided arguments
* This function was (and still is) unused, but decided this new functionality was actually more useful
* Introduces `_bash-it-fgrep` to invoke `grep -F`
* Removes `type -P egrep` from the `_bash-it-*grep` functions
* For usages that were _already going to be modified_, use `-F` if appropriate
* Does not touch grep usages that may have benefited from `-F`, but were not otherwise considered for this PR
* Adds shellcheck header to modified `.bash` files that …
=> chore: Use grep -E / grep -F instead of egrep / fgrep

.github/workflows/ci.yml
Fixes breaking 'lint' ci job
replaces use of `brew` when installing shellcheck.
Now fetches pre-compiled stable linux version from project's github releases
Brew stopped being installed by default on github ubuntu images, breaking the ability to use it to install shellcheck.
This PR's lint pipeline task runs successfully !
=> bug:CI Lint - Install shellcheck via wget

docs/README.md, docs/troubleshooting.rst
Included a subsection under the Installation instructions in the README, giving MacOS users instructions on how to update their version of Bash so as to properly enjoy the full functionality of Bash-it.
It is worth noting that while trying to follow the instructions suggested by [davesteinberg](https://github.com/davesteinberg) in issue #1614, I noticed that Homebrew did not install Bash to ``/usr/local/bin/bash``, but rather to ``/opt/homebrew/bin/bash``. As it turns out, M1 Macs have changed Homebrew's default installation path to ``/opt/homebrew/bin/``. Therefore, I altered the suggested instructions slightly to include two sets of instructions, one for x86 Mac users, and one for M1 Mac users, which reflect this discrepancy.
As noted by [issue …
=> Added update-bash section in README

aliases/available/kubectl.aliases.bash
This is minor house cleaning. I saw the function name and didn't like that it's name wasn't well scoped,
and further, I see no need for wrapping this logic with a function.
Thought for the future:  maybe all alias loading should be wrapped in a callable with a predictable name?
e.g. `_bash_it_load_alias_<alias plugin name>`
I don't like polluting the global namespace with poorly named functions
See the test output.
=> remove function wrapper around kubectl aliases

lib/command_duration.bash, plugins/available/cmd-returned-notify.plugin.bash, test/plugins/cmd-returned-notify.plugin.bats
Isolates fetching of EPOCHREALTIME to a function which sets LC_ALL=en_US.UTF-8.
This ensures that the value is in decimal format, regardless of runtime locale.
fixes #2171 
Tested locally
=> bug: Use en_US when fetching EPOCHREALTIME

completion/available/aliases.completion.bash
Before, the '\n' in the characters being checked would be interpreted as 'n' rather than newline meaning that any alias who's command contained the letter 'n' would be incorrectly skipped.
This bug is annoying as certain aliases will appear to randomly not have completion for them.
- Tests pass locally.
- My `alias gb='git branch'` alias now shows the correct completion
- Tested that the C style string usage still correctly identifies aliases with disallowed characters
=> bug: Use C style strings when checking for invalid alias characters

install.sh, plugins/available/colors.plugin.bash, themes/agnoster/agnoster.theme.bash
There are some shellcheck errors, this PR fixes these
N/A
Locally, on linux
=> Fix lint errors in multiple files

lib/command_duration.bash
Allows for setting "COMMAND_DURATION_MIN_SECONDS" to more than 60 seconds without adding to the prompt. Previously always showed with lengths over 60 seconds regardless of setting. The documentation does not mention that it would always show when over 1 minute so no change is necessary.
Allows setting minimum duration for prompts longer than 60 seconds.
Tested locally on Ubuntu 22.04 and Debian 11 using sleep of various lengths.
=> Allow for longer command min duration

.github/workflows/ci.yml
This commit bumps `go` version to 1.21.0 and changes `go get` to `go install`.
Current workflow for PRs is broken because the tool that is invoked to format the code, `shfmt`, requires `go` >= 1.19.
Workflow was launched again after fix and it doesn't fail anymore.
=> fix: lint :green_heart:

docs/contributing.rst
Simply fixes the links of the Bats testing libraries that we use. The old links were outdated.
=> docs: Update Bash libraries links

.github/workflows/ci.yml
CI hasn't been updated in a hot while. This updates the actions to their latest and greates versions. It also fixes issues with the Go version being too low for `shfmt`.
- [-] I have added tests to cover my changes, and all the new and existing tests pass.
=> ci: Update GitHub actions

themes/brainy/brainy.theme.bash
a theme file breaks shellcheck linting for my other PR, fixing it even though it's not my code.
unrelated PRs fail the lint test otherwise.
=> fix the shellcheck lint test for Brainy theme

aliases/available/git.aliases.bash
Adds a short Git alias for `git show --name-only`, which list the files affected by the changes only (instead of the full diff).
The Git command `git show --name-only` list only the files affected by the changes instead of showing the full diff, which comes in handy when you need to know which files were affected w/o being distracted by the full diff of the changes.
The additional `git show --name-status` shows the current version control status of the listed files. (Maybe interesting to note, this is like a light version of `git whatchanged -1`.)
Just two convenient aliases in addition to `gsh` (`git show`) to avoid the need for typing and remembering the lengthy `--name-only` and `--name-status` options.
I tried it out locally, applied the identical change to my local Bash-it setup. …
=> Add git alias `gshn` (`git show --name-only`)

aliases/available/git.aliases.bash
Adds Git aliases for merging are rebasing, which are needed when conflicts occur.
For a better user experience, the same pattern for constructing the aliases is applied for merge and rebase. The aliases also largely match [the ones provided by OMZ](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git). `gms` is inspired by OMZ (I have never used it, personally).
When working with branches conflicts can occur and need to be resolved. This may involve options like `--continue` and `--abort` for merge and rebase. Some developers may even want to perform `--interactive` rebasing.
I have the identical changes integrated in a fresh, local installation of Bash-it on my developer laptop.
To verify that the aliases don't conflict with existing ones, I have grepped the current repository HEAD …
=> Add more aliases for `git merge` and `git rebase`

clean_files.txt, docs/themes-list/index.rst, docs/themes-list/inretio.rst, themes/inretio/inretio.theme.bash
Add new theme called Inretio, along with documentation describing it.
Inretio theme uses inspiration from existing themes: `metal` and `bobby`, but adds more details about virtual environment - when Python is available in it, prompt will display that particular Python binary version.
Displaying specific Python version is very useful for developers who keep multiple `venv`s for running their Python code on different runner versions, e.g.: `3.12.x` and `3.9.x` on the same machine.
Tested on usual filesystem folder, Git-tracked folder, in `venv` without Python and in `venv` with Python.
Added in documentation as required: https://github.com/Bash-it/bash-it/pull/2246
=> Add new theme - Inretio

aliases/available/git.aliases.bash
=> (update) Add some new aliases for logging and for miss typing. 

lib/command_duration.bash
When using the lib to display the command duration, the dynamic clock is off by 1.
This change is required to have a dynamic clock that output the correct clock hand.
Before:
```bash
for second in {1..15}; do     
clock_hand=$(printf '%x' $(((${1:-${second}} % 12) + 144)))
printf '%b' "\xf0\x9f\x95\x$clock_hand"
done
🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛🕐🕑🕒🕓
```
After:
```bash
for second in {1..15}; do     
clock_hand=$(printf '%x' $((((${1:-${second}} -1 ) % 12) + 144)))
printf '%b' "\xf0\x9f\x95\x$clock_hand"
done
🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛🕐🕑🕒
```
=> Fix clock_hand to display correct hour hand

clean_files.txt, themes/lambda/lambda.theme.bash
I've created a new Bash theme named "Lambda". This theme provides a clean and visually appealing command line prompt. Below, I briefly explain the configuration file and its elements.
```bash
function set_prompt {
local user_color="\[\033[1;31m\]"  # bold red for username
local at_color="\[\033[1;37m\]"    # bold white for @ symbol
local host_color="\[\033[1;31m\]"  # bold red for hostname
local in_color="\[\033[1;37m\]"    # bold white for "in"
local dir_color="\[\033[1;35m\]"   # bold purple for current working directory
local git_color="\[\033[1;36m\]"   # bold cyan for Git information
local time_color="\[\033[1;32m\]"  # bold green for time taken
local reset_color="\[\033[0m\]"    # reset color
local prompt_symbol_color="\[\033[1;31m\]"  # bold red for the prompt symbol
local …
```
=>  added new theme (lambda)

themes/bira/bira.theme.bash
Support for the showing the conda environment for the bira theme. This will prioritise the virtualenv prompt. 
I usually got confused whether conda is activated or not, then found that it is in fact activated but theme doesn't handle `CONDA_DEFAULT_ENV` variable.
Locally, sourcing the new script with new changes and activating the environment
=> Support conda environement for bira theme

themes/liquidprompt/liquidprompt.theme.bash
Missing leading underscore in `_lp_escape`
Without this - presumably - the code fails silently, never presenting the branch name in the PS1 prompt.
Forgive me if there are tests for themes, but I could not find any; I personally tested this by cd'ing into and out of Git clone directories with and without the fix.
=> Fix call to liquidprompt function

clean_files.txt, themes/elixr/elixr.theme.bash
Followed instructions in #1696 to cleanup `elixr.theme.bash`
Addresses #1696
Ran `./lint_clean_files.sh`
=> Clean `elixr.theme.bash`

aliases/available/git.aliases.bash
Adds a new alias for pulling changes with Git.
From the `git-pull` man page:
> -p, --prune
> Before fetching, remove any remote-tracking references that no longer exist on the remote.
When working with feature branches it's necessary to clean up branches from time to time. The alias makes this recurring task easier.
I have the exact same changes integrated in a local, fresh installation of Bash-it on my developer laptop.
I grepped for "glp" over the current repository HEAD to verify that there are no conflicting aliases.
=> Add alias for `git pull --prune`

clean_files.txt, lint_clean_files.sh
I noticed that all files under `lib/*` were manually specified in `clean_files.txt`. I refactored that to the first section.
When running the `lint_clean_files.sh` script, I receieve the following message:
```text
xargs: warning: options --max-args and --replace/-I/-i are mutually exclusive, ignoring previous --max-args value
...
```
Because the previuos `--max-args` / `-n` value is ignored anyways, and to remove the warning, I removed that option from the script.
This simplifes the cleaning files workflow.
By executing `./lint_clean_files.sh`. And double-checking to ensure that directories are, in fact, supported by `clean_files.txt`.
=> Tweaks to clean files scripts and file list

plugins/available/gif.plugin.bash
* fixes for the latest versions of gifski and gifsicle commandline options.
* More warning messages from ffmpeg.
* print help when run with --help
* improved BASH syntax
updates since stale code was broken
ran it locally with different options
=> Updates to the gif plugin

aliases/available/git.aliases.bash
Adds two aliases for `git reset`, which are [inspired by OMZ](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git).
- `grh` is a natural acronym for `git reset HEAD`.
- `grh!` is the "dangerous" version of `git reset`, which throws away everything, hence the exclamation mark.
The existing Git alias for `git reset` is not immediately obvious, unless you are used to think in terms of "stage" and "unstage".
I use this on a daily basis, having it integrated identically in a fresh installation of Bash-it on my developer laptop.
The new aliases don't clash with existing ones, as verified manually by a simple text search in the file and a grep over the repository HEAD.
=> Add alias for `git reset --hard` and `grh` like OMZ

plugins/available/nvm.plugin.bash
Loading a brew-installed `nvm` was previously broken. This PR fixes it.
This reverts to the original (working) version from 2017. During the most recent refactor to use the `_bash_it_homebrew_check` helper method, it was overlooked that `${BASH_IT_HOMEBREW_PREFIX}/nvm.sh` is not the equivalent to `$(brew --prefix nvm)/nvm.sh` since `BASH_IT_HOMEBREW_PREFIX` is set from `brew --prefix` instead of `brew --prefix nvm`.
This fixes a regression caused by 65ef8e2e8be9fc6ded3611751725a32548c933c2.
I've tested this on my local instance where I have `nvm` installed via `brew`.
N/A
=> Fix loading of nvm for brew-installed nvm

clean_files.txt, plugins/available/url.plugin.bash
Added the plugin to handle the URL related workload and slugify function to add handle the heading to slug transformation.
While writing the headings of the blog or documentation on the markdown for the project, I need to go to external services to create the slug for the heading. This is very unproductive, so I have created the plugin for handling such transforms in the terminal.
Locally on Linux
=> Add url manipulation plugin

test/test_helper.bash
git worktree -d does not work on all versions of git worktree
this seems to resolve my problems running the tests locally
After debugging the tests_setup a bit, I found out that git worktree call failed. After further testing, it seems like the `-d` flag was responsible for the failures
Closes #2115 
By running the tests :)
=> tests: Use git worktree correctly

aliases/available/git.aliases.bash, clean_files.txt, docs/themes-list/inretio.rst, plugins/available/browser.plugin.bash, test/plugins/battery.plugin.bats, test/plugins/cmd-returned-notify.plugin.bats, themes/base.theme.bash, themes/inretio/inretio.theme.bash, themes/lambda/lambda.theme.bash
cleaning up lint that fails other PRs.
=> lint cleanup for shfmt

clean_files.txt, plugins/available/jgitflow.plugin.bash
Add pre-jgitflow function
Prepare a function to be executed before any jgitflow command
I have to check if I had access to my codeartifact repository before
any jgitflow command. With this improvement I can implement this function
on my ~/.bashrc file, and it would be executed before any jgitflow command.
```bash
function pre-jgitflow {
source aws-auth-codeartifact
return $(test -n "$CODEARTIFACT_AUTH_TOKEN")
}
```
I've been testing this process for a few months, but I don't know how to write
a unit test on this framework.
=> Add pre-jgitflow function

bash_it.sh
Reverts Bash-it/bash-it#2097 - seems like it was prematurely merged.
=> Revert "Revert "bash_it: source reloader.bash without arguments for the default enabling""

lib/command_duration.bash
This fixes #2206 (and a duplicate #2269) as described in comments https://github.com/Bash-it/bash-it/issues/2269#issuecomment-2478178460 and https://github.com/Bash-it/bash-it/issues/2206#issuecomment-2479428229.
*Describe your changes in detail*---The original code in the `master` branch used the locale `en_US.UTF-8` to ensure that the decimal point of `EPOCHREALTIME` is the period. However, the specific locale `en_US.UTF-8` is not ensured to exist in the system. More specifically, the locale `en_US.UTF-8` is the locale for English used in the United States. In other countries and regions, the locale installed in the system is probably the region's local language, and `en_US.UTF-8` is not installed.
The standard solution in this kind of situation is to specify the locale `C` or `POSIX`. …
=> lib/command_duration: avoid relying on a specific locale

themes/powerline/powerline.base.bash
Minor cleanup and alsö apply defaults to most variables in the `theme/powerline.base` file. This should make *no* changes to any existing themes. 
This should allow easier modificaiton/creation of powerline-based themes, as well as reduce duplicative code in existing themes. The idea is to reduce duplicate "base" files from powerline themes. 
Careful layering of includes to ensure I got the right bits.
=> theme/powerline base: cleanup and incorporate defaults

docs/README.md, install.sh, uninstall.sh
- update `install.sh`/`uninstall.sh`
- update `README.md`
- added handling of overriding of `CONFIG_FILE` if `BASH_IT_CONFIG_FILE` is passed to `install.sh/uninstall.sh`
this allows not touching user's bash config file, making it easier to detect regressions or compare 2 config files.
#2241
the change is pretty trivial, ran `BASH_IT_CONFIG_FILE=.bashrc_bash_it ./install.sh` resulted in created fle, bashrc untouched.
linux: rhel7, ubuntu 22, mac.
doubt there are any other side-effects, please review though.
- [x ] My code follows the code style of this project.
=> implement #2241 (custom config file during install)

.github/workflows/ci.yml, clean_files.txt, completion/available/bundler.completion.bash, completion/available/capistrano.completion.bash, completion/available/dirs.completion.bash, completion/available/docker-compose.completion.bash, plugins/available/sudo.plugin.bash, plugins/available/thefuck.plugin.bash, plugins/available/virtualenv.plugin.bash, plugins/available/z_autoenv.plugin.bash
continuing #2274, I have fixed up a few more files. this includes it so I won't pull this out of draft till that first one is merged.
pre-commit and then CI.
=> shfmt and shellcheck for a few more files

aliases/available/homebrew.aliases.bash
Enclose the aliases for `brew` within the `_command_exists` helper function.
We do not need to add aliases for package managers if the command does not exist.
This was done for other files that were already checking for commands via `command -v` in #1938.
Tested by syncing profiles between Debian, Fedora and macos
=> check whether `brew` command exists before aliasing

aliases/available/dnf.aliases.bash
Enclose the aliases for `dnf` within the `_command_exists` helper function.
We do not need to add aliases for package managers if the command does not exist.
This was done for other files that were already checking for commands via `command -v` in #1938.
Tested by syncing profiles between Debian, Fedora and macos
=> check whether `dnf` command exists before aliasing

plugins/available/virtualenv.plugin.bash
Check for the whole `pyenv virtualenvwrapper` command when loading virtualenv, instead of checking for `pyenv only`
This is useful if the system has `pyenv` installed but not `pyenv virtulenvwrapper`. The previous version just printed out  
```text
pyenv: no such command `sh-virtualenvwrapper'
```
which is just the pyenv stderr output.
Tested both with and `pyenv virtualenvwrapper` present. In both cases virtualenvwrapper.sh was also present. In poth cases ´ _virtualenvwrapper_version´ returned with the verion value. I  renamed the plugins in enabled, to ensure that pyenv gets loaded first during debugging. I don't remember the original loading order, but pyenv must be loaded first so that the plugin would work. Otherwise pyenv prints the following: 
```
Failed to initialize …
```
=> Fix for cases in the virtualenv plugin where pyenv is present but pyenv virtualenvwrapper isn't

themes/base.theme.bash
aws cli version 2 changed the variable used to override the default profile from AWS_DEFAULT_PROFILE to AWS_PROFILE. This pr updates the aws_profile function in the base theme to work with the new variable, but will still fall back to the old one if the new one is unset.
Custom themes using this function are useful for people who manage multiple AWS accounts. This will allow them to continue working with new versions of aws cli moving forward.
Tested with either and both variable in multiple themes on multiple machines and none of them caught fire. The change maintains backward compatibility, so the only people who could theoretically be impacted are those still using and old version of aws cli for some reason and also coincidentally setting AWS_PROFILE for some other purpose.
- [na] If …
=> update aws_profile in base theme to work with new aws cli versions

plugins/available/man.plugin.bash
this should fix #2261 without breaking any existing value of $LESS
=> a fix for #2261

completion/available/aliases.completion.bash
I was seeing issues where certain aliases do not complete as expected.
For example, my `alias gbD='git branch -D'` alias should provide completions to local branches only, and it does when run without an alias. However when running completion on the alias, I get all the branches which appears to be the git default completion response.
I tracked this down to an issue where an array was being incorrectly handled. The old handling caused this result, `COMP_WORDS=[‘git’, ‘branch -D’, 'ma']` (length 3) where `branch` and `-D` were combined into a single entry. This produces the incorrect behavior. By changing the array to string handling to better maintain individual arguments the new result is `COMP_WORDS=[‘git’, ‘branch’ ,‘-D’, 'ma']` (length 4) which correctly keeps `branch` and `-D` apart. …
=> Improve array handling in alias completion

clean_files.txt, themes/codeword/codeword.theme.bash, themes/cooperkid/cooperkid.theme.bash, themes/cupcake/cupcake.theme.bash
Followed instructions in #1696 to cleanup these files.
Addresses #1696
Ran `./lint_clean_files.sh` successfully.
=> Clean codeword, cooperkid, cupcake theme files

completion/available/crystal.completion.bash, completion/available/defaults.completion.bash, completion/available/drush.completion.bash, completion/available/fabric.completion.bash, completion/available/gradle.completion.bash, completion/available/homesick.completion.bash, completion/available/maven.completion.bash, completion/available/minishift.completion.bash, completion/available/openshift.completion.bash, completion/available/pew.completion.bash, completion/available/rvm.completion.bash, completion/available/todo.completion.bash, completion/available/travis.completion.bash, completion/available/vagrant.completion.bash, completion/available/virsh.completion.bash
cleaning up completions to please the shellcheck gods.
directory `completion/` was not tested due to a typo, and now it is, and I hope to have fixed the completions.
Nada. I am not a user of any of those commandline tools. I am just happy this passes the linters.
=> Lots of little fixes because I screwed up the clean_files.txt and missed unlinted completions

aliases/available/general.aliases.bash, plugins/available/base.plugin.bash
New function labeled `rex()`  servers a single purpose. Replace the file extensions of multiple file at once. File extensions usually does not quite matter in bash, but there is a few cases when one might needs to and this function simplifies the process from multiple commands into one.
```sh
function rex() {
about 'mass replace of the extension of multiple files'
param '1: extension to replace'
param '2: new extenstion'
example 'rex txt md'
group 'base'
local ext2replace="${1:-}"
local newext="${2:-}"
local files=(`ls *.$ext2replace`)
for file in "${files[@]}"; do mv "$file" "${file/%.$ext2replace/.$newext}"; done
}
```
Created multiple test files with different extensions, than proceeded to use `rex` to only change the specified extension which worked flawlessly
**Testing Environment** …
=> Add new feature to base.plugin.bash

completion/available/aliases.completion.bash
If a user has a completion defined for an alias, the alias completion script should not replace it.
I ad a completion for one of my alias and could not figure out why it was not working. Turns out the alias completion logic was replacing my completion. This is helpful for uses who make their own completions.
The end goal is for the alias completion script to not replace user provided completions for aliases that otherwise would have completion added by the alias completion script.
This requires a few core changes to achieve and support reload commands such as `bash-it reload`.
1. Before this change, only some completions added by this script used a wrapper function. Now all completions added by this script use a wrapper.
- This is needed as the wrapper contains identifying data to tell if …
=> Do not replace already existing completions

aliases/available/general.aliases.bash, aliases/available/git.aliases.bash, aliases/available/laravel.aliases.bash, aliases/available/terraform.aliases.bash, completion/available/terraform.completion.bash
improvements to readability, added a few aliases for completion, added OpenTofu compat for free...
Last minute ideas and fixes that popped in my head while looking at the 222-file long diff of the pre-release.
superficially
=> auto-compat with OpenTofu, co-pilot suggestions and other last-minute ideas

plugins/available/blesh.plugin.bash, plugins/available/fzf.plugin.bash, plugins/available/history-eternal.plugin.bash
found a few crucial clashes between the fzf and blesh plugins. this should fix them. credits to @akinomyoga for figuring this out.
Lesson of the day: RTFM
=> Cleanup Ble.sh plugin clashes

themes/powerline-multiline/powerline-multiline.base.bash
* fix parameter expansion for __powerline_last_status_prompt
* change ASCII code for beginning_of_line
* chane chain expansion for PROMPT
=> Fix for 2323 issue

.pre-commit-config.yaml, completion/available/terraform.completion.bash
finishing touches to the changes and updates from #2063 
protection of /vendor from pre-commit.
=> Cleanups that should have been part of  #2063

plugins/available/man.plugin.bash
it's a bit ugly but less ugly than before.  man is now an alias (imperfect) bit the LESS value and colours are not changing for everyone.
=> fix #2261 #2289 - $LESS is no longer clobbered globally
